### DISCUSSION TITLE
Can't we avoid the bloat from introducing leptos_router? (csr)

### DISCUSSION THREAD

**Discussion by jsprog** [leptos-rs/leptos#1073] [General]
When building a size optimized sample app, I could confirm that leptos_router is bloating WASM output size from 59KB to 174KB (nightly), A compatible sycamore app (80KB with routing) is more efficient in size compared to leptos.

I suppose that the regex crate is optional and not used by default for csr.
1. Could you elaborate what's causing the code to inflate by a non trivial margin just by introducing routing to app.
2. Is there a room for improvement.

```toml
# Cargo.toml (release is optimized for size)

[package]
name = "leptos-router-bloat"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.3.0" }
leptos_router = { version = "0.3.0", features = ["csr"] }

[profile.release]
codegen-units = 1 # Reduce Parallel Code Generation Units.
lto = true        # Enable Link Time Optimization. ("fat").
opt-level = "z"   # Optimize for size (default is 3).
panic = "abort"   # Abort on Panic    (default is "unwind").

# [unstable]
# build-std = ["std", "panic_abort", "core", "alloc"]
# build-std-features = ["panic_immediate_abort"]
```

```html
<!-- index.html (wasm-opt: optimized for size) -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leptos Router Bloat</title>

    <link data-trunk rel="rust" data-wasm-opt="z">
</head>
<body>
    
</body>
</html>
```

```rust
// src/main.rs

use leptos::*;
use leptos_router::{Router, Routes, Route};

fn main() {
    mount_to_body(|cx| {
        view! { cx, <App /> }
    })
}

#[component]
fn App(cx: Scope) -> impl IntoView {
    view! { cx,
        <h3>"Leptos Router Bloat"</h3>

        <nav>
            <a href="/">"Home"</a>
            " | "
            <a href="/about">"About"</a>
        </nav>
        <br />

        <main>
            // un-comment the following lines and build again
            // <Router>
            //     <Routes>
            //         <Route path="/" view=|cx| view! { cx, <Home /> } />
            //         <Route path="/about" view=|cx| view! { cx, <About /> } />
            //         <Route path="/*any" view=|cx| view! { cx, <NotFount /> } />
            //     </Routes>
            // </Router>
        </main>
    }
}

#[component]
fn Home(cx: Scope) -> impl IntoView {
    view! { cx, "Home Page" }
}

#[component]
fn About(cx: Scope) -> impl IntoView {
    view! { cx, "About Page" }
}

#[component]
fn NotFount(cx: Scope) -> impl IntoView {
    view! { cx, "Not Found!"}
}

```
