### DISCUSSION TITLE
How do you build a `cargo-leptos` project for the `x86_64-unknown-linux-musl` target?

### DISCUSSION THREAD

**Discussion by saikatdas0790** [leptos-rs/leptos#1963] [Q&A] [answered]
I've tried the following things but they didn't work:
- Adding `--target x86_64-unknown-linux-musl` to the `cargo-leptos build` command
  - `cargo-leptos` doesn't recognize this
- Running a plain `cargo build` with a musl target doesn't work because cargo leptos adds additional build parameters
- Adding a `.cargo/config.toml` file and adding musl as a target also makes the `cargo-leptos` build fail

What am I missing? Any input is appreciated 🙂

**Comment by gbj** [comment]
I just merged a PR to `cargo-leptos` a few days ago that may be useful here, but haven't made a new release yet.

It adds support for two additional settings for `cargo-leptos` in your `Cargo.toml`
```toml
# Pass additional parameters to the cargo process compiling to WASM
# 
# Optional. No default
lib_cargo-args = ["--timings"]

# Pass additional parameters to the cargo process to build the server
# 
# Optional. No default
bin_cargo-args = ["--timings"]
```
So `bin-cargo-args` may be a useful place to put the target.

IIRC the command to install from git is 
```bash
cargo install --git https://github.com/leptos-rs/cargo-leptos
```
