### DISCUSSION TITLE
Trouble with Events not triggering at all

### DISCUSSION THREAD

**Discussion by ogcatt** [leptos-rs/leptos#2157] [Q&A]
**Describe the bug**
I have a function which loads a threejs file to display an interface. This works fine when loading a single page, but after I visit another page and return back to it, the element disappears.

**Leptos Dependencies**
```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_actix = { version = "0.5", optional = true }
leptos_router = { version = "0.5", features = ["nightly"] }
```
To fix this, I tried loading it on pageshow and load (as events) and neither trigger on pageload, leaving the script always unloaded.

**Relevant Code**
```rust
#[component]
pub fn Banner() -> impl IntoView {
    let (loaded, load_up) = create_signal(false);

    let handle = window_event_listener(ev::pageshow, move |_ev| {
        load_up(true);
    });
    on_cleanup(move || handle.remove());

    view ! {
        <Show when=move || loaded.get() == true>
            <Script type_="module" src="/scripts/banner.js"></Script>
        </Show>
    }
}
```

Help would be appreciated. I can provide more details if needed.
