### DISCUSSION TITLE
lib is compiled two times

### DISCUSSION THREAD

**Discussion by TimerErTim** [leptos-rs/leptos#2185] [Q&A] [answered]
I have this function:

```rust
#[server(FetchPastTempTargets)]
pub async fn fetch_past_temp_targets() -> Result<Vec<MonitoringTempTargetData>, ServerFnError> {
    #[cfg(feature = "ssr")]
    return Ok(crate::behavior::load_temp_targets()?);
    #[cfg(not(feature = "ssr"))]
    Err(ServerFnError::ServerError("Unreachable".to_string()))
}
```

declared it in a module both lib.rs (wasm frontend) and main.rs (server) have access to. I can't compile it because the compilation of lib.rs fails with

```
  |
7 |     return Ok(crate::behavior::load_temp_targets()?);
  |                      ^^^^^^^^ could not find `behavior` in the crate root
```

Which should not happen under any circumstances because of 
- the `cfg(feature)` prevents this by completely blocking this code when compiling for wasm (lib).
- the macro expanding this to code differently on wasm (lib), where this should only be a remote call, and the server (bin), where this implementation would remain untouched.

The `cargo leptos` commands shows me that it successfully compiled the lib with 16 warnings, then says `Front compiling` and then shows me a failed compilation attempt of lib with 19 warnings. 

I am slowly losing my sanity to this one because it does not make any sense. It seems as if wasm (lib) is compiled twice, once with the correct "hydrate" feature, and once with the "ssr" feature enabled, which is beyond scuffed. I have no clue where this could originate from, I even started looking into the `cargo leptos` source code, which does not seem to have room for a bug of this magnitude occurring.

My leptos cargo.toml:

```toml
[package.metadata.leptos]
output-name = "app"

assets-dir = "public"

# The features to use when compiling the bin target
#
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]

# If the --no-default-features flag should be used when compiling the bin target
#
# Optional. Defaults to false.
bin-default-features = false

# The features to use when compiling the lib target
#
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
#
# Optional. Defaults to false.
lib-default-features = false

# The profile to use for the lib target when compiling for release
#
# Optional. Defaults to "release".
lib-profile-release = "wasm-release"
```
