### DISCUSSION TITLE
How to implement middleware using Server Functions?

### DISCUSSION THREAD

**Discussion by erlangparasu** [leptos-rs/leptos#3754] [Q&A] [answered]
How to implement middleware using Server Functions?
for adding some http filter like Auth, etc

**Comment by gbj** [comment, marked as answer]
[Here's an example](https://github.com/leptos-rs/leptos/blob/main/examples/server_fns_axum/src/app.rs#L260-L268).

**Reply by erlangparasu** [reply]
Thanks https://github.com/leptos-rs/leptos/blob/1a1e436cffa4236d10198935ef62810fd50525c5/examples/server_fns_axum/src/app.rs#L260-L268

**Comment by KevinGuancheDarias** [comment]
My project can't find a middleware macro

Those are my deps (leptos actix default)

```toml
[dependencies]
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true, features = ["macros"] }
console_error_panic_hook = "0.1"
leptos = { version = "0.7" }
leptos_meta = { version = "0.7" }
leptos_actix = { version = "0.7", optional = true }
tokio = { version = "1", optional = true}
leptos_router = { version = "0.7" }
wasm-bindgen = "=0.2.100"

[features]
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = [
  "dep:actix-files",
  "dep:actix-web",
  "dep:leptos_actix",
  "dep:tokio",
  "leptos/ssr",
  "leptos_actix/dont-use-islands-router",
  "leptos_meta/ssr",
  "leptos_router/ssr",
]
```
