### DISCUSSION TITLE
Has anyone managed to get helix setup with tailwind + emmet completions

### DISCUSSION THREAD

**Discussion by mnpqraven** [leptos-rs/leptos#4024] [Q&A] [answered]
I'm trying to setup a leptos project and there are some aspects that is still not working. Is there anyone using helix that has a working configuration running?  

I'm trying to get tailwind + emmet + rust_analyzer in feature code block running, here are the results so far:

1. no hover support in `ssr` feature code blocks, even though if i type inside the code block i do get suggestions + i already had `cargo = { features = "all" }` in `language.toml`
2. no emmet + tailwind suggestion inside `view!` macro. I tried to follow [this thread](https://github.com/helix-editor/helix/issues/2213) but to no avail

What i'm getting so far is the macro definitions on hover instead of tailwind
![image](https://github.com/user-attachments/assets/b9c2f06d-0b78-48e1-9fc4-c7147339185b)

here is my `language.toml` for reference
```
[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss", "emmet-lsp"]
auto-format = true

[language-server.tailwindcss]
command = "tailwindcss-language-server"
language-id = "rust"
args = ["--stdio"]

[language-server.tailwindcss.config]
tailwindCSS = { includeLanguages = { rust = "html", "*.rs" = "html" } }

[language-server.rust-analyzer.config]
procMacro = { ignored = { leptos_macro = ["server"] } }
cargo = { features = "all" }

[language-server.emmet-lsp.config]
emmet = { includeLanguages = { rust = "html", "*.rs" = "html" } }
```

**Comment by mnpqraven** [comment, marked as answer]
After a while i finally got helix configured with said programs, some issues were me being extremely careless and missed out on some obvious mistake, I'll try to make a checklist for anyone using helix and stumble across this discussion to have an easier time setting up helix with leptos

- [ ] language config files are in `your_project_root/.helix/languages.toml`. I made a really dumb mistake and made a typo (`language.toml` without the s) and couldn't figure out why the configuration didn't take any effect.
- [ ] tailwind, emmet lsp and leptosfmt will be configured here, if configured correctly you would be able so see tailwind in hover definitions, emmet autocomplete in rust file and leptos on save. Here is my configuration:
```toml
[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss", "emmet-lsp"]
auto-format = true

[language-server.tailwindcss]
command = "tailwindcss-language-server"
language-id = "rust"
args = ["--stdio"]

[language-server.tailwindcss.config]
tailwindCSS = { includeLanguages = { rust = "html", "*.rs" = "html" } }

[language-server.rust-analyzer.config]
rustfmt = { overrideCommand = ["leptosfmt", "--stdin", "--rustfmt"] }
features = "all"

[language-server.emmet-lsp.config]
emmet = { includeLanguages = { rust = "html", "*.rs" = "html" } }
```
- [ ] NOTE on tailwindcss definition hover: when you hover classes in the view macro, there would be hover definition for both tailwind class and a rust definition for that part in the macro and in helix the keybind for cycling through these hover definitions are `A-n` and `A-p` with (currently) no way to change them. Make sure you're not having conflicting keybinds with other programs (notably multiplexers and I've already been using these binds and had to change them)
- [ ] Follow the rest of the [leptos DX guide](https://book.leptos.dev/getting_started/leptos_dx.html) for other niceties. For me when i ignore the server proc macros i've had all these squiggly line lints from rust-analyzer showing up around the whole server function so currently i'm not ignoring those just yet.
