### ISSUE TITLE
Nested component Transitions render their fallback view on page refresh

### ISSUE THREAD

**Issue by PlGGS** [leptos-rs/leptos#1156]
**Describe the bug**
Nested component Transitions render both their fallback as well as their content views on a page refresh

**Leptos Dependencies**
```toml
leptos = { git="https://github.com/leptos-rs/leptos", default-features = false, features = [
	"serde", "tracing",
] }
leptos_meta = { git="https://github.com/leptos-rs/leptos", default-features = false }
leptos_axum = { git="https://github.com/leptos-rs/leptos", optional = true }
leptos_router = {  git="https://github.com/leptos-rs/leptos", default-features = false }
```

**To Reproduce**
1. Create two components with transitions for rendering async content
2. Nest one of the components within the other
3. Build and watch project
4. Refresh the page to see both the fallback and the content of the inner component's Transition

**Expected behavior**
I expected both components to render their content as normal

**Screenshots**
My inner component: (Ignore the unnecessary braces warning. That's a separate issue, because those braces are  necessary)
![image](https://github.com/leptos-rs/leptos/assets/20197872/6592712c-d6e1-4b94-8eb5-2f7a5cc48417)

DOM before refresh:
![image](https://github.com/leptos-rs/leptos/assets/20197872/e01e1158-fc04-4fc6-9dba-74e260d8b9a4)

DOM after refresh:
![image](https://github.com/leptos-rs/leptos/assets/20197872/434e4965-776f-4f26-a308-75c56e43c986)

It goes from looking like this:
![image](https://github.com/leptos-rs/leptos/assets/20197872/76a9ca47-54e5-452a-a952-d90dfc70150f)

To this:
![image](https://github.com/leptos-rs/leptos/assets/20197872/2fe81474-9ea5-4beb-893f-658aa0b07df2)

Thanks!
