### ISSUE TITLE
test(examples/js-framework-benchmark): error: cannot find macro `template` in this scope

### ISSUE THREAD

**Issue by agilarity** [leptos-rs/leptos#1182]
**Describe the bug**

The **js-framework-benchmark** example raises a clippy error.

**Leptos Dependencies**

```toml
[dependencies]
leptos = { path = "../../leptos", features=["template_macro"] }
console_log = "1"
log = "0.4"
# used in rand, but we need to enable js feature
getrandom = { version = "0.2.7", features = ["js"] }
rand = { version = "0.8.5", features = ["small_rng"] }
console_error_panic_hook = "0.1.7"

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.0"
web-sys = "0.3"
```

**To Reproduce**
1. Run `cargo make check-style` from the **examples/js-framework-benchmark** directory

_Produces..._
```shell
[cargo-make] INFO - cargo make 0.36.8
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Project: js-framework-benchmark-leptos
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: check-style
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "cargo" "fmt" "--" "--check" "--config-path" "../../"
[cargo-make] INFO - Execute Command: "cargo" "clippy" "--all-targets" "--all-features" "--" "-D" "warnings"
    Checking js-framework-benchmark-leptos v1.0.0 (/home/joseph/ws/leptos/examples/js-framework-benchmark)
error: cannot find macro `template` in this scope
   --> src/lib.rs:176:29
    |
176 | ...                   template! {
    |                       ^^^^^^^^

error: could not compile `js-framework-benchmark-leptos` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `js-framework-benchmark-leptos` (lib test) due to previous error
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
```

**Expected behavior**
Build should succeed with no errors.

**Screenshots**
N/A

**Additional context**

- This error was discovered while developing #1155
- The error was not previously detected because the **js-framework-benchmark** example was not configured as a member in **examples/Makefile.toml**
