### ISSUE TITLE
rust keywords like `use` as html tag name

### ISSUE THREAD

**Issue by M1cha** [leptos-rs/leptos#1202]
**Describe the bug**
Some tag names collide with rust keywords. For example SVGs `use`:
```html
<svg><use href="#circle-half"></use></svg>
```
That prevents one from using that within the `view` macro.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.3", default-features = false, features = ["serde"] }
leptos_meta = { version = "0.3", default-features = false }
leptos_router = { version = "0.3", default-features = false }
leptos_axum = { version = "0.3", optional = true }
```

**To Reproduce**
Just put the mentioned svg code in a `view` macro of any leptos project.

**Expected behavior**
Compile and render the svg. Instead, we get something like this:
```
error: expected identifier, found keyword `use`
  --> src/app.rs:34:15
   |
34 |         <svg><use href="#circle-half"></use></svg>
   |               ^^^ expected identifier, found keyword
   |
help: escape `use` to use it as an identifier
   |
34 |         <svg><r#use href="#circle-half"></use></svg>
   |               ++

error[E0425]: cannot find function `r#use` in module `leptos::leptos_dom::svg`
   --> src/app.rs:34:15
    |
34  |           <svg><use href="#circle-half"></use></svg>
    |                 ^^^ help: a constant with a similar name exists: `USE`
    |
   ::: /home/m1cha/.cargo/registry/src/github.com-1ecc6299db9ec823/leptos_dom-0.3.0/src/svg.rs:178:1
    |
178 | / generate_svg_tags![
179 | |   /// SVG Element.
180 | |   a,
181 | |   /// SVG Element.
...   |
310 | |   view,
311 | | ];
    | |_- similarly named constant `USE` defined here

For more information about this error, try `rustc --explain E0425`.

```
