### ISSUE TITLE
Attributes are not escaped properly

### ISSUE THREAD

**Issue by mforsb** [leptos-rs/leptos#1238]
**Describe the bug**
Input:
```html
<Body class="\" foo=\"bar\""/>
```
Expected output:
```html
<body class="&quot; foo=&quot;bar&quot;">
```

Actual output:
```html
<body class="&quot; foo=&quot;bar&quot;" foo="bar" "="">
```

**Leptos Dependencies**

```toml
leptos = { git = "https://github.com/leptos-rs/leptos", default-features = false, features = ["serde"] }
leptos_axum = { git = "https://github.com/leptos-rs/leptos", optional = true }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", default-features = false }
leptos_router = { git = "https://github.com/leptos-rs/leptos", default-features = false }
```
