### ISSUE TITLE
Nested elements sometimes pop out of containers when using SSR

### ISSUE THREAD

**Issue by Xendergo** [leptos-rs/leptos#1239]
**Describe the bug**
Sometimes nested elements sort of "pop out" of the container they're nested in, leaving two copies of the empty container around the element that's supposed to be inside.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

```toml
leptos = { version = "0.3", default-features = false, features = ["serde"] }
leptos_axum = { version = "0.3", optional = true }
leptos_meta = { version = "0.3", default-features = false }
leptos_router = { version = "0.3", default-features = false }
```
The error also seems to happen when tracking git.

**To Reproduce**
1. Create a template with cargo leptos new --git leptos-rs/start-axum
2. Replace HomePage with something like
```rust
#[component]
fn HomePage(cx: Scope) -> impl IntoView {
    view! { cx,
        <p>
            <p>"bruh"</p>
        </p>
    }
}
```
3. Run it and look at the inspector. The html generated is `<p></p> <p>bruh</p> <p></p>`

**Expected behavior**
The html generated should be `<p><p>bruh</p></p>`

**Additional context**
This seems to be an SSR specific issue since it works as expected using trunk.

Not all elements are popped out, and which elements are being used matters. This:
```rust
#[component]
fn HomePage(cx: Scope) -> impl IntoView {
    view! { cx,
        <p>
            <span>"test"</span>
            <div>"bruh"</div>
            "test"
        </p>
    }
}
```
generates `<p><span>test</span></p> <div>bruh</div> test <p></p>`. Using a `div` instead of a `p` will make it generate the correct HTML.

Viewing the page source shows that the HTML rendered by the server is correct.
