### ISSUE TITLE
Differences exist in dev and release hydration behaviour on hard reload

### ISSUE THREAD

**Issue by MinaMatta98** [leptos-rs/leptos#1242]
**Describe the bug**
`cargo leptos watch --release` <--- Hydration errors with multiple items missing after hard reload
`cargo leptos watch` <---- all elements render but warnings are present about signals dropped out of scope after hard reload

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true, features = ["macros", "secure-cookies"] }
actix-identity = { version = "0.5.2", optional = true }
actix-session = { version = "0.7.2", features = ["redis", "redis-rs-session"], optional = true }
actix = { version = "0.13.0", optional = true }
console_error_panic_hook = "0.1"
cfg-if = "1"
leptos = { version = "0.3.0", default-features = false, features = [
  "serde",
] }
leptos_meta = { version = "0.3.0", default-features = false }
leptos_actix = { version = "0.3.0", optional = true }
leptos_router = { version = "0.3.0", default-features = false }
# leptos-use = { version = "0.3.3", default-features = false, features = ["storage"] }
wasm-bindgen = "0.2.87"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
getrandom = { version = "0.2.9", features = ["js"] }
# serde_urlencoded = "0.7.1"
fancy-regex = { version = "0.11.0" }
validator = { version = "0.16.0", features = ["derive", "phone"] }
lazy_static = "1.4.0"
env_logger = "0.10.0"
web-sys = { version = "0.3.63", features = ["HtmlFormElement", "SubmitEvent", "KeyboardEvent", "Window", "Location", "History", "File", "FileList", "HtmlInputElement", "HtmlLiElement", "ScrollToOptions", "ScrollBehavior", "Element"] }
gloo-net = { version = "0.3.0", features = [] }
gloo-file = { version = "0.2.3", features = ["futures"] }
tokio = { version = "1.28.1", features = ["rt", "process"], optional = true }
wasm-bindgen-futures = "0.4.36"
sea-orm-migration = { version = "0.11.3"}
async-trait = "0.1.68"
sea-orm = { version = "0.11.3", features = ["sqlx-mysql", "runtime-tokio-native-tls", "with-chrono"], optional = true }
lettre = { version = "0.10.4", optional = true }
askama = "0.12.0"
base64 = "0.21.2"
chrono = "0.4.24"
rand = "0.8.5"
redis = "0.23.0"
argon2 = "0.5.0"
leptos_icons = { version = "0.0.12", default_features = false ,features = ["AiCloseCircleFilled", "HiChatBubbleOvalLeftEllipsisSolidMd", "HiUserCircleSolidMd", "HiArrowLeftCircleOutlineLg", "AiUserOutlined", "AiUserAddOutlined", "HiChevronLeftSolidLg", "BiUserCircleSolid", "HiEllipsisHorizontalSolidMd", "TbPhotoFilled", "HiPaperAirplaneOutlineLg", "LuImageOff", "IoClose", "IoTrash", "FiAlertTriangle"] }
futures-util = "0.3.28"
iter_tools = "0.1.4"
infer = "0.14.0"
actix-web-actors = { version = "4.2.0", optional = true }
image = { version = "0.24.6", features = ["rgb"], optional = true }
turbojpeg = { version = "0.5.2", features = ["image"], optional = true }
parking_lot = { version = "0.12.1", features = ["deadlock_detection", "hardware-lock-elision", "nightly", "arc_lock"] }
```

**Expected behavior**

**Screenshots**
![image](https://github.com/leptos-rs/leptos/assets/81748812/c09d9ab0-622a-4f02-9deb-cf69a1b490fa)
![image](https://github.com/leptos-rs/leptos/assets/81748812/872b8888-0a89-44b0-842f-7a2932f44c3b)

**Additional context**
It's difficult for me to reproduce this issue in a minimal version, but I suspect that the problem is related to the functionality of suspense.

Now, hydration bugs mean that there are mismatches between client and server. I am using lazy_static and storing a Arc<parking_lot::RwLock<RwSignal<Vec<String>>>>. It is possible that upon reload, they are partially dropped. However, what I cannot understand is why this only happens on release and not prod.

**Note that triggering a redirect via `<A/>` causes the items to successfully load**

If I find a workaround, as usual, I will post them here.

Thanks for your time.
