### ISSUE TITLE
Missing pkg files when build using custom pkg dir

### ISSUE THREAD

**Issue by snapiz** [leptos-rs/leptos#1340]
**Describe the bug**
When `cargo leptos build` or `cargo letpos watch` with `site-pkg-dir=example-pkg`, the wasm et js files is missing from `target/site/example-pkg`.

**Leptos Dependencies**

```toml
leptos = { version = "0.4.2", features = ["serde"] }
leptos_axum = { version = "0.4.2", optional = true }
leptos_meta = { version = "0.4.2"}
leptos_router = { version = "0.4.2"}
```

**To Reproduce**
1. cargo leptos new --git https://github.com/leptos-rs/start-axum
2. edit `site-pkg-dir=example-pkg` in Cargo.toml
3. run `cargo leptos build --release`
4. See the files missing at target/site/example-pkg

**Expected behavior**
The wasm et js files should exists in `target/site/example-pkg` like when `site-pkg-dir=pkg` where files can be found at `target/site/pkg`
