### ISSUE TITLE
panicked at 'called `Option::unwrap()` on a `None` value when building for release mode

### ISSUE THREAD

**Issue by tqwewe** [leptos-rs/leptos#1382]
**Describe the bug**
My app thus far works great in debug mode with no errors, but when building to release, I get a panic in the console:
```js
panicked at 'called `Option::unwrap()` on a `None` value', /home/ari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.2/src/components/dyn_child.rs:349:38
```

The code that panics in dyn_child.rs is:
https://github.com/leptos-rs/leptos/blob/c1c49ce53be5c85cbb3505bfd8b7a86dbc14fd60/leptos_dom/src/components/dyn_child.rs#L347-L352

Could this be as simple as removing the `unwrap` and doing an `if let Some` check instead?

**Leptos Dependencies**

```toml
leptos = { version = "0.4", features = ["nightly"] }
leptos_axum = { version = "0.4" }
leptos_meta = { version = "0.4", features = ["nightly"] }
leptos_router = { version = "0.4", features = ["nightly"] }
leptos_dom = { version = "0.4" }
```

**To Reproduce**
I'm not sure :(

**Expected behavior**
This should not panic, as there's no error when running in debug mode.

**Screenshots**

![image](https://github.com/leptos-rs/leptos/assets/16362377/35f82ad9-b2e5-4cde-9eea-42c1974c297f)

**Additional context**
-
