### ISSUE TITLE
Numbers not allowed in tag name

### ISSUE THREAD

**Issue by ThePrimeagen** [leptos-rs/leptos#1434]
**Describe the bug**
When trying to use the hottest new framework, HTMX, which is not a framework, i run into an error trying to redirect request responses based on status codes.

![image](https://github.com/leptos-rs/leptos/assets/4458174/e97c9b36-bb51-4491-b80a-922ea209b43b)

**Leptos Dependencies**
```toml
[package]
name = "htmx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0.71"
env_logger = "0.10.0"
leptos = { version = "0.4.1", features = ["ssr"] }
libsql-client = "0.31.8"
log = "0.4.19"
qstring = "0.7.2"
serde = { version = "1.0.164", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }
```

**To Reproduce**
Steps to reproduce the behavior: Copy and paste in this code

```rust
pub fn TodoForm(cx: Scope, todos: Vec<TodoItem>, route: &'static str) -> impl IntoView {
    // create user interfaces with the declarative `view!` macro
    return view! { cx,
        <form hx-post="{route}"
            hx-target="#todos"
            hx-target-500="#serious-errors"
            hx-swap="afterbegin"
            hx-trigger="submit">
            <input name="title" required minlength="1" type="text" placeholder="More like Todone, amirite?" />
            <button type="submit">"add me daddy"</button>
        </form>
        <Todos todos=todos />
    };
}
```

**Expected behavior**
I would assume that we want to be able to work with HTMX status routing :)

**Additional context**
Greg is great, and so is Ben and Underscore Funk
