### ISSUE TITLE
Safari loads wasm twice

### ISSUE THREAD

**Issue by 617a7aa** [leptos-rs/leptos#1450]
**Describe the bug**
In Safari (Version 17.0 (19616.1.20.11.3)), Leptos loads the wasm file twice. [Production example](https://valera.co) - source code [here](https://github.com/valeralabs/web/tree/mk3) (mk3 branch)

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { git = "https://github.com/leptos-rs/leptos", default-features = false, features = [
	"rkyv",
] }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", default-features = false }
leptos_actix = { git = "https://github.com/leptos-rs/leptos", default-features = false, optional = true }
leptos_router = { git = "https://github.com/leptos-rs/leptos", default-features = false }
```

**To Reproduce**
1. Go to ['valera.co'](https://valera.co) in Safari
2. Open web console, go to networking
3. Reload page
4. Wasm gets loaded once from XHR in HTML, twice from web.js from fetch

**Expected behavior**
One load of wasm

**Screenshots**

<img width="100%" alt="Screenshot 2023-07-27 at 11 44 46" src="https://github.com/leptos-rs/leptos/assets/67651251/807907dd-a8eb-4722-9649-680c1ace7f5d">
