### ISSUE TITLE
Component with "mut" props yields compile error

### ISSUE THREAD

**Issue by awesomelemonade** [leptos-rs/leptos#1458]
**Describe the bug**
Can't seem to mark parameters in #[component] as mutable. For example:
```rust
#[component]
fn TestMutCallback<F>(cx: Scope, mut callback: F) -> impl IntoView
where
    F: FnMut(u32) + 'static,
{
    view! { cx,
        <div class="bg-blue-500 w-20 h-20">
            <button on:click=move |_| {
                callback(5);
            }>
                TEST
            </button>
        </div>
    }
}
```

We can simply do a workaround w/ shadowing:
```rust
#[component]
fn TestMutCallback<F>(cx: Scope, callback: F) -> impl IntoView
where
    F: FnMut(u32) + 'static,
{
    let mut callback = callback; // Workaround because we can't create mutable props
    view! { cx,
        <div class="bg-blue-500 w-20 h-20">
            <button on:click=move |_| {
                callback(5);
            }>
                TEST
            </button>
        </div>
    }
}

```

This seems to be caused by the #[component] prop naively pasting the "mut" attribute into the struct fields, which is a compile error.

**Leptos Dependencies**

```toml
leptos = { version = "0.4", features = ["csr", "nightly"] }
leptos_meta = { version = "0.4", features = ["csr", "nightly"] }
leptos_router = { version = "0.4", features = ["csr", "nightly"] }
```
