### ISSUE TITLE
Clicking links inside a Suspense panics

### ISSUE THREAD

**Issue by johansmitsnl** [leptos-rs/leptos#1465]
**Describe the bug**

When you use a link in the router that is wrapped inside a `Suspense`

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

```toml
leptos = { version = "0.5.0-alpha", default-features = false, features = ["serde", "nightly"] }
leptos_router = {version = "0.5.0-alpha", default-features = false}
```

**To Reproduce**
1. Go to When you click a link
4. `panicked at 'context of type "leptos_reactive::suspense::GlobalSuspenseContext" to be present', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.0-alpha/src/context.rs:202:9`

**Expected behavior**
Be able to click on links
