### ISSUE TITLE
0.5.0-beta Attempted to get a memo after it was disposed

### ISSUE THREAD

**Issue by johan-smits** [leptos-rs/leptos#1488]
**Describe the bug**

**Leptos Dependencies**

```toml
leptos = { version = "0.5.0-alpha2", default-features = false, features = ["serde", "nightly"] }
leptos_router = { version = "0.5.0-alpha2", default-features = false }
```

**To Reproduce**

```rs
    let app_state = expect_context::<RwSignal<AppState>>();

    let (token, _) = create_slice(
        // we take a slice *from* `state`
        app_state,
        // our getter returns a "slice" of the data
        |state| state.token,
        // our setter describes how to mutate that slice, given a new value
        |state, token| state.token = token,
    );
```

Open your app and it will show the error.

**Expected behavior**
Don't panic.

**Screenshots**
![image](https://github.com/leptos-rs/leptos/assets/3228882/267aba2e-c367-4032-a9dd-6d6e89943c43)

**Additional context**
This code works in the `0.4.5` version.
