### ISSUE TITLE
use_params_map causes server fn to reload on hashtag navigation

### ISSUE THREAD

**Issue by ankarhem** [leptos-rs/leptos#1516]
**Describe the bug**
The server function is retriggered (once) if navigating withing the page to a header etc. After this first "retrigger" of the server function, it will no longer trigger on subsequent in-page navigations.

**Leptos Dependencies**

```toml
leptos = { version = "0.4", features = ["nightly"] }
leptos_meta = { version = "0.4", features = ["nightly"] }
leptos_actix = { version = "0.4", optional = true }
leptos_router = { version = "0.4", features = ["nightly"] }
```

**To Reproduce**
1. Go to /
2. Open network tab
3. Click on link "/hello"
4. See request (expected)
5. Click on link "/hello#h1"
6. See another request (unexpected)

**Expected behavior**
Should not retrigger

**Additional context**
Reproduction repo: https://github.com/ankarhem/leptos-nav-bug
