### ISSUE TITLE
`load_resource` is discarding errors from `Result` values

### ISSUE THREAD

**Issue by srid** [leptos-rs/leptos#1530]
**Describe the bug**

https://github.com/leptos-rs/leptos/blob/aa58cedc156d9b90fe88c82f1c810626d6f083c8/leptos_reactive/src/resource.rs#L410-L412

Discord context: https://discord.com/channels/1031524867910148188/1031524868883218474/1139637277950214255

The use of `expect_throw` disards the `Result`'s own error which I'd like to see in browser console. I only see the generic errors: 
![image](https://github.com/leptos-rs/leptos/assets/3998/c78ce030-8071-41ea-a160-4d6d79f3d9c9)

**Leptos Dependencies**

```toml
leptos = { version = "0.4", features = ["serde"] }
leptos_axum = { version = "0.4", optional = true }
leptos_meta = { version = "0.4" }
leptos_router = { version = "0.4" }
```

**Expected behavior**
Instead of seeing `Error: could not deserialize Resource JSON` (see screenshot above), I'd like to also see what the `Result`'s error value is.

**Additional context**

To reproduce locally, run `cargo leptos watch` on this tree (see below) and go to the "Nix Health" route.

https://github.com/juspay/nix-browser/commit/1d0fb596ffe2ac17b1f55f8e54108df2baffc703
