### ISSUE TITLE
Route switch stops working when an <Outlet/> sibling component reads a resource

### ISSUE THREAD

**Issue by srid** [leptos-rs/leptos#1569]
**Describe the bug**
I came across this strange bug. Consider a route that renders like this,

```html
        <div class="items-left">
            <ThingsNav/>
            <Outlet/>
        </div>
```

Now suppose `<ThingsNav />` reads a resource using `create_resource` (which the sub-route also does), then none of the link clicks on that nav work at all. To workaround this bug, you have to move the `<ThingsNav/>` component to inside of each sub route components.

(See the linked PR below for more details)

**Leptos Dependencies**

Using 0.4.9 (exact version are in Cargo.lock in the PR linked below),

```toml
leptos = { version = "0.4", features = ["serde"] }
leptos_axum = { version = "0.4", optional = true }
leptos_meta = { version = "0.4" }
leptos_router = { version = "0.4" }
```

**To Reproduce**
Detailed repro steps here: https://github.com/srid/leptos-fullstack/pull/19

**Expected behavior**
See https://github.com/srid/leptos-fullstack/pull/19

**Screenshots**
See https://github.com/srid/leptos-fullstack/pull/19

**Additional context**
Discord link: https://discord.com/channels/1031524867910148188/1143326756334489651
