### ISSUE TITLE
API with both POST and GET Methods

### ISSUE THREAD

**Issue by realeinherjar** [leptos-rs/leptos#1606]
**Describe the bug**

Defining both POST and GET methods will return only the GET method.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.5.0-beta", features = ["nightly"] }
leptos_meta = { version = "0.5.0-beta", features = ["nightly"] }
leptos_router = { version = "0.5.0-beta", features = ["nightly"] }
leptos_axum = { version = "0.5.0-beta" }
```

**To Reproduce**

Using the [`leptos-rs/start-axum-workspace`](https://github.com/leptos-rs/start-axum-workspace) change the `server/scr/main.rs` to:

```rust
#[server(MyFun, "/api", "GetJson", "balance")]
pub async fn balance() -> Result<usize, ServerFnError>{
    Ok(0)
}
#[server(MyFun2, "/api", "Url", "balance")]
pub async fn balance_post() -> Result<usize, ServerFnError>{
    Ok(1)
}

#[tokio::main]
async fn main() {
...
    let app = Router::new()
        .route("/api/*fn_name", post(handle_server_fns))
        .route("/api/*fn_name", get(handle_server_fns)) // Add a `get` as well
        .leptos_routes(&leptos_options, routes, || view! {  <App/> })
        .fallback(file_and_error_handler)
        .with_state(leptos_options);
...
}
```

I've followed the instructions in #1311.

**Expected behavior**

Now do a `curl` using `GET`/`POST`.
It should return `1` for `POST` and `0` for `GET`.

But it does not. The `POST` method is overwritten with the `GET` method somehow:

```bash
> curl -X GET http://localhost:3000/api/balance
0
> curl -X POST http://localhost:3000/api/balance
0 # <----- This should be `1`, right?
```
