### ISSUE TITLE
Some hydrated elements are duplicated in release mode

### ISSUE THREAD

**Issue by vhfmag** [leptos-rs/leptos#1609]
**Describe the bug**
A number of users has reported (see [the Discord thread](https://discord.com/channels/1031524867910148188/1143951840677986374)) an issue where some hydrated elements are duplicated when compiled in release mode. The issue doesn't happen if the app isn't compiled in release mode, and I wasn't able to pinpoint in which conditions it happens, but here's a minimal app that reproduces the issue: https://github.com/vhfmag/leptos-release-mode-hydration-issue.

<table id="recordings"><thead><tr><th>Non-release mode</th><th>Release mode</th></tr></thead><tbody><tr><td>

https://github.com/leptos-rs/leptos/assets/357835/032b1be2-4b01-4b2b-80cb-b6fb0928919f

</td><td>

https://github.com/leptos-rs/leptos/assets/357835/bc8e1027-c8f8-4526-bdb5-4c2b5b4cece1

</td></tr></tbody></table>

The issue has been reported to happen for, at least, 0.4.6 (Alden Moreton), 0.4.8 (myself, when first reporting the issue), 0.4.10 (Alden Moreton, my reproduction repo), and 0.5.0-beta (myself in my pet project, currently).

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.4", features = ["nightly"] }
leptos_meta = { version = "0.4", features = ["nightly"] }
leptos_actix = { version = "0.4", optional = true }
leptos_router = { version = "0.4", features = ["nightly"] }
```

**To Reproduce**
As mentioned, I wasn't able to pinpoint a precise set of conditions, but there is a sample app that reproduces the issue: https://github.com/vhfmag/leptos-release-mode-hydration-issue.

It seems to require `create_resource` + `Suspense`/`Transition`, but otherwise it's pretty broad.

**Expected behavior**
Hydrated elements should be modified, not duplicated, when updated.

**Screenshots**
See [recordings](#recordings) above.
