### ISSUE TITLE
is_active detection in router's A component incorrect

### ISSUE THREAD

**Issue by flo-at** [leptos-rs/leptos#1655]
**Describe the bug**
I stubmled across this when I added a condition style class with the `aria-current=page` attribute. In some cases, more than one link in the navigation bar was highlighted. This happens when there are two (or more) routes like `/foo/test` and `/foo/test_bar`. This is because the latter one starts with the first one. This is what is checked to determine `is_active` [here](https://github.com/leptos-rs/leptos/blob/495862e9f99d94ebb30d0b065a9d650e6c15fe2e/router/src/components/link.rs#L136C2-L136C2).

**Leptos Dependencies**
```toml
leptos = { version = "0.4.10", features = ["csr", "nightly"] }
leptos_meta = { version =  "0.4.10", features = ["csr", "nightly"] }
leptos_router = { version = "0.4.10", features = ["csr", "nightly"] }
```

**To Reproduce**
1. Create two routes, `/foo/test` and `/foo/test_bar`.
2. Use the `aria-current=page` attribute to conditionally change the text color of the link in the navigation bar.
3. Click on the link to `/foo/test_bar`.
4. Both links are considered active and change their color.

**Expected behavior**
`/foo/test` and `/foo/test_bar` should be considered different routes that cannot be active at the same time.
