### ISSUE TITLE
changing site-pkg-dir config not working

### ISSUE THREAD

**Issue by paul2t** [leptos-rs/leptos#1686]
**Describe the bug**
In a multi-package project with ssr. In the config of lepto in `Cargo.toml`: Changing `site-pkg-dir` to something else than `"pkg"`, leads to js and wasm files not being copied to the specified directory.

**Leptos Dependencies**
```toml
leptos = "0.4.8"
leptos_meta = "0.4.8"
leptos_router = "0.4.8"
leptos_axum = { version = "0.4.8", optional = true }
```

**To Reproduce**
1. Create a multi-package project.
2. In `Cargo.toml` change `site-pkg-dir = "pkg"` to `site-pkg-dir = "app"`
3. `cargo leptos build`
4. See in `target/site/app/` directory that there is no js and no wasm file.

**Expected behavior**
The files should be copied to the specified directory.
