### ISSUE TITLE
Reading from already completed resource using .with gets stuck in fallback

### ISSUE THREAD

**Issue by akarras** [leptos-rs/leptos#1751]
**Describe the bug**
When reading a resource using .with the resource will load on the initial page load, but navigating between different pages that might use the same resource results in the components getting stuck in the fallback.

**Leptos Dependencies**

Currently on [2b59ae18](https://github.com/leptos-rs/leptos/commit/2b59ae18bc0b415f67bbb323b07f4518acfc85aa)
```toml
leptos = { git = "https://github.com/leptos-rs/leptos.git", default-features = false, features = [
  "serde",
  "nightly"
] }
leptos_axum = { git = "https://github.com/leptos-rs/leptos.git" }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", default-features = false }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git", default-features = false }
```

**To Reproduce**
[minimal reproduction](https://gist.github.com/akarras/425ee3fd9c552c9487dcbc32de2a934a)
1. With the gist provided, serve using cargo-leptos with SSR. 
2. navigate to the other page
3. observe "Loading" stays.

**Expected behavior**
Suspense can resolve even if resource is loaded

**Additional context**
This occurs with `create_local_resource` or `create_resource`
