### ISSUE TITLE
js fetch #1554 seems to break custom api routes

### ISSUE THREAD

**Issue by dgsantana** [leptos-rs/leptos#1787]
**Describe the bug**
When using custom routes for the server api on axum (not verified on actix), the new spawn_task causes a panic due to `spawn_local called from outside of a task::LocalSet`.

**Leptos Dependencies**

```toml
leptos = { version = "0.5.0-rc3", default-features = false, features = [
    "nightly",
] }
leptos_axum = { version = "0.5.0-rc3", default-features = false }
leptos_config = { version = "0.5.0-rc3", default-features = false }
leptos_dom = { version = "0.5.0-rc3", default-features = false }
leptos_macro = { version = "0.5.0-rc3", default-features = false }
leptos_reactive = { version = "0.5.0-rc3", default-features = false }
leptos_router = { version = "0.5.0-rc3", default-features = false, features = [
    "nightly",
] }
leptos_server = { version = "0.5.0-rc3", default-features = false }
leptos_meta = { version = "0.5.0-rc3", default-features = false, features = [
    "nightly",
] }
server_fn = { version = "0.5.0-rc3", default-features = false }
```

with crates.io patch
```toml
leptos = { git = "https://github.com/leptos-rs/leptos" }
leptos_axum = { git = "https://github.com/leptos-rs/leptos" }
leptos_config = { git = "https://github.com/leptos-rs/leptos" }
leptos_dom = { git = "https://github.com/leptos-rs/leptos" }
leptos_macro = { git = "https://github.com/leptos-rs/leptos" }
leptos_reactive = { git = "https://github.com/leptos-rs/leptos" }
leptos_router = { git = "https://github.com/leptos-rs/leptos" }
leptos_server = { git = "https://github.com/leptos-rs/leptos" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos" }
server_fn = { git = "https://github.com/leptos-rs/leptos" }
```

**To Reproduce**
Use one of the axum templates.

Add to the routes the following:
```rust
    let app = Router::new()
        .route(
            "/api/*fn_name",
            get(handle_leptos_api).post(handle_leptos_api),
        )
...
```

The route handler itself
```rust
async fn handle_leptos_api(
    query: RawQuery,
    path: Path<String>,
    headers: HeaderMap,
    State(state): State<AppState>,
    ConnectInfo(addr): ConnectInfo<SocketAddr>,
    req: Request<Body>,
) -> impl IntoResponse {
    handle_server_fns_with_context(
        path,
        headers,
        query,
        move || {
            provide_context(state.clone());
        },
        req,
    )
    .await
}
```

Navigate to a route that calls any server api. It should give a panic the server on the route (the server keeps running).

**Expected behavior**
No panic when a api call is used in either the SSR rendering phase or the frontend navigation.

**Additional context**
Didn't happen on RC2.
