### ISSUE TITLE
leptos 0.5.0-rc3 SSR hydration bug

### ISSUE THREAD

**Issue by beckend** [leptos-rs/leptos#1790]
**Describe the bug**
Using standard elements causes the bug, I based the project on the tailwindcss example folder.

**Leptos Dependencies**

```toml
leptos = { features = [], version = '0.5.0-rc3' }
leptos_meta = { features = [], version = '0.5.0-rc3' }
leptos_axum = { optional = true, version = '0.5.0-rc3' }
leptos_router = { features = [], version = '0.5.0-rc3' }
```

**To Reproduce**
1. clone https://github.com/beckend/leptos-hydration-bug-1
2. cargo leptos watch
3. visit http://localhost:3000
4. edit `./src/client/routes/home.rs` On lines 14-24 there are elements ready to be used, uncomment any element you want, and see the SSR bug in browser console.
5. See error

**Expected behavior**
No hydration bugs using simple elements

**Screenshots**
![2023-09-26T17:30:05,363679543-03:00](https://github.com/leptos-rs/leptos/assets/6056334/4d7588cc-ce74-4dca-a7e0-132c38955b7f)
