### ISSUE TITLE
Bug with <For /> when using a struct array

### ISSUE THREAD

**Issue by cchance27** [leptos-rs/leptos#1802]
**Describe the bug**
Getting lots of "component with id 1-0-40o not found, ignoring it for hydration" errors when i'm trying to use a <For /> when i've used a function to result in a function.

**Leptos Dependencies**
```toml
leptos = { git="https://github.com/leptos-rs/leptos.git", features = ["serde", "nightly"] }
leptos_axum = { git="https://github.com/leptos-rs/leptos.git", optional = true }
leptos_meta = { git="https://github.com/leptos-rs/leptos.git", features = ["nightly"] }
leptos_router = { git="https://github.com/leptos-rs/leptos.git", features = ["nightly"] }
```

**To Reproduce**
1. clone **https://github.com/cchance27/broken-leptos-forloop**
2. Run with cargo leptos watch
3. Goto http://localhost:3000

**Expected behavior**
For loop with the data from the serverfn remapped to a vec outputted in divs.

**Screenshots**
![image](https://github.com/leptos-rs/leptos/assets/13766359/2104165b-3370-49f4-8c78-182a05f07f4a)

**Additional context**
We discussed the issue on discord, heres the repo example
