### ISSUE TITLE
Error with `Suspense` and `create_local_resource`

### ISSUE THREAD

**Issue by kaivol** [leptos-rs/leptos#1823]
**Leptos Dependencies**

```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
```

Consider the following code example:
```rust
#[server]
pub async fn server_function() -> Result<(), ServerFnError> {
    tokio::time::sleep(std::time::Duration::from_secs(5)).await;

    Ok(())
}

#[component]
fn HomePage() -> impl IntoView {
    let resource = create_local_resource(|| (), |_| async move { server_function().await.unwrap() });

    view! {
        <h1>"Welcome to Leptos!"</h1>
        <button 
            on:click=move |_| resource.refetch() >
            "Refresh"
        </button>
        <div>
            <Suspense
                fallback=move || view! { "Loading" } >
                {move || resource.map(|_| "Ready")}
            </Suspense>
        </div>
    }
}
```

**Expected behavior**
I expect it to show "Loading" for 5 seconds after loading the page and whenever I press on "Refresh", and "Ready" otherwise.

**Actual behavior**
Instead, initially it renders nothing. Then, after 5 seconds, "Ready" appears.
When I then press the button, it shows "ReadyLoading" for 5 seconds, before going blank again and throwing an error: 
```
panicked at C:\Users\Kai\.cargo\registry\src\index.crates.io-6f17d22bba15001f\leptos_dom-0.5.0\src\components\dyn_child.rs:263:33:
before to not err: JsValue(HierarchyRequestError: CharacterData.before: The new child is an ancestor of the parent 
...
```

Wrapping the _fallback_ text in an `<p>` element like 
```rust
fallback=move || view! { <p>"Loading"</p> } >
```
makes this error go away, but the behavior is still not as expected:
Now the `<p>` element is rendered on subsequent refreshes (so not initially after loading the page), but its text is missing (but it's observable in the HTML inspector).
Also, there is a warning in the console: `element with id 1-0-5 not found, ignoring it for hydration`
When the resource is not currently loading, "Ready" is shown as expected.
