### ISSUE TITLE
Attribute spreading with string values causes spaces to split into separate attributes

### ISSUE THREAD

**Issue by JonahLund** [leptos-rs/leptos#1826]
**Describe the bug**
Using the new attribute spreading syntax {..attrs} with an attribute that has a string value with spaces will split the spaces into separate attributes.

Example:
```rust
#[component]
pub fn Input(
    #[prop(attrs)] attrs: Vec<(&'static str, Attribute)>,
) -> impl IntoView {
    view! {
        <input {..attrs} />
    }
}

#[component]
fn HomePage() -> impl IntoView {
    view! {
        <Input attr:placeholder="Enter your email" />
    }
}
``` 

This will produce the following html output:
```html
<input placeholder="Enter" your="" email="">
```

**Leptos Dependencies**

```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_actix = { version = "0.5", optional = true }
leptos_router = { version = "0.5", features = ["nightly"] }
```

**To Reproduce**
Use the starter template, copy and paste the components above

**Expected behavior**
Should not split string attribute values with spaces into separate attributes with the {..attrs} syntax
