### ISSUE TITLE
Using multiple <Html> in SSR behaves different from hydration

### ISSUE THREAD

**Issue by dgsantana** [leptos-rs/leptos#1828]
**Describe the bug**
When using multiple <Html> meta tags, the "last" one sets all the props for it. It should not override lang, class and dir, if the values are None.

**Leptos Dependencies**

```toml
leptos = { version = "0.5", features = ["serde"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5"}
leptos_router = { version = "0.5"}
```

**To Reproduce**
Clone the https://github.com/leptos-rs/start-axum repository.
1. Go to app.rs  and in theApp component add a <Html lang="fr-FR"/>
2. In the same file, on the component HomePage, add <Html class="no_lang_in_ssr"/>
3. Run the project using cargo leptos watch

**Expected behavior**
The behavior expected was to have the lang attribute on the <Html> tag, beside the class attribute, but only the class attribute appears.

**Additional context**
Going to create a PR to propose a fix for this.
