### ISSUE TITLE
Hydration error with Suspense > Outlet > Suspense

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#1863]
**Describe the bug**
Using a Suspense-based route guard to conditionally render an Outlet, with a child route that itself loads something via Suspense, causes a hydration issue.

**Leptos Dependencies**

```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
```

**To Reproduce**

```rust
use leptos::*;
use leptos_router::*;

#[server]
pub async fn get_user() -> Result<(), ServerFnError> {
    Ok(())
}

#[server]
pub async fn data() -> Result<(), ServerFnError> {
    Ok(())
}

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <div>
                <div>"NavBar"</div>
                <main>
                    <div>
                        <Routes>
                            <Route path="" view=LoginGuard>
                                <Route path="" view=Child/>
                            </Route>
                        </Routes>
                    </div>
                    <div>
                        <div>
                            <button on:click=move |_| leptos::logging::log!("Did I hydrate?")>"Click"</button>
                        </div>
                    </div>
                </main>
            </div>
        </Router>
    }
}

#[component]
fn LoginGuard() -> impl IntoView {
    let guard_data = Resource::once(get_user);
    view! {
        <Suspense>
            {move || guard_data.and_then(|_| view! { <Outlet/> })}
        </Suspense>
    }
}

#[component]
pub fn Child() -> impl IntoView {
    let nested_data = Resource::once(data);

    view! {
        <Suspense>
            <pre>{
                move || {
                    format!("{:?}", nested_data.get())
                }
            }</pre>
        </Suspense>
    }
}
```
