### ISSUE TITLE
Panic because spawn_local called from outside of a task::LocalSet

### ISSUE THREAD

**Issue by Dragonink** [leptos-rs/leptos#1872]
The server panics with the following error "`spawn_local` called from outside of a `task::LocalSet`" (at leptos_reactive/src/spawn.rs:87:13) when trying to connect to the server.

**In the server router**
```rust
.leptos_routes_with_context(
	state,
	leptos_axum::generate_route_list(App),
	move || {
		leptos::provide_context(client.clone());
	},
	App,
)
```
where `state` is my Axum state, and `client` is a `reqwest::Client`.

**In the client `#[component]` functions**
```rust
let client = use_context::<reqwest::Client>();
let resource = create_resource(|| (), move |()| {
	let client = client.clone();
	async move {
		client.get()
		// ...
	}
});
```

**Leptos Dependencies**
```toml
leptos = "0.5.1"
leptos_axum = "0.5.1"
leptos_meta = "0.5.1"
leptos_router = "0.5.1"
```

**Comment by gbj** [comment]
Could you please provide a reproducible example?

**Comment by Dragonink** [comment]
**`client/Cargo.toml`**
```toml
[package]
name = "leptos_mre-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[target.wasm32-unknown-unknown.dependencies]
leptos = { version = "0.5.1", default-features = false, features = ["hydrate"] }
leptos_router = { version = "0.5.1", features = ["hydrate"] }
wasm-bindgen = "0.2.87"
[target.x86_64-unknown-linux-gnu.dependencies]
leptos = { version = "0.5.1", default-features = false, features = ["ssr"] }
leptos_router = { version = "0.5.1", features = ["ssr"] }
```

**`client/src/lib.rs`**
```rust
use leptos::*;
use leptos_router::*;
#[cfg(target_arch = "wasm32")]
use wasm_bindgen::prelude::*;

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen(start)]
fn start() {
	mount_to_body(|| {
		view! { <App /> }
	});
}

#[component]
pub fn App() -> impl IntoView {
	view! {
		<Router fallback=|| view! { <h1>"NOT FOUND"</h1> }.into_view()>
			<Routes>
				<Route path="" view=Home />
			</Routes>
		</Router>
	}
}

#[component]
fn Home() -> impl IntoView {
	let motd = create_resource(
		|| (),
		move |()| {
			async move {
				"Hello world!".to_owned()
			}
		},
	);

	view! {
		<h1>{motd.get()}</h1>
	}
}
```

**`server/Cargo.toml`**
```toml
[package]
name = "leptos_mre-server"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos_mre-client = { path = "../client" }
axum = "0.6.20"
axum-extra = "0.8.0"
leptos = { version = "0.5.1", default-features = false }
leptos_axum = { version = "0.5.1", default-features = false }
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros"] }
```

**`server/src/main.rs`**
```rust
use axum::{http::StatusCode, routing, Router, Server};
use axum_extra::response::{JavaScript, Wasm};
use leptos::LeptosOptions;
use leptos_axum::LeptosRoutes;
use leptos_mre_client::App;

#[tokio::main]
async fn main() {
	let leptos_options = LeptosOptions::builder()
		.output_name("main".to_owned())
		.site_pkg_dir(".".to_owned())
		.build();
	let app = Router::new()
		.route(
			"/main.js",
			routing::get(|| async {
				std::fs::read("main.js")
					.map(JavaScript)
					.map_err(|err| (StatusCode::INTERNAL_SERVER_ERROR, err.to_string()))
			}),
		)
		.route(
			"/main_bg.wasm",
			routing::get(|| async {
				std::fs::read("main_bg.wasm")
					.map(Wasm)
					.map_err(|err| (StatusCode::INTERNAL_SERVER_ERROR, err.to_string()))
			}),
		)
		.leptos_routes_with_context(
			&leptos_options,
			leptos_axum::generate_route_list(App),
			|| {},
			App,
		)
		.with_state(leptos_options);

	Server::bind(&"0.0.0.0:8080".parse().unwrap())
		.serve(app.into_make_service())
		.await
		.unwrap();
}
```
