### ISSUE TITLE
tracking and then updating a signal in on_cleanup causes Router to rerender

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#1882]
**Describe the bug**
When using a tracked signal in on_cleanup of a page component, and then updating it from within that component for example via `request_animation_frame` or `set_timeout` then once navigation switches to a different page, the Router renders the new page twice.

**Leptos Dependencies**
```toml
leptos = { version = "0.5.1", features = ["nightly"] }
leptos_meta = { version = "0.5.1", features = ["nightly"] }
leptos_actix = { version = "0.5.1", optional = true }
leptos_router = { version = "0.5.1", features = ["nightly"] }
```

**To Reproduce**
Use the code below, go to the HomePage (default), then click on "Random" to switch to the other page. In the console, there will be these log messages:
```
RandomPage
HomePage cleanup
RandomPage
```

```rs
use leptos::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    let ctx = create_rw_signal(());

    provide_context(ctx);

    view! {
        <Router>
            <main>
                <nav>
                    <a href="/">"Home"</a>
                    <a href="/random">"Random"</a>
                </nav>
                <Routes>
                    <Route path="" view=HomePage/>
                    <Route path="/random" view=RandomPage/>
                </Routes>
            </main>
        </Router>
    }
}

#[component]
pub fn RandomPage() -> impl IntoView {
    logging::log!("RandomPage");
    view! {
        <div>"RandomPage"</div>
    }
}

#[component]
pub fn HomePage() -> impl IntoView {
    let ctx = expect_context::<RwSignal<()>>();

    on_cleanup(move || {
        logging::log!("HomePage cleanup");
        ctx.track();

        request_animation_frame(move || {
            ctx.update(|_| {});
        });
    });

    ()
}
```

**Expected behavior**
Ideally, the code in `on_cleanup` should only be using untracked functions I guess, but this bug is very difficult to track down. I don't know why this tracking causes the Router to end up rerendering the page. It shouldn't, I think.
