### ISSUE TITLE
Router query parameter override hash part of the url

### ISSUE THREAD

**Issue by rambip** [leptos-rs/leptos#1902]
**Describe the bug**

When the page has a "hash url" part, `create_query_signal` will override this part, but that is not needed.

**Leptos Dependencies**

```toml
[dependencies]
wasm-bindgen="0.2.87"
leptos={version="0.5", features=["csr"]}
leptos_router = {version="0.5.1", features=["csr"]}
```

**To Reproduce**
```rust
use leptos::*;
use leptos_router::*;

fn app() -> impl IntoView {
    let navigate = move |url| {
        let nav = use_navigate();
        nav(url, Default::default());
    };

    let (_bar, set_bar) = create_query_signal("bar");

    view!{
        <Router>
            <button on:click=move |_| set_bar.set(Some("42".to_string()))
                >add query option 42
            </button>
            <button on:click=move |_| navigate("#foo")>
                navigate to specific hash url
            </button>
            <button on:click=move |_| navigate("/")>
                navigate to home
            </button>
        </Router>
    }
}

fn main(){
    mount_to_body(app);
}
```

Then, click on "navigate to specific hash url" and then "add query option 42"

**Expected behavior**
The url query should be added, but without overwriting the hash url
