### ISSUE TITLE
Resource::set() breaks Suspense if it tracks multiple resources.

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#1905]
**Describe the bug**
When tracking more than one resource within the body of a <Suspense> component, then updating the resources using the `Resource::set` function gives incorrect values for `SuspenseContext.pending_resources`, which causes the Suspense to stay forever in pending state.

**Leptos Dependencies**
currently using rev 17b33003517928a35fb50d74d56328cbf38dd7c2 (according to lockfile)
```toml
[patch.crates-io]
leptos_reactive = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos_actix = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos_hot_reload = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos_macro = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos_integration_utils = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
```

**To Reproduce**
```rs
#[component]
pub fn MyTest() -> impl IntoView {
    let r1 = create_local_resource(move || {}, move |_| future::pending::<()>());
    let r2 = create_local_resource(move || {}, move |_| future::pending::<()>());

    let click = move |_| {
        r1.set(());
        r2.set(());
        logging::log!("Setting resources");
    };

    view! {
        <button on:click=click>"Click"</button>
        <Suspense fallback=move || view! { <p>"Loading..."</p> }>
            {move || {
                r1.track();
                r2.track();
                view! {
                    <div>"My Test"</div>
                }
            }}
        </Suspense>
    }
}
```

Clicking the button does not cause the Suspense to resolve. In fact, when monitoring the Suspense context from within the suspense, I notice that the number of pending_resources goes down to `1` and then stays there.

**Expected behavior**
Expected the Suspense to move into its resolved state once both resources have been completed.

**Additional context**
- The issue does not arise at the time the Resource completes automatically (i.e. with a `gloo_timers::future::sleep(Duration::from_secs(10)).await;` instead of the ever-pending future). However, even with such a future, calling `set` on the Resource still causes the same errorneous behaviour.
- When only calling set on a single resource (either `r1` or `r2` but not both), calling `set()` multiple times on the same resource actually causes the `pending_resources` value to increase (despite no additional resources being added). The first `set` keeps the value the same, but subsequent calls increase the value. Running `refetch` on the resource slightly alters the behavior as it will cause even the first `set` to already increment the value.

The use-case is for a cache similar to `leptos_query`, where resources can be `set` when data arrives in the cache from various sources.
