### ISSUE TITLE
Anchor Jump Links do not work when the URL already contains the hash

### ISSUE THREAD

**Issue by lukexor** [leptos-rs/leptos#1907]
**Describe the bug**

The following snippet of HTML has an anchor link to a title further down the page. Clicking it once (or hard refreshing the page with the hash) works as expected. However, scrolling back up and clicking the link a second time or doing a soft refresh does not scroll to the anchor when using SSR with cargo-leptos and leptos_router.

```html
        <a href="#title">"Go to title"</a>
        <div style="height: 1000px"></div>
        <h1 id="title" style="height: 1000px">Title</h1>
```

This functionality works as expected using plain HTML and using Client-side rendering with `trunk`.

**Leptos Dependencies**

```toml
[dependencies]
axum = { version = "0.6.4", optional = true }
console_error_panic_hook = "0.1"
console_log = "1"
cfg-if = "1"
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
log = "0.4"
simple_logger = "4"
tokio = { version = "1.25.0", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.4", features = ["fs"], optional = true }
wasm-bindgen = "=0.2.87"
thiserror = "1.0.38"
tracing = { version = "0.1.37", optional = true }
http = "0.2.8"
```

**To Reproduce**
1. Start a new project from a template: `cargo leptos new --git leptos-rs/start-axum`
2. Set the above HTML to the `Homepage` component
3. `cargo leptos watch` or `cargo leptos serve`
4. Click the "Go to title" link
5. Scroll up and click the link again

**Expected behavior**

Expected behavior is that each time the link is clicked, the page is scrolled to the Title anchor

**Additional context**

I suspect the issue is in the leptos router, since the URL doesn't change, the default event handler isn't getting fired.
