### ISSUE TITLE
Hydration error with Suspense > Outlet and other component outside of <Routes><Routes/>

### ISSUE THREAD

**Issue by winteler** [leptos-rs/leptos#1909]
Hi!

I think I found another hydration bug a bit similar to https://github.com/leptos-rs/leptos/issues/1863. This time the hydration error appears when a Suspense is outside `<Routes><Routes/>`. 

**Leptos Dependencies**

Originally discovered with
```toml
leptos = { git = "https://github.com/leptos-rs/leptos.git", rev = "a3af4eb8fe09af1d7d538a660094940a17ff2285", features = ["nightly"] }
leptos_axum = { git = "https://github.com/leptos-rs/leptos.git", rev = "a3af4eb8fe09af1d7d538a660094940a17ff2285", optional = true }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git", rev = "a3af4eb8fe09af1d7d538a660094940a17ff2285", features = ["nightly"] }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", rev = "a3af4eb8fe09af1d7d538a660094940a17ff2285", features = ["nightly"] }
```
And then reproduced with ```rev = "0d6ddfb71e37a08548d938972142dbc39a0632f8""```. Interestingly it doesn't occur with ```version = "0.5.1"```.

**To Reproduce**
```
use leptos::*;
use leptos_router::*;

#[server]
pub async fn get_user() -> Result<(), ServerFnError> {
    Ok(())
}

#[server]
pub async fn data() -> Result<(), ServerFnError> {
    Ok(())
}

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <div>
                <main>
                    <div>
                        <Routes>
                            <Route path="" view=LoginGuard>
                                <Route path="" view=Child/>
                            </Route>
                        </Routes>
                    </div>
                    //<div>
                        <Drawer/>
                    //</div>
                    <div>
                        <div>
                            <button on:click=move |_| leptos::logging::log!("Did I hydrate?")>"Click"</button>
                        </div>
                    </div>
                </main>
            </div>
        </Router>
    }
}

#[component]
pub fn Drawer() -> impl IntoView {
    let nested_data = Resource::once(data);

    view! {
        <label>"Label"</label>
        <Suspense>
            <pre>{
                move || {
                    format!("{:?}", nested_data.get())
                }
            }</pre>
        </Suspense>
    }
}

#[component]
fn LoginGuard() -> impl IntoView {
    let guard_data = Resource::once(get_user);
    view! {
        <Suspense>
            {move || guard_data.and_then(|_| view! { <Outlet/> })}
        </Suspense>
    }
}

#[component]
pub fn Child() -> impl IntoView {
    //let nested_data = Resource::once(data);
    view! {
        <div>
            "Test"
        </div>
        /*<Suspense>
            <pre>{
                move || {
                    format!("{:?}", nested_data.get())
                }
            }</pre>
        </Suspense>*/
    }
}
```

**Additional context**
I've been trying to identify exactly the setup causing the issue but I'm still not completely sure. In the example from the reproduce section, it looks like uncommenting the `<div></div>` around the `<Drawer/>` component removed the hydration error, but then uncommenting the `<Suspense>` in `<Child/>` resulted again in an hydration error. This might be two different issues tho.
