### ISSUE TITLE
No closing </head> Tag

### ISSUE THREAD

**Issue by rconnol** [leptos-rs/leptos#1930]
**Describe the bug**
The leptos generated html and css is not generating a closing tag for the head element.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

ahash is failing to build on the nightly toolchain for me, so I am using stable Rust for this MRE.

For example:
```toml
[dependencies]
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true, features = ["macros"] }
console_error_panic_hook = "0.1"
cfg-if = "1"
http = { version = "0.2", optional = true }
leptos = { version = "0.5" }
leptos_meta = { version = "0.5"}
leptos_actix = { version = "0.5", optional = true }
leptos_router = { version = "0.5" }
wasm-bindgen = "=0.2.87"
```

rust-toolchain.toml
```toml
[toolchain]
channel = "1.73.0"
```

**To Reproduce**
1. Follow the getting started guide for cargo leptos actix: https://leptos-rs.github.io/leptos/ssr/21_cargo_leptos.html
2. go to localhost:3000
3. inspect source
4. search the page for </head>

**Expected behavior**
I expect the <head> tag to have a corresponding </head> tag on the generated app

**Screenshots**
![image](https://github.com/leptos-rs/leptos/assets/12263637/16a4dd6d-b472-4eec-965c-6d7aa2bfe6bf)

**Additional context**
