### ISSUE TITLE
Attribute spreading does not work with self closing elements in `view!` macro

### ISSUE THREAD

**Issue by tqwewe** [leptos-rs/leptos#1934]
**Describe the bug**
Spreading attributes on a self closing tag (such as img or input) doesn't work in the `view!` macro.

For it to fail, the following must be true:
- Its a self closing tag
- It has normal attributes before the attribute spread
- The attribute spread must be after all the other attributes

Of course this means a simple work around is to put your attribute spread before other attributes.

For example, this fails:
```rust
view! {
    <img src=img_src {..attrs} />
}
```
However, this works:
```rust
view! {
    <img {..attrs} src=img_src />
}
```
Interestingly too, if `src` is a literal string instead of an ident, then it works:
```rust
view! {
    <img src="..." {..attrs} />
}
```

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.5.1", features = ["nightly"] }
leptos_axum = { version = "0.5.1" }
leptos_meta = { version = "0.5.1", features = ["nightly"] }
leptos_router = { version = "0.5.1", features = ["nightly"] }
leptos_dom = { version = "0.5.1", features = ["nightly"] }
```

**To Reproduce**
Create the following component:
```rust
use leptos::*;

#[component]
pub fn Img(
    #[prop(attrs)] attrs: Vec<(&'static str, Attribute)>,
) -> impl IntoView {
    let img_url = "...";

    view! { <img src=img_url {..attrs}/> }
}
```

**Expected behavior**
It should compile fine.

**Screenshots**
-

**Additional context**
-
