### ISSUE TITLE
`Trigger` doesn't work when provided as a context in a `Transition`

### ISSUE THREAD

**Issue by tqwewe** [leptos-rs/leptos#1948]
**Describe the bug**
Using a trigger provided as a context and used in a child which is nested in a Transition does not work.

**Leptos Dependencies**

```toml
leptos = { version = "0.5.1", features = ["nightly"] }
leptos_meta = { version = "0.5.1", features = ["nightly"] }
leptos_router = { version = "0.5.1", features = ["nightly"] }
leptos_dom = { version = "0.5.1", features = ["nightly"] }
```

**To Reproduce**

```rust
#[component]
fn App() -> impl IntoView {
    let trigger = create_trigger();
    provide_context(trigger);

    create_effect(move |_| {
        set_interval(move || trigger.notify(), Duration::from_millis(500));
    });

    // If this line is placed above the create_trigger then the bug disappears.
    let stuff = create_resource(|| (), |_| async move { do_something().await });

    view! {
        <Transition>
            {move || {
                stuff
                    .get()
                    .map(move |_| {
                        view! {<CountDisplay/> }
                    })
            }}

        </Transition>
    }
}

#[component]
fn CountDisplay() -> impl IntoView {
    let (count, set_count) = create_signal(0);

    let trigger: Trigger = expect_context();
    // Increment the count when the trigger triggers
    let _ = watch(
        move || trigger.track(),
        move |_, _, _| {
            set_count.update(|count| *count += 1);
        },
        false,
    );

    view! { <span>{count}</span> }
}

async fn do_something() {
    // This timeout is needed, otherwise the bug disappears...
    // AND it needs to be more than the time set for the interval above (500ms)
    TimeoutFuture::new(600).await; 
}
```

In this example, the count should increment every 500ms.
However, with this specific code it doesn't work. But if you change either:
- Move the `create_trigger` below the `create_resource`
- Set the TimeoutFuture to below the interval
Then the bug disappears and the code works correctly.

**Expected behavior**
The code should work no matter if the Trigger or Resource is created first.
