### ISSUE TITLE
Multiple subsequent ErrorBoundaries fail to render

### ISSUE THREAD

**Issue by CircuitSacul** [leptos-rs/leptos#1987]
**Describe the bug**
If you have multiple ErrorBoundaries next to each other, and update one or more of them using a signal client-side, it fails to render the fallback (and the original content disappears).

My reproduction on codesandbox behaves differently, possibly due to lack of hydration/ssr. Regardless, it is still bugged: only one of the ErrorBoundaries shows the error, the first continues to show the ok content.

https://codesandbox.io/p/sandbox/1-basic-component-forked-zfd2pp

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
```

**To Reproduce**
https://codesandbox.io/p/sandbox/1-basic-component-forked-zfd2pp

**Expected behavior**
Both ErrorBoundaries show the error after update.

**Screenshots**
Only one, or neither, shows the error.

**Additional context**
I can confirm that both ErrorBoundaries are calling the fallback code, because logging occurs. It just won't render.
