### ISSUE TITLE
Server functions inconsistent with`rkyv` feature on `leptos` crate

### ISSUE THREAD

**Issue by thestarmaker** [leptos-rs/leptos#1989]
**Describe the bug**
Hello, this is borderline bug/feature request; raising as bug as behaviour is unexpected for the end user.

Currently `leptos` crate supports `rkyv` feature for serealisation/deserelisation, this enables `Suspense` to work with `rkyv` serialisation (or at least that used to be the case). The `leptos_macro` crate on the other hand does not support `rkyv` serialisation on server-side functions (only serde). 

Since `leptos_macro` is not explicitly added to project dependencies, it is natural for user to assume that the feature changing the serialisation method on `leptos` crate would get propagated to all transient logic. This is not the case as server-side functions only support serde.

**Leptos Dependencies**
```toml
leptos = { version = "0.5.1", features = ["nightly", "rkyv"] }
leptos_meta = { version = "0.5.1", features = ["nightly"] }
leptos_router = { version = "0.5.1", features = ["nightly"] }
leptos_axum = { version = "0.5.1" }

rkyv = "0.7.42"
```

**To Reproduce**
Setup a new project, set `rkyv` feature on `leptos`, attemopt creating a server-side function that would use `rkyv` serialised struct.

**Expected behavior**
It should compile and when invoked should use `rkyv` serialisation.
