### ISSUE TITLE
<Portal /> can cause hydration issues

### ISSUE THREAD

**Issue by CorvusPrudens** [leptos-rs/leptos#2010]
**Describe the bug**
If a `<Portal />` component is used with SSR and does not have any surrounding `<Suspense />`, `<Show />`, etc., hydration will fail on the portal.

**Leptos Dependencies**

```toml
leptos = { version = "0.5.2", features = ["nightly"] }
leptos_axum = { version = "0.5.2", optional = true }
leptos_meta = { version = "0.5.2", features = ["nightly"] }
leptos_router = { version = "0.5.2", features = ["nightly"] }
```

**To Reproduce**
Here's an example:

```rs
#[component]
fn HomePage() -> impl IntoView {
    let (show, set_show) = create_signal(false);
    create_effect(move |_| set_show(true));

    view! {
        <Show when=show>
            <Portal>
                <h1>"This mounts properly."</h1>
            </Portal>
        </Show>

        <Portal>
            <h1>"This does not mount."</h1>
        </Portal>
    }
}
```
![error_example](https://github.com/leptos-rs/leptos/assets/26205140/e2446a18-a895-4565-bc89-415c583e65e1)

[Here's a link to a repo where I set up this example for quick reference.](https://github.com/CorvusPrudens/leptos-portal-issue)

**Expected behavior**
While I don't have a deep understanding of the framework, I think the above should simply work in both cases. This is useful in certain situations where you want a portal to always be present, not just transient like a tooltip.
