### ISSUE TITLE
Major drop in performance due to component nesting

### ISSUE THREAD

**Issue by timfvb** [leptos-rs/leptos#2065]
**Describe the bug**
 The nesting of components results in a significant drop in performance. I noticed this for the first time in my project, which is quite large and therefore has many components. I reached in my project with a [wrk](https://github.com/wg/wrk) benchmark just 8req/sec.
After searching for the problem, I found that the nesting of components is very cpu intensive.

I have written an example below to roughly reproduce the problem. 
Below are also 2 [wrk](https://github.com/wg/wrk) benchmarks in which I have benchmarked once with these components and once without.

**Wrk Benchmarks**
_Without test components:_
Running 10s test @ http://localhost:3000
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.01ms   10.41ms  42.77ms   85.33%
    Req/Sec    15.36k     2.20k   20.93k    69.31%
  308753 requests in 10.10s, 5.29GB read
Requests/sec:  30570.08
Transfer/sec:    536.47MB

_With test components (example reproduction code below):_
Running 10s test @ http://localhost:3000
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.32ms   10.42ms  51.70ms   85.55%
    Req/Sec     6.00k     1.49k   10.59k    71.64%
  120073 requests in 10.10s, 2.45GB read
Requests/sec:  11888.37
Transfer/sec:    248.65MB

**System**
CPU: AMD Ryzen 5 2600X (12) @ 3.600GHz
RAM: 16GB DDR4

**Leptos Dependencies**
```toml
axum = { version = "0.6.4", optional = true }
console_error_panic_hook = "0.1"
console_log = "1"
cfg-if = "1"
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
log = "0.4"
simple_logger = "4"
tokio = { version = "1.25.0", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.4", features = ["fs"], optional = true }
wasm-bindgen = "=0.2.88"
thiserror = "1.0.38"
tracing = { version = "0.1.37", optional = true }
http = "0.2.8"
```

**To Reproduce**
My example reproduction code:
```rs
/// Renders the home page of your application.
#[component]
fn HomePage() -> impl IntoView {
    view! {
        <EntryComponent/>
        <EntryComponent/>
        <EntryComponent/>
        <EntryComponent/>
        <EntryComponent/>
        <EntryComponent/>
        <EntryComponent/>
        <EntryComponent/>
    }
}

#[component]
fn EntryComponent() -> impl IntoView {
    view! { <Component2/> }
}

#[component]
fn Component2() -> impl IntoView {
    view! { <Component3/> }
}

#[component]
fn Component3() -> impl IntoView {
    view! { <Component4/> }
}

#[component]
fn Component4() -> impl IntoView {
    view! { <Component5/> }
}

#[component]
fn Component5() -> impl IntoView {
    view! { <Component6/> }
}

#[component]
fn Component6() -> impl IntoView {
    view! { <Component7/> }
}

#[component]
fn Component7() -> impl IntoView {
    view! { <Component8/> }
}

#[component]
fn Component8() -> impl IntoView {
    view! { <Component9/> }
}

#[component]
fn Component9() -> impl IntoView {
    view! { <Component10/> }
}

#[component]
fn Component10() -> impl IntoView {
    view! { <Component11/> }
}

#[component]
fn Component11() -> impl IntoView {
    view! { <Component12/> }
}

#[component]
fn Component12() -> impl IntoView {
    view! { <Component13/> }
}

#[component]
fn Component13() -> impl IntoView {
    view! { <Component14/> }
}

#[component]
fn Component14() -> impl IntoView {
    view! { <Component15/> }
}

#[component]
fn Component15() -> impl IntoView {
    view! { <Component16/> }
}

#[component]
fn Component16() -> impl IntoView {
    view! { <Component17/> }
}

#[component]
fn Component17() -> impl IntoView {
    view! { <EndComponent/> }
}

#[component]
fn EndComponent() -> impl IntoView {
    view! { <p>Test</p> }
}
```

**Expected behavior**
 Only a minimal change in performance, as in the end the components should have no influence on the performance of the application.
