### ISSUE TITLE
BorrowMut error when using signal immutably in `<Show/>` and mutably in `on:click`.

### ISSUE THREAD

**Issue by adrianncovaci** [leptos-rs/leptos#2087]
**Describe the bug**
I'm not really sure if leptos should handle this or not, but Im trying to use a signal to both `<Show/> `and handle an `on:click` event and get a borrowmut error. I think it's because the effect in show gets an immutable reference while there's still a mutable one for the `on:click` handler.
**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.
```toml
[workspace.dependencies]
leptos = { version = "0.5", features = ["nightly"] }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5" }
```

**To Reproduce**
Run (or inspect) https://github.com/adrianncovaci/leptos_reproduce and click on one of the divs.

**Screenshots**
<img width="630" alt="image" src="https://github.com/leptos-rs/leptos/assets/26554899/4d2cf527-6b39-47c2-b362-83b7b6343792">
