### ISSUE TITLE
Javascript no longer loads after page routing

### ISSUE THREAD

**Issue by timfvb** [leptos-rs/leptos#2100]
**Describe the bug**
As soon as you switch to another page (page2), the javascript no longer loads when you go back to the original page (home).
Affected are normal routes (page2) and routes with a parameter (page2/:id). 

If you reload the page (home) the javascript works again.

An error appears in the console if you do this with a route that takes a parameter (page2/:id):
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Leptos Dependencies**
```toml
axum = { version = "0.6.4", optional = true }
console_error_panic_hook = "0.1"
console_log = "1"
cfg-if = "1"
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
log = "0.4"
simple_logger = "4"
tokio = { version = "1.25.0", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.4", features = ["fs"], optional = true }
wasm-bindgen = "=0.2.89"
thiserror = "1.0.38"
tracing = { version = "0.1.37", optional = true }
http = "0.2.8"
```

**To Reproduce**
Code to reproduce the behavior:

`app.rs`
```rs
use leptos::*;
use leptos_meta::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {
        <Stylesheet id="leptos" href="/pkg/js-load-wasm.css"/>

        <Router>
            <main>
                <Routes>
                    <Route path="" view=Home/>
                    <Route path="page2/:id" view=Page2/>
                </Routes>
            </main>
        </Router>
    }
}

#[component]
fn Home() -> impl IntoView {
    view! {
        <A href="/page2/test">"Go to Page 2"</A>

        <div id="mybox"></div>

        <script type="module" src="content.js"/>
    }
}

#[component]
fn Page2() -> impl IntoView {
    view! {
        <A href="/">"Back to Home"</A>
    }
}
```
`content.js`
```rs
import "https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/p5.min.js";
import "https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.topology.min.js";

VANTA.TOPOLOGY({
  el: "#mybox",
  mouseControls: true,
  touchControls: true,
  gyroControls: false,
  minHeight: 200.00,
  minWidth: 200.00,
  scale: 1.00,
  scaleMobile: 1.00,
  color: 0x9b1be5
})
```

**Expected behavior**
That even when changing pages the javascript is loaded correctly.
