### ISSUE TITLE
`mount_to_body` should accept `FnOnce` closures

### ISSUE THREAD

**Issue by NKID00** [leptos-rs/leptos#2115]
**Describe the bug**

Function `mount_to_body` in `leptos_dom` accepts `Fn` closures only, therefore it is not possible to pass a `FnOnce` closure to `mount_to_body`. However `mount_to` accepts `FnOnce` closures and `mount_to_body` does barely nothing more than calling `mount_to`. `mount_to_body` should be able to accept `FnOnce` closures without modification.

**Leptos Dependencies**

```toml
leptos = { version = "0.5.4", features = ["csr"] }
leptos_dom = { version = "0.5.4", features = ["csr"] }
```

**Additional context**

`mount_to_body`: https://github.com/leptos-rs/leptos/blob/v0.5.4/leptos_dom/src/lib.rs#L927

`mount_to`: https://github.com/leptos-rs/leptos/blob/v0.5.4/leptos_dom/src/lib.rs#L950
