### ISSUE TITLE
Transition fallback not shown

### ISSUE THREAD

**Issue by lukasschlueter** [leptos-rs/leptos#2123]
**Describe the bug**
I'm using ssr/hydrate. When using a `Route` to a `Transition`, the `fallback` is not shown. It is shown on a fresh page load. 
If I replace the `Transition` with a `Suspense`, it works in both cases.

**Leptos Dependencies**
```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_router = { version = "0.5", features = ["nightly"] }
```

**To Reproduce**
1. Clone https://github.com/lukasschlueter/leptos-transition-fallback-bug (based on https://github.com/leptos-rs/start-axum, relevant code in [src/app.rs](https://github.com/lukasschlueter/leptos-transition-fallback-bug/blob/1d637fdc942dedd3a452c9b39be1ae4383984c1c/src/app.rs))
2. Run `cargo leptos watch --release`
3. Go to `localhost:3000`
4. Click `Click here to load a buggy transition`
5. Wait 2s on a blank screen (this is where the bug happens - the fallback is not shown)
6. "Success!" appears
7. Reload the page
8. "Loading...!" is shown (fallback works on a fresh page load)
9. Replace `Transition` with `Suspense` (https://github.com/lukasschlueter/leptos-transition-fallback-bug/blob/1d637fdc942dedd3a452c9b39be1ae4383984c1c/src/app.rs#L31)
10. Repeat from Step 3 - fallback is shown in both cases

**Expected behavior**
The `Transition` fallback is shown instead of the blank screen in step 5

**Screenshots**
Can't take a video of my browser at the moment (linux wayland stuff)

**Additional context**
```bash
$ cargo --version             
cargo 1.76.0-nightly (1a2666ddd 2023-12-17)
$ rustc --version      
rustc 1.76.0-nightly (3f28fe133 2023-12-18)
```
