### ISSUE TITLE
Route `State` is being lost after Backward and/or Forward navigation

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#2164]
**Describe the bug**
`NavigateOptions` allows you to set a `state` for the current route. However, if the user navigates using the browsers forward and backward buttons this state is being lost. This is even true when just using JavaScript to navigate (i.e. completely avoiding the use_navigate/use_location). Just having the router on the page triggers this issue.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.5.4", features = ["nightly"] }
leptos_meta = { version = "0.5.4", features = ["nightly"] }
leptos_actix = { version = "0.5.4", optional = true }
leptos_router = { version = "0.5.4", features = ["nightly"] }
leptos_reactive = { version = "0.5.4", features = ["nightly"] }
```

**To Reproduce**
Go to a page with leptos router on it, then run the following javascript in the console. Make sure that the line with pushState moves to a *different* route that is still handled by the router.

```js
  async function sleep() {
      await new Promise(resolve => setTimeout(resolve, 100));
  }
  async function do_navigate() {
      await sleep();
      
      history.pushState(123, 'title', '/about');
      await sleep();
      
      console.log("State from JS (before):", history.state);
      await sleep();
      
      history.back();
      await sleep();
      
      history.forward();
      await sleep();
      
      console.log("State from JS:", history.state);
  }
  do_navigate();
```

For more indepth examples (WithRouter, WithRouterWithJS and NoRouterJS which has the correct behaviour), see this gist: https://gist.github.com/luxalpa/c498a64e72f64d8ad293d47f6b66d2bf

**Expected behavior**
The state that's associated with the route should still be available after navigating backwards and forwards (that's kinda the point).
