### ISSUE TITLE
Hydration bug when using an <html> tag

### ISSUE THREAD

**Issue by SGauvin** [leptos-rs/leptos#2192]
**Describe the bug**
When adding an `<html>` tag in a `view` macro, the following warning appears in the browser's console:
`component with id 0-0-0-1c not found, ignoring it for hydration`

**Leptos Dependencies**
```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
axum = { version = "0.6.4", optional = true }
```

**To Reproduce**
1. Create a new project with `cargo leptos new --git leptos-rs/start-axum`
2. Add an `<html>` tag around the router:
```rust
#[component]
pub fn App() -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context();

    view! {
        <html class="dark"> // <== NEW
            // injects a stylesheet into the document <head>
            // id=leptos means cargo-leptos will hot-reload this stylesheet
            <Stylesheet id="leptos" href="/pkg/leptos-bug.css"/>

            // sets the document title
            <Title text="Welcome to Leptos"/>

            // content for this welcome page
            <Router fallback=|| {
                let mut outside_errors = Errors::default();
                outside_errors.insert_with_default_key(AppError::NotFound);
                view! {
                    <ErrorTemplate outside_errors/>
                }
                .into_view()
            }>
                <main>
                    <Routes>
                        <Route path="" view=HomePage/>
                    </Routes>
                </main>
            </Router>
        </html> // <== NEW
    }
}
```
3. `cargo leptos serve`
4. Go to `localhost:3000`
5. Open the console
6. Observe the message: `component with id 0-0-0-1c not found, ignoring it for hydration`

**Expected behavior**
There should be no warnings.
