### ISSUE TITLE
Panic for nightly when using use_local_storage

### ISSUE THREAD

**Issue by glennpierce** [leptos-rs/leptos#2202]
This may be because of an unsupported branch 

In my toplevel App component I do

let (token, set_token, _) = use_local_storage::<String, StringCodec>("token");

When running the app with leptos watch I get

```
thread 'main' panicked at /home/glenn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.6/src/runtime.rs:1010:10:
tried to create a signal in a runtime that has been disposed: RuntimeDisposed(RuntimeId(4294967295v1))
```

For example:
```toml
leptos = { git = "https://github.com/dgsantana/leptos", branch="axum_7", features = ["nightly"] }
leptos_axum = { git = "https://github.com/dgsantana/leptos", branch="axum_7", optional = true }
leptos_meta = { git = "https://github.com/dgsantana/leptos", branch="axum_7", features = ["nightly"] }
leptos_router = { git = "https://github.com/dgsantana/leptos", branch="axum_7", features = ["nightly"] }
leptos-use = "0.9.0"
```
