### ISSUE TITLE
In the tailwind example, when running without leptos watch, the wasm isnt delivered to the browser 

### ISSUE THREAD

**Issue by Alt-iOS** [leptos-rs/leptos#2206]
**Describe the bug**
When trying the tailwind_axum example you cant use it without using `cargo leptos watch`

**Leptos Dependencies**
```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
```

**To Reproduce**
1. Clone the repo and go to the examples folder, to the tailwind_axum case.
2. Change this From ```None``` to  ```Some("Cargo.toml")``` in main.rs around line 27
```rust
    let conf = get_configuration(Some("Cargo.toml")).await.unwrap();
```
3.Change the folder of the site root and site pkg  (changing the site where the wasm-pack build outputs didnt seem to work, so I changed where leptos looks for it)
```toml
[package.metadata.leptos]
# The site root folder is where cargo-leptos generate all output. Use it in your server setup.
site-root = "pkg"

# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg
site-pkg-dir = "."
```
3. Attempt to run the example with this commands
```sh
  wasm-pack build --target=web --debug --no-default-features --features=hydrate
 cargo run --no-default-features --features=ssr
```

**Expected result**
This is for example the browser on the tailwind example
<img width="219" alt="Screenshot 2024-01-19 at 9 03 06 PM" src="https://github.com/leptos-rs/leptos/assets/80638470/47965c05-11f2-45d2-a3ca-b4b091718c0b">
Expected something like this , its the axum starter generated by the cli running the same way with commands separated and no cargo leptos watch, using the same config mentioned in the steps above which actually works
<img width="218" alt="Screenshot 2024-01-19 at 9 03 18 PM" src="https://github.com/leptos-rs/leptos/assets/80638470/0399d89c-579b-4f15-b41d-e506b0e87b9a">

if it helps here are the cargo.toml from the example:
https://pastebin.com/YuVjpniy?theme=dark
the one that I managed to get working:
https://pastebin.com/yaeMYkXG?theme=dark
