### ISSUE TITLE
source html in production

### ISSUE THREAD

**Issue by MrChaker** [leptos-rs/leptos#2220]
In the final html result ( checked using dev tools sources ) , Is there any way that I can make the content inside the body to be formatted instead of just being 1 line

For example:
```toml
leptos = { version = "0.4", features = ["nightly"] }
leptos_axum = { version = "0.4", optional = true }
leptos_meta = { version = "0.4", features = ["nightly"] }
leptos_router = { version = "0.4", features = ["nightly"] }
```
