### ISSUE TITLE
Panic from batched update to disposed runtime after action dispatch

### ISSUE THREAD

**Issue by alilee** [leptos-rs/leptos#2225]
**Describe the bug**
Panic during initial server-side rendering when dispatching to server action. 

**Leptos Dependencies**
on tag `v0.6.0-beta`:
```toml
leptos = { path = "../../leptos", features = ["nightly"] }
leptos_axum = { path = "../../integrations/axum", optional = true }
leptos_meta = { path = "../../meta", features = ["nightly"] }
leptos_router = { path = "../../router", features = ["nightly"] }
server_fn = { path = "../../server_fn", features = ["serde-lite", "rkyv", "multipart" ]}
```

**To Reproduce**
<img width="936" alt="Screenshot 2024-01-25 at 11 55 30 am" src="https://github.com/leptos-rs/leptos/assets/16739/6391d5cb-a710-413e-942e-938a2ae7a746">

Note error:
```
thread '<unnamed>' panicked at /.../leptos/leptos_reactive/src/runtime.rs:1407:6:
tried to run a batched update in a runtime that has been disposed: RuntimeDisposed(RuntimeId(1v1))
```

**Expected behavior**
The panic doesn't seem to stop the `value()` call from resolving on the next (client-side) round-trip which is good. Ideally I'd like it to resolve on the first call though. Also would like to understand if the panic is indicative of undefined behaviour or something we'd fix.  Thanks!
