### ISSUE TITLE
Derived signal is not updated.

### ISSUE THREAD

**Issue by gzp79** [leptos-rs/leptos#2255]
**Describe the bug**
If I have a signal that updates its own dependency, the derived signal is not evaluated again.
It could be a tech limitation to avoid infinite loops, but in this case, how can I work around this issue. Please see the sample source code.

**Leptos Dependencies**

```toml
log = "0.4"
console_log = "1.0"
console_error_panic_hook = "0.1"
thiserror = "1.0"

rand = "0.8"
gloo-timers = { version = "0.3", features = ["futures"] }
reqwasm = "0.5"
serde = { version = "1", features = ["derive"] }

js-sys = "0.3"
leptos = { version = "0.6", features = ["csr"] }
leptos_meta = { version = "0.6", features = ["csr"] }
leptos_router = { version = "0.6", features = ["csr"] }
```

**To Reproduce**

This test component should render ErrorPage, instead of Loading. Note, the app_error is rendered/updated correctly, but not the other part.
```

static mut i: usize = 0;

#[component(transparent)]
pub fn TestComp() -> impl IntoView {
    let app_error = create_rw_signal(None::<String>);
    let resource = create_local_resource(
        || (),
        move |_| async move { Err::<Option<String>, String>("Err".into()) },
    );

    let user = move || {
        log::info!("error_bound");
        match resource.get() {
            None => {
                log::info!("user returns None");
                None
            }
            Some(Ok(value)) => {
                log::info!("user returns value");
                Some(value)
            }
            Some(Err(err)) => {
                log::info!("user returns None for error, updates app_error");
                app_error.set(Some(err));
                None
            }
        }
    };
    
    view! {
        {move || {
            let a = unsafe{ i += 1; i };
            log::info!("render err vvvvvvv {}", a);
            let r = format!("err: [{:?}]", app_error.get());
            log::info!("render err ^^^^^^^ {}", a);
            r
        }}

        {move || {
            let a = unsafe{ i += 1; i };
            log::info!("render page vvvvvvv {}", a);
            let view = if app_error.get().is_some() {
                "ErrorPage".into_view()
            }
            else {
                match user() {
                    None => {
                        "Loading".into_view()
                    }
                    Some(None) => {
                        "No User".into_view()
                    }
                    Some(Some(_)) => {
                        "Has User".into_view()
                    }
                }
            };
            log::info!("render page ^^^^^^ {}", a);
            view
        }}
    }

}
```
