### ISSUE TITLE
create_resource inside Suspense causes server panic

### ISSUE THREAD

**Issue by haslersn** [leptos-rs/leptos#2308]
**Describe the bug**

The following code causes a server panic when visiting the web page.

```rust
use leptos::*;
use leptos_meta::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {
        <Router>
            <Routes>
                <Route path="" view=Page ssr=SsrMode::PartiallyBlocked/>
            </Routes>
        </Router>
    }
}

#[component]
fn Page() -> impl IntoView {
    view! {
        <Suspense fallback=|| "Loading ...">
            {
                let resource = create_blocking_resource(
                    || (),
                    |_| async { "Hello, World!".to_string() },
                );
                move || resource.get().unwrap_or_default()
            }
        </Suspense>
    }
}
```

**Leptos Dependencies**

```toml
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
```

This seems to have to do with the fact that the resource is created within the `<Suspense>`. When moving the resource creation to the beginning of `fn Page()`, the bug is not triggered.

**Expected behavior**

Ideally the code should behave as if the resource was created outside of the Suspense.
