### ISSUE TITLE
Server action's value is None after calling the action with JS/WASM disabled

### ISSUE THREAD

**Issue by haslersn** [leptos-rs/leptos#2321]
**Describe the bug**

The following page allows you to enter some text and submit it. The text should then appear under the form. However, with JS/WASM disabled, it does not appear, because the page gets rendered on the server where `action.value().get()` is `None`.

```rust
use leptos::*;
use leptos_meta::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    let action = create_server_action::<Identity>();
    let value = action.value();
    view! {
        <ActionForm action>
            <input type="text" name="x"/>
            <button type="submit">Submit</button>
        </ActionForm>
        {move || value.get()}
    }
}

#[server(Identity)]
async fn identity(x: String) -> Result<String, ServerFnError> {
    Ok(x)
}
```

**Leptos Dependencies**

```toml
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
```

**Expected behavior**

See bug description above.
