### ISSUE TITLE
relocation of nestedly imported js in wasm_bindgen

### ISSUE THREAD

**Issue by qidian99** [leptos-rs/leptos#2347]
**Describe the bug**
I defined the extern js fn as below:

```rust
#[wasm_bindgen(module = "/public/highlight.js")]
extern "C" {
    #[wasm_bindgen(js_namespace = default)]
    fn highlightAll();

```

inside /public/highlight.js, I did the following:
```js

import json from './languages/json.js';
highlight.registerLanguage("json", json);

// returns a new instance of the highlighter to be used for extensions
// check https://github.com/wooorm/lowlight/issues/47
highlight.newInstance = () => HLJS({});


export { highlight as default };
```

the dev environment worked just fine, but when I bundled for release, the ./languages/json.js is not relocated, e.g., into `dist/snippets/xxxxxx/languages/json.js`, so I have to manually copy the resource like
![image](https://github.com/leptos-rs/leptos/assets/20527912/902b0d48-6d1a-47f9-a03b-9301c197e6f2)

**Leptos Dependencies**

```toml
leptos = { version = "0.6", features = ["csr", "nightly"] }
leptos_meta = { version = "0.6", features = ["csr", "nightly"] }
leptos_router = { version = "0.6", features = ["csr", "nightly"] }
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1"
serde_json = "1.0.114"
serde = "1.0.197"

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
