### ISSUE TITLE
Multiple query_signals cancel out each other's writes

### ISSUE THREAD

**Issue by purung** [leptos-rs/leptos#2369]
**Describe the bug**
When updating more than one query_signal in the same closure, only the last write has an effect. 

**Leptos Dependencies**

```toml
leptos = { version = "0.6", features = ["csr", "nightly"] }
leptos_meta = { version = "0.6", features = ["csr", "nightly"] }
leptos_router = { version = "0.6", features = ["csr", "nightly"] }
```

**To Reproduce**
1. Create two `query_signal`s
2. Trigger a closure that updates both signals
3. Notice that only the last write has had an effect on the url

**Expected behavior**
Writes to each `query_signal` has an immediate effect.

**Additional context**
Additionally, it is clear that writes to a `query_signal` do not take effect until after the closure has run. 

**Minimal example**
```rust
#[component]
pub fn TestQuery() -> impl IntoView {
    let (r_from, w_from) = create_query_signal::<String>("from");
    let (r_to, w_to) = create_query_signal::<String>("to");
    let switch = move |_| {
        log!("Before from: {:?}", r_from());
        log!("Before to: {:?}", r_to());
        w_from(r_to());
        w_to(None);
        log!("After from: {:?}", r_from());
        log!("After to: {:?}", r_to());
    };
    view! {
        <div class="flex flex-col gap-4 p-8">
            <div>Current from: {r_from}</div>
            <div>Current to: {r_to}</div>
            <button type="button" on:click=switch class="btn">
                Switch
            </button>
        </div>
    }
}
```

Output after first click: 

```
Before from: Some("Original from")
Before to: Some("Original to")
After from: Some("Original from")
After to: Some("Original to")
```

Output after second click: 

```
Before from: Some("Original from")
Before to: None
After from: Some("Original from")
After to: None
```

This should support the idea that 1) The last write "wins" and 2) Writes do not take immediate effect.
