### ISSUE TITLE
New bug in 0.6.6: `ActionForm` with `redirect` strips query string

### ISSUE THREAD

**Issue by jollygreenlaser** [leptos-rs/leptos#2374]
[Discord thread](https://discord.com/channels/1031524867910148188/1211769737281929236/1211769737281929236)

**Describe the bug**
In 0.6.5 and earlier, using `leptos_axum::redirect` with an `ActionForm` would redirect to the path specified exactly as written. 

In 0.6.6 it started stripping out the query string. Everything including and after a `?` in the path is gone. 

**Leptos Dependencies**

```toml
leptos = { version = "0.6.6", features = ["nightly"] }
leptos_meta = { version = "0.6.6", features = ["nightly"] }
leptos_router = { version = "0.6.6", features = ["nightly"] }
leptos-use = { version = "0.10.2", features = ["serde"] }
leptos_axum = { version = "0.6.6", optional = true }
axum = { version = "0.7.4", optional = true }
tokio = { version = "1.36.0", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
axum-extra = { version = "0.9.2", optional = true, features = ["cookie"] }
```
