### ISSUE TITLE
Events not firing in Safari

### ISSUE THREAD

**Issue by garvanwalshe** [leptos-rs/leptos#2400]
**Describe the bug**
`on:change` and `on:input`Events don't fire on `<input> element in Safari (but they do in Chrome). I don't have Firefox installed so wasn't able to test that.

The simplest example of the bug uses the example code from the book (but it also happened with some of my own code)

**Leptos Dependencies**

```toml
axum = { version = "0.7", optional = true }
console_error_panic_hook = "0.1"
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
wasm-bindgen = "^0.2.89"
thiserror = "1"
tracing = { version = "0.1", optional = true }
http = "1"

```

**To Reproduce**
Add an event handler to an input event to update a signal.  I even tried the basic example from the book, as well as several of my own.
The simplest example is  a direct copy from the book

```
pub fn InputFromBook() -> impl IntoView {
    let (name, set_name) = create_signal("Controlled".to_string());

    view! {
        <input type="text"
            on:input=move |ev| {
                // event_target_value is a Leptos helper function
                // it functions the same way as event.target.value
                // in JavaScript, but smooths out some of the typecasting
                // necessary to make this work in Rust
                set_name(event_target_value(&ev));
            }

            // the `prop:` syntax lets you update a DOM property,
            // rather than an attribute.
            prop:value=name
        />
        <p>"Name is: " {name}</p>
    }
}
```

**Expected behavior**
It should update the  name to reflect what has been typed in the input.  It only does so in Chrome, but not Safari.
