### ISSUE TITLE
`warning: empty doc comment` on latest nightly clippy

### ISSUE THREAD

**Issue by rupansh-gob** [leptos-rs/leptos#2406]
**Describe the bug**
Running `cargo clippy --no-deps` shows this warning wherever I am using the `#[component]` macro
This issue is reproducible on the [start](https://github.com/leptos-rs/start) template

**Leptos Dependencies**

```toml
leptos = { version = "0.6", features = ["nightly"] }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_actix = { version = "0.6", optional = true }
leptos_router = { version = "0.6", features = ["nightly"] }

```

**To Reproduce**
1. `cargo leptos new --git "https://github.com/leptos-rs/start"`
2. navigate to the newly created project
3.  `cargo clippy --no-deps --all-features`

**Expected behavior**
clippy warnings should not originate from the `#[component]` macro
