### ISSUE TITLE
ErrorBoundaries as child of Suspense creates signal warnings when used outside of SSR?

### ISSUE THREAD

**Issue by sjud** [leptos-rs/leptos#2408]
When you have code of this pattern

```rust
<Suspense fallback=||view!{Loading Login Details}>
        <ErrorBoundary fallback=|errors|format!("ERRORS: {:?}",errors.get_untracked()).into_view()>
      ...
      </ErrorBoundary>
</Suspense>
  ```

you get this warning

[Signal::update] At Location { file: "/Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.6.9/src/components/errors.rs", line: 110, col: 40 }, you’re trying to update a Signal<leptos_dom::components::errors::Errors> (defined at /Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.6.9/src/error_boundary.rs:68:40) that has already been disposed of. This is probably a logic error in a component that creates and disposes of scopes. If it does not cause any issues, it is safe to ignore this warning, which occurs only in debug mode. [user_app.js:774:9](http://127.0.0.1:3000/pkg/user_app.js)
Attempted to update a signal after it was disposed.
signal created here: /Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.6.9/src/error_boundary.rs:68:40
warning happened here: /Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.6.9/src/components/errors.rs:110:40

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.6.9", features = ["nightly"] }
leptos_axum = { version = "0.6.9", optional = true }
leptos_meta = { version = "0.6.9", features = ["nightly"] }
leptos_router = { version = "0.6.9", features = ["nightly"] }
```

**To Reproduce**
Have two pages, one link to the second.
On the second page write the above code (possibly include resource?)
Load first page, click link to go to second page. Check console, see warnings.

**Expected behavior**
No warnings

**Additional context**
I can upload minimum reproducible if requested.
Thank you.
