### ISSUE TITLE
Hard to Debug NodeRef Warning

### ISSUE THREAD

**Issue by soundprojects** [leptos-rs/leptos#2414]
**Describe the bug**
When getting the warning:
`[Warning] You are setting a NodeRef that has already been filled. It’s possible this is intentional, but it’s also possible that you’re accidentally using the same NodeRef for multiple _ref attributes.`

There is no stack trace or way to debug where this warning originates, which NodeRef has already been filled and where to look for it

**Leptos Dependencies**

```toml
leptos = { version = "0.6.9", features = ["csr"] }
leptos_meta = { version = "0.6.9", features = ["csr"] }
leptos_router = { version = "0.6.9", features = ["csr"] }
```

**To Reproduce**
1. That's the issue, I don't know how to reproduce this

**Expected behavior**
A stack trace or more information of any kind would really help 

**Screenshots**

**Additional context**
