### ISSUE TITLE
Environment variables do not overwrite Config.toml options

### ISSUE THREAD

**Issue by GrumiumXD** [leptos-rs/leptos#2429]
**Describe the bug**

When calling `get_configuration()` with `None`, environment variables like `LEPTOS_SITE_ADDR` are used correctly, but when the method is called with `Some("Cargo.toml")`, the environment variable gets ignored.

**Leptos Dependencies**

I am encountering this with the axum starter and leptos `0.6.9`.

```toml
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
```

**To Reproduce**

1. Create a new leptos project using the axum starter.
2. Run `cargo leptos build`.
3. Set the environment variable `LEPTOS_SITE_ADDR` to `0.0.0.0:1234`.
4. Run `target/debug/<project name>`.
5. You should see "listening on http://0.0.0.0:1234".
6. Edit the `site-addr` option in the `Cargo.toml` to something non default (e.g. `site-addr = "127.0.0.1:3001"`).
7. Edit the `main.rs` file and change `get_configuration(None)` to `get_configuration(Some("Cargo.toml"))`.
8. Rebuild and launch the server again (still with the environment variable set).
9. Now it shows "listening on http://127.0.0.1:3001"

**Expected behavior**

According to the documentation, configuration via environment variables should always take precedence.
