### ISSUE TITLE
HTML is rendering url encoding escapes on the server and not correcting it until it reaches the browser

### ISSUE THREAD

**Issue by SleeplessOne1917** [leptos-rs/leptos#2463]
**Describe the bug**
When using SSR to render a page with escaped text (e.g. "&#x27;" for "'"), it gets returned to the browser displaying the literal escapes instead of the characters they represent.

**Leptos Dependencies**

```toml
leptos = { version = "0", features = ["nightly"] }
leptos_meta = { version = "0", features = ["nightly"] }
leptos_router = { version = "0", features = ["nightly"] }
leptos_i18n = "0"
leptos_actix = { version = "0", optional = true }
leptos_query = "0.5"
```

**To Reproduce**
1. Create project that uses SSR to return a page
2. Include characters that will need to be escaped for HTML in your markup
3. Run `cargo leptos watch`
4. Go to page

**Expected behavior**
The HTML gets sent to the browser with escapes displaying as the characters they represent instead of literally.

**Screenshots**
![Issue video](https://github.com/leptos-rs/leptos/assets/28871516/f670e1c5-f779-4e08-a437-37ab186f4358)

**Additional context**
Some style related things also change between page load and hydration (notice the sidebar on the right in the video shifts leftward at the same time the escaped text goes back to normal).
