### ISSUE TITLE
Failure to Version Examples

### ISSUE THREAD

**Issue by owlwres** [leptos-rs/leptos#2475]
I will not follow the template because this is such a stupid problem that I cannot understand why you have robbed me of my time.

The examples contain a file:

```toml
[toolchain]
channel = "nightly-2024-01-29"
```

That is not even compatible with the source.
