### ISSUE TITLE
Reading a resource in an effect incorrectly(?) results in a warning about hydration issues

### ISSUE THREAD

**Issue by Silvea12** [leptos-rs/leptos#2480]
**Describe the bug**

When reading a resource in a hydrated context, usually via an effect, you get a hydration warning.

<details><summary>Warning text</summary>

At src/app.rs:48:39, you are reading a resource in `hydrate` mode outside a <Suspense/> or <Transition/>. This can cause hydration mismatch errors and loses out on a significant performance optimization. To fix this issue, you can either: 
1. Wrap the place where you read the resource in a <Suspense/> or <Transition/> component, or 
2. Switch to using create_local_resource(), which will wait to load the resource until the app is hydrated on the client side. (This will have worse performance in most cases.) [leptos-fullstack-test.js:875:9](http://127.0.0.1:3000/pkg/leptos-fullstack-test.js)
</details>

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
```

**To Reproduce**
Create a server fn:
```rs
#[server]
async fn get_info() -> Result<String, ServerFnError> {
    Ok("Hello, world!".to_string())
}
```
Put this in a component:
```rs
let e = create_resource(|| (), |_| get_info());
create_effect(move |_| log!("{:?}", e.get()));
```

The Warning appears on hydration

**Expected behavior**
No warning should appear
