### ISSUE TITLE
Variably mounted children stop responding to signals on second mount

### ISSUE THREAD

**Issue by zakstucke** [leptos-rs/leptos#2488]
**Describe the bug**
Continuation of #2482, but sort of different so opening new, turns out the solution provided is still buggy. If children are unmounted, any reactive blocks stop updating on remount. 

https://github.com/leptos-rs/leptos/assets/44890343/4e40d122-b34f-4062-9762-107e2c9cf748

**Leptos Dependencies**

For example:
```toml
leptos = { version = "0.6.10" }
leptos_meta = { version = "0.6.10", features = [] }
leptos_router = { version = "0.6.10", features = [] }
leptos_axum = { version = "0.6.10", optional = true }
gloo-timers = { version = "0.3.0", features = ["futures"] }
once_cell = { version = "1.19" }
```

**To Reproduce**
- Mount `<Parent />`
- Click the toggle button to mount the children, you will see the counter increasing every 100ms
- Unmount then remount (click click)
- The counter will no longer update

```rust
use leptos::*;

#[component]
pub fn Parent() -> impl IntoView {
    let counter = create_rw_signal(0);
    create_effect(move |_| {
        spawn_local(async move {
            loop {
                gloo_timers::future::TimeoutFuture::new(100).await;
                counter.update(|v| *v += 1);
                tracing::info!("COUNTING");
            }
        })
    });

    view! {
        <Child>
            <div>CHILDREN</div>
            <div>{move || format!("Counter: {}", counter.get())}</div>
        </Child>
    }
}

#[component]
pub fn Child(children: Children) -> impl IntoView {
    let show = create_rw_signal(false);
    // Used your implementation, but my store_value_lazy() has same problem.
    let children = store_value(once_cell::unsync::Lazy::new(|| children()));
    view! {
        <div>
            <button on:click=move |_| {
                show.update(|v| *v = !*v);
            }>"Toggle children"</button>
            <div>{move || format!("Children shown: {}", show.get())}</div>
            {move || {
                show.get()
                    .then(move || {
                        view! { <div>{children.with_value(|value| (*value).clone())}</div> }
                    })
            }}

        </div>
    }
}

```

**Expected behavior**
Children shouldn't lose reactivity after the first mount/unmount.

Completely appreciate and excited for the work being done for 0.7, if this is only going to be properly fixed then, any ideas how to get something working for now?
