### ISSUE TITLE
build breaks after cargo-leptos version upgrade

### ISSUE THREAD

**Issue by komal-rs** [leptos-rs/leptos#2495]
**Describe the bug**
`cargo leptos` watch/serve/build breaks after bumping version to cargo-leptos 0.2.17 
Error:
```bash
Error: at `/Users/runner/work/cargo-leptos/cargo-leptos/src/lib.rs:44:76`

Caused by:
    0: at `src/config/mod.rs:59:84`
    1: invalid type: string "", expected a sequence
```

Works with 0.2.16 (`cargo binstall --no-confirm cargo-leptos --version 0.2.16`)

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

```toml
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
```

**To Reproduce**
1. Go to https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr
2. `cargo binstall --no-confirm cargo-leptos`
3. cargo leptos watch

**Expected behavior**

The build to run normally

**Screenshots**
<img width="1227" alt="Screenshot 2024-04-03 at 10 37 38 AM" src="https://github.com/leptos-rs/leptos/assets/157946119/d28d982b-7016-4a42-bb83-8591567628d1">

**Additional context**
