### ISSUE TITLE
Suspense and ErrorBoundary Doesn't render Ok() case if initial render is Err() until transitioning from Err -> Ok -> Err -> Ok

### ISSUE THREAD

**Issue by zoomiti** [leptos-rs/leptos#2508]
**Describe the bug**
Basically if an initial page render renders a suspense with an err, the error boundary fallback is rendered. However if through signals the resource that is suspended succeeds on a refetch the success case is not rendered. This is fixed if one more transition to err and then back to ok is performed. This might make more sense by just following the reproduction instructions.

**Leptos Dependencies**
```toml
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
```

**To Reproduce**
Using the [fallible resource branch of my min repro repo](https://github.com/zoomiti/min-repro/tree/fallible_resource)
1. Navigate to the page with query id=6,
2. Input 4 into the text box that will update the query signal and refetch the resource
3. Nothing will be rendered at first
4. Input 6 to render the Error case again
5. Input 4 and the Ok case will finally be rendered

**Expected behavior**
If an initial page load renders the fallback of an error boundary, if a signal refetches the resources into an ok, the ok branch should be rendered immediately.

**Screenshots**
N/A hopefully but happy to provide if needed

**Additional context**
This uses a server fn as the resource fetcher, to mirror my actual use case. However I can reproduce the bug without it being a server fn.
