### ISSUE TITLE
the format!() bug in <a href={format!()}>

### ISSUE THREAD

**Issue by yiwufen** [leptos-rs/leptos#2554]
**Describe the bug**

```
let edit_url = create_memo(move |_| format!{"/edit_chapter/{}/{}", novel_name(), chapter_title()});
...
<a href={edit_url} class="p-2 hover:text-blue-400">edit1</a>
<a href={format!("/edit_chapter/{}/{}", novel_name(), chapter_title())} class="p-2 hover:text-blue-400">edit2</a>
```
cargo leptos
in edge
```
<a href="/edit_chapter/aaa/bbb" class="p-2 hover:text-blue-400">edit1</a>
<a href="/edit_chapter/aaa/" class="p-2 hover:text-blue-400">edit2</a>
```
![image](https://github.com/leptos-rs/leptos/assets/95032361/b1c867a9-7e95-4c87-bfa8-583b277372a3)

**Leptos Dependencies**
```toml
[dependencies]
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true, features = ["macros"] }
console_error_panic_hook = "0.1"
http = { version = "1.0.0", optional = true }
leptos = { version = "0.6", features = ["nightly"] }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_actix = { version = "0.6", optional = true }
leptos_router = { version = "0.6", features = ["nightly"] }
wasm-bindgen = "=0.2.92"
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
sqlx ={ version = "0.7", features = ["runtime-async-std", "sqlite", "chrono"], optional = true }
uuid = { version = "1.8.0", features = ["v4"], optional = true }
```

**Expected behavior**
the tag 'a'  should be the same.
