### ISSUE TITLE
Error when running server function inside spawn_local

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#2562]
**Describe the bug**
When using `spawn_local` to get data from the server instead of fetching from inside a resource, then the `extract` function inside the server function will cause an error: `"HttpRequest should have been provided via context"`.

**Leptos Dependencies**
```toml
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true, features = ["macros"] }
console_error_panic_hook = "0.1"
cfg-if = "1"
http = { version = "0.2", optional = true }
leptos = { version = "0.6.11", features = ["nightly"] }
leptos_meta = { version = "0.6.11", features = ["nightly"] }
leptos_actix = { version = "0.6.11", optional = true }
leptos_router = { version = "0.6.11", features = ["nightly"] }
leptos_dom = "0.6.11"
leptos_reactive = { version = "0.6.11" }
leptos_macro = { version = "0.6.11" }
serde = "1.0.198"
```

**To Reproduce**
```rs
use leptos::*;
use leptos_meta::*;
use leptos_router::{Route, Router, Routes, SsrMode};
use std::time::Duration;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {
        <Router>
            <div>
                "Hello World"
                    <Routes>
                        <Route path="/" view=|| {
                            view! {<FrontPage />}
                        } ssr=SsrMode::PartiallyBlocked />
                    </Routes>
            </div>
        </Router>
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct UserData {
    name: String,
}

#[server]
pub async fn get_user_data() -> Result<UserData, ServerFnError> {
    use actix_web::HttpRequest;
    use leptos_actix::extract;

    let req: HttpRequest = extract().await.unwrap();
    println!("Method: {:?}", req.method());

    return Ok(UserData {
        name: "Luxalpa".to_string(),
    });
}

#[component]
pub fn FrontPage() -> impl IntoView {
    spawn_local(async move {
        let site_data = get_user_data().await.unwrap();
        println!("Site Data: {:?}", site_data);
    });

    view! { <div> "Front Page" </div> }
}
```

**Additional Context**
Using reqwest instead of a server function seems to be a workaround.
