### ISSUE TITLE
Clippy warnings in some components with rust 1.78

### ISSUE THREAD

**Issue by abusch** [leptos-rs/leptos#2571]
**Describe the bug**
There's a new clippy warning that shipped with Rust 1.78 and is turned on by default, which warns about empty rustdoc comments. See https://rust-lang.github.io/rust-clippy/master/index.html#/empty_docs.

It appears that the `#[component]` macro generates such empty rustdoc comments in the case where you don't specify your own rustdoc comment and the component has no properties, which now triggers the new clippy lint.

It's more of an annoyance than a bug as you can silence the warning by either adding a rustdoc to your component (probably good practice anyway...) or disabling the lint, but the component macro can probably be fixed to not output any empty rustdoc comment in that particular case.

**Leptos Dependencies**

```toml
leptos = { workspace = true, features = ["csr"] }
leptos-use = "0.10"
leptos_query = { version = "0.5", features = ["csr"] }
leptos_query_devtools = { version = "0.1", features = ["csr"] }
leptos_router = { version = "0.6", features = ["csr"] }
```

**To Reproduce**
- Add a component like the following:
```rust
#[component]
pub fn Foo() -> impl IntoView {
    view! { "test" }
}
```
- run `cargo clippy`

**Expected behavior**
There shouldn't be any `clippy::empty_docs` warning.
