### ISSUE TITLE
leptos_router parent Route attr view is not generating view for dynamic routes

### ISSUE THREAD

**Issue by vitordhers** [leptos-rs/leptos#2586]
**Describe the bug**
When trying to render a `transparent` component, the parent `Router` view doesn't get rendered if I try to it dynamically. As a matter of fact, not even when trying to use static content it gets rendered.

```
#[component(transparent)]
fn TestTransparent() -> impl IntoView {
    view! {
        <Route path="/" view=|| view! {<div> <p>this is useless</p> <Outlet /> </div>}>
            <Route path="test" view =|| view! {<span>TEST CHILD #2</span>} />
            <Route path="" view =|| view! {<span>TEST CHILD #1</span>} />
        </Route>
    }
}
```
so, when I proceed to ```log!("TEST TRANSPARENT {:?}", view! {<TestTransparent />}.render_to_string());```, I get an empty string, as if not even the parent component Route view has been rendered.
I believe that's a bug, since at least the view on the parent `Route` should be rendered, regardless of child routes.

**Leptos Dependencies**

```toml
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true, features = ["macros"] }
http = { version = "1.0.0", optional = true }
leptos_actix = { version = "0.6.11", optional = true }
leptos_i18n = { workspace = true, features = ["track_locale_files", "serde"] }
leptos ={ version = "0.6.11", features = [] }
leptos_meta = { version = "0.6.11", features = [] }
leptos_router = { version = "0.6.11", features = [] }
wasm-bindgen = { version = "0.2.92", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4" }
js-sys = "0.3"
serde = { version = "1.0.197", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1.7"
```

**To Reproduce**
1. Go to ['My repository'](https://github.com/vitordhers/liturgy-of-the-day) in order to reproduce the issue;
2. run `cargo leptos watch` in order for the code to build and compile;
3. Go to `client/src/pages/locale_routes/mod.rs` in order to see where the logs come from

**Expected behavior**
`render_to_string` should display nested components in transparent routes, regardless of dynamic or static

**Additional context**
My application intends to make heavy use of `i18n` features for displaying appropriate ssr results and custom route names, to the point it makes no sense to write each one manually.

Thanks for your awesome work!
