### ISSUE TITLE
Enabling the rkyv feature is failing to compile

### ISSUE THREAD

**Issue by tuzz** [leptos-rs/leptos#2610]
**Describe the bug**
When I add `features = ["rkyv"]` to the `leptos` dependency, I get an error.

**Leptos Dependencies**

```toml
leptos = { version = "0.6", features = ["rkyv"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6" }
leptos_router = { version = "0.6" }
```

**To Reproduce**
1. `cargo leptos new --git leptos-rs/start-axum --name foo`
2. `cd foo`
3. Add `features = ["rkyv"]` to `leptos` in `Cargo.toml`
4. `cargo leptos serve`

**Expected behavior**
The app compiles successfully.

**Screenshots**
<img width="961" alt="Screenshot 2024-06-02 at 17 12 56" src="https://github.com/leptos-rs/leptos/assets/892251/84a70027-4e60-4acd-8eca-914254198b4e">
