### ISSUE TITLE
Fresh project's build fails because unsuported wasm features on tokio

### ISSUE THREAD

**Issue by cidit** [leptos-rs/leptos#2649]
**Describe the bug**

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.3", features = ["serde"] }
leptos_axum = { version = "0.3", optional = true }
leptos_meta = { version = "0.3"}
leptos_router = { version = "0.3"}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
