### ISSUE TITLE
[0.7-alpha] `<Route ... view=Component/>` fails if `Component` has an optional prop

### ISSUE THREAD

**Issue by bicarlsen** [leptos-rs/leptos#2659]
`<Route ... view=Component/>` fails if `Component` has an optional prop, but `<Route ... view=view! { <Component/> }/>` works.
```rust
<Router>
  <Routes fallback=|| "An error occurred">
    <Route path=StaticSegment("") view=Count/> // Errors
    <Route path=StaticSegment("") view=move || view! { <Count/> }/> // Works
  </Routes>
<Router>

#[component]
fn Register(#[prop(default = 0)] count: usize) -> impl IntoView {
...
}
```

**Leptos Dependencies**
```toml
leptos = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7", features = ["csr", "nightly"] }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", branch =  "leptos_0.7", features = ["nightly"] }
```

**To Reproduce**
See example above.

**Expected behavior**
Optional props will be set to their default value.

**Screenshots**
N/A

**Additional context**
N/A
