### ISSUE TITLE
Router base has no effect

### ISSUE THREAD

**Issue by littlebenlittle** [leptos-rs/leptos#2668]
**Describe the bug**

Setting `<Router base="base-path">` has no effect.

**Leptos Dependencies**

```toml
leptos = { version = "0.6", features = ["csr", "nightly"] }
leptos_meta = { version = "0.6", features = ["csr", "nightly"] }
leptos_router = { version = "0.6", features = ["csr", "nightly"] }
```

**To Reproduce**

Navigate to any page.

**Expected behavior**

`<Route path="/" view=Home/>` should display `Home` view when navigating to `/base-path/`, instead navigates to catch-all route.
