### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by 4f48** [leptos-rs/leptos#2679]
**Describe the bug**
I'm trying to use a custom font for my Leptos web app (CSR, using Trunk, and TailwindCSS). It imports the font just fine, and shows up in the network tab, but throws this browser error: `Failed to decode downloaded font: http://localhost:8080/InterVariable.woff2` (see screenshot in its respective section).

**Leptos Dependencies**
```toml
[dependencies]
leptos = { version = "0.6", features = ["csr", "nightly"] }
leptos_meta = { version = "0.6", features = ["csr", "nightly"] }
leptos_router = { version = "0.6", features = ["csr", "nightly"] }
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1"

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
web-sys = { version = "0.3", features = ["Document", "Window"] }


[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
```

**To Reproduce**
1. Setup Leptos using https://github.com/leptos-rs/start-trunk
2. Modify index.html to look like this:
``` html
<!DOCTYPE html>
<html>
  <head>
    <!-- Add a plain CSS file: see https://trunkrs.dev/assets/#css -->
    <!-- If using Tailwind with Leptos CSR, see https://trunkrs.dev/assets/#tailwind instead-->
    <link data-trunk rel="tailwind-css" href="public/tailwind.css" />

    <!-- Include favicon in dist output: see https://trunkrs.dev/assets/#icon -->
    <link data-trunk rel="icon" href="public/favicon.ico" />

    <!-- include support for `wasm-bindgen --weak-refs` - see: https://rustwasm.github.io/docs/wasm-bindgen/reference/weak-references.html -->
    <link data-trunk rel="rust" data-wasm-opt="z" data-weak-refs />
  </head>
  <body></body>
</html>
``` 
3. Add tailwind.css file to public/
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
    @font-face {
        font-family: Inter;
        font-feature-settings: 'liga' 1, 'calt' 1;
        font-display: swap;
        src: url(InterVariable.woff2) format('woff2');
    }
}
```

4. Run this
``` sh
npx tailwindcss init
```
5. Add [InterVariable.woff2](https://github.com/4f48/semail/raw/9960746b4bede4c0b0480188ebb567a74a1153ac/client/static/InterVariable.woff2) (worked before in my JS project) to public/

6. Serve the app by running
``` sh
trunk serve
```

**Expected behavior**
Load my font and work!

**Screenshots**
![Network tab](https://github.com/leptos-rs/leptos/assets/154711213/9b1455d0-9a42-431f-8403-f441e89eab91)
![Developer console](https://github.com/leptos-rs/leptos/assets/154711213/65a45f7d-0916-4648-913e-6d1915a45d14)
