### ISSUE TITLE
Title 

### ISSUE THREAD

**Issue by agraboso** [leptos-rs/leptos#2715]
**Describe the bug**
When using `leptos_meta`'s `<Title>`, the `<title>` tag gets correctly set from server, but becomes empty when navigating on the client side.

**Leptos Dependencies**
```toml
axum = { version = "1.7", features = ["macros"], optional = true }
console_error_panic_hook = "0.1"
derive_more = { version = "0.99.17", default-features = false, features = [
    "deref",
] }
http = "1"
icondata = "0.3.1"
icondata_core = "0.1"
indoc = "2.0.5"
leptos = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.7", features = [
    "nightly",
] }
leptos_axum = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.7", optional = true }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.7" }
leptos_router = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.7", features = [
    "nightly",
] }
leptos_router_macro = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.7" }
serde = { version = "1.0", features = ["derive"] }
surrealdb = { version = "1.5.1", features = ["kv-speedb"], optional = true }
thiserror = "1"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
], optional = true }
tracing = { version = "0.1", optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
uuid = "1.6.1"
wasm-bindgen = "=0.2.92"
```

**To Reproduce**
Use `<Title formatter=|text| format!("{text} - My website")/>` in the main component, and update it in any page using `<Title text="Page"/>`. Load any page from server: get correct `<title>` (`Page - My website`). Navigate to any page: `<title>` is empty.

**Expected behavior**
`<title>` tag should be set whether loading from the server or navigating on the client.

**Screenshots**
None

**Additional context**
I'm tracking the `leptos_0.7` branch, which is now at `81e7cd83293f809560e5545ef0398eacfaaf0b74`.
