### ISSUE TITLE
LocalResource spawn_local called from outside of a task::LocalSet

### ISSUE THREAD

**Issue by VVishion** [leptos-rs/leptos#2717]
**Describe the bug**

```rust
async fn create_list() -> Vec<String> {
    vec![String::from("Ehm")]
}

#[component]
pub fn App() -> impl IntoView {
    //let list = Resource::new(|| (), |_| async { create_list().await });
    let list = LocalResource::new(|| async { create_list().await });

    view! {
        <div id="app">
            {move || list.get()}
        </div>
    }
}
```
Panics on the server with 
```
thread 'main' panicked at /home/vvishion/.cargo/git/checkouts/leptos-2c8932a5258b3db6/4bc999e/any_spawner/src/lib.rs:136:17:
`spawn_local` called from outside of a `task::LocalSet`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The above code doesnt panic with `let list = Resource::new(|| (), move |_| async move { create_list().await });`

**Leptos Dependencies**
```toml
leptos = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
leptos_axum = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
``` 
at the time of commit https://github.com/leptos-rs/leptos/commit/4bc999ead36ab9eeb2b80e13ef945b343e9e3393

**To Reproduce**
compile

**Expected behavior**
Working as `Resource`

**Additional context**
I can provide the full workspace if this isnt enough to reproduce
