### ISSUE TITLE
Suspense renders fallback and children on page refresh

### ISSUE THREAD

**Issue by GarrettFleischer** [leptos-rs/leptos#2747]
**Describe the bug**
I have an issue where with nested Suspense in an SSR app, the inner Suspense renders both the fallback and the children on page refresh. If I navigate to the page via an ```<a href>``` button in the app then it works fine. It's only when refreshing in the browser.

It seems almost identical to this issue https://github.com/leptos-rs/leptos/issues/1156

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
[dependencies]
axum = { version = "0.7", optional = true }
console_error_panic_hook = "0.1"
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
wasm-bindgen = "=0.2.92"
thiserror = "1"
tracing = { version = "0.1", optional = true }
http = "1" 
serde = { version = "1", features = ["derive"] }
serde_json = "1"
surrealdb = { version = "1.5.3", optional = true}
bcrypt = {version = "0.15.1", optional =  true}
chrono = {version = "0.4", optional = true}
cfg-if = "1.0.0"
leptos-use = {version = "0.11"}
dotenv = {version = "*", optional = true}

[features]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
    "dep:axum",
    "dep:tokio",
    "dep:tower",
    "dep:tower-http",
    "dep:leptos_axum",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:tracing",
    "dep:surrealdb",
    "dep:bcrypt",
    "dep:chrono",
    "dep:dotenv",
    "leptos-use/ssr",
    "leptos-use/axum"
]
```

**To Reproduce**
have an outer Suspense that waits for a server resource, and an inner Suspense that waits for a different server resource.

```rust
use leptos::*;

#[server]
async fn fetch_items() -> Result<Vec<(usize, String, String)>, ServerFnError> {
    use std::time::Duration;
    tokio::time::sleep(Duration::from_secs(2)).await;

    Ok(vec![
        (1, "The Meaning of Life".to_string(), "$42".to_string()),
        (2, "The Number".to_string(), "$23".to_string()),
    ])
}

#[component]
pub fn Items() -> impl IntoView {
    let items_res = create_resource(|| (), |_| fetch_items());

    let items = move || match items_res() {
        Some(Ok(items)) => items,
        _ => Vec::<(usize, String, String)>::new(),
    };

    view! {
      <div>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            <Suspense fallback=|| view! { <div>...</div> }>
              <For
                each=items
                key=|item| item.0
                children=|item| {
                    view! {
                      <tr>
                        <td>{item.1}</td>
                        <td>{item.2}</td>
                      </tr>
                    }
                }
              />

            </Suspense>
          </tbody>
        </table>
      </div>
    }
}

```

**Expected behavior**
Only the children of the suspense are rendered after loading is complete on page refresh

**Current behavior**
It renders the loading fallback plus the children of the suspense on page refresh
