### ISSUE TITLE
ArcAsyncDerived::new_with_initial() setting multiple dependencies will *NOT* hold until the latest change is ready

### ISSUE THREAD

**Issue by VVishion** [leptos-rs/leptos#2787]
**Describe the bug**
```rust
#[cfg(test)]
pub mod tests {
    #[test]
    fn test_async() {
        use leptos::reactive_graph::computed::*;
        use leptos::reactive_graph::prelude::*;
        use leptos::reactive_graph::signal::*;
        tokio_test::block_on(async move {
            leptos::spawn::Executor::init_tokio();
            let _guard = leptos::reactive_graph::diagnostics::SpecialNonReactiveZone::enter();

            let signal1 = RwSignal::new(0);
            let signal2 = RwSignal::new(0);
            let derived = ArcAsyncDerived::new_with_initial(Some(5), move || async move {
                // reactive values can be tracked anywhere in the `async` block
                let value1 = signal1.get();
                tokio::time::sleep(std::time::Duration::from_millis(25)).await;
                let value2 = signal2.get();

                value1 + value2
            });

            // the value can be accessed synchronously as `Option<T>`
            assert_eq!(derived.get(), Some(5));
            // we can also .await the value, i.e., convert it into a Future
            assert_eq!(derived.clone().await, 5);
            assert_eq!(derived.get(), Some(5));

            signal1.set(1);
            // while the new value is still pending, the signal holds the old value
            tokio::time::sleep(std::time::Duration::from_millis(5)).await;
            assert_eq!(derived.get(), Some(5));

            // setting multiple dependencies will hold until the latest change is ready
            signal2.set(1);
            assert_eq!(derived.await, 2);
        });
    }
}
```

panics with
```
assertion `left == right` failed
  left: 5
 right: 2
```

Bug is probably somewhere here
https://github.com/leptos-rs/leptos/blob/288da232acb1fabd77a8d7ae7896524d421886a6/reactive_graph/src/computed/async_derived/arc_async_derived.rs#L276-L284

**Leptos Dependencies**

```toml
leptos = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos_axum = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", branch = "main" }
```
as of commit 288da232

**To Reproduce**
`cargo test`

**Expected behavior**
Should pass
