### ISSUE TITLE
Inconsistency in `aria-current="page"` behavior in `<A>`components

### ISSUE THREAD

**Issue by agraboso** [leptos-rs/leptos#2793]
**Describe the bug**

The `aria-current="page"` attribute loaded from server is not unset when navigating away until you navigate on the client back to it.

**Leptos Dependencies**

With the `main` branch at  [`e0cc6fd7b909b7e6727df5bde5514b3fe3f6f565`](https://github.com/leptos-rs/leptos/tree/e0cc6fd7b909b7e6727df5bde5514b3fe3f6f565):
```toml
leptos = { git = "https://github.com/leptos-rs/leptos", branch = "main", features = [
    "nightly",
] }
leptos_axum = { git = "https://github.com/leptos-rs/leptos", branch = "main", optional = true }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
leptos_router = { git = "https://github.com/leptos-rs/leptos", branch = "main", features = [
    "nightly",
] }
```

**To Reproduce**

Say you have two `<A>`s:
```html
<A href="/1">"1"</A>
<A href="/2">"2"</A>
```
Loading from server in route `/1` results in
```html
<a href="/1" aria-current="page">"1"</a>
<a href="/2">"2"</a>
```
Clicking on the link provided by the second `a` tag correctly sets `aria-current="page"` in the second link, but leaves it in in the first:
```html
<a href="/1" aria-current="page">"1"</a>
<a href="/2" aria-current="page">"2"</a>
```
Clicking again on the first link returns to 
```html
<a href="/1" aria-current="page">"1"</a>
<a href="/2">"2"</a>
```
Clicking again on the second link now does the right thing:
```html
<a href="/1">"1"</a>
<a href="/2" aria-current="page">"2"</a>
```
Navigating back and forth between the two routes continues to work as expected.

**Expected behavior**

What happens in the last step above: navigating away from the page loaded from the server should unset the `aria-current="page"` on the corresponding link.

**Screenshots**

None.

**Additional context**

None.
