### ISSUE TITLE
Inconsistency in client-side query fragment handling

### ISSUE THREAD

**Issue by agraboso** [leptos-rs/leptos#2806]
**Describe the bug**

Clicking on the link rendered by an `<A>` component on the server does not dispose of the query fragment of the URL. A second click does, but does not empty the input field.

**Leptos Dependencies**

With the main branch at [`d1248d3faf89ccae572827a6b96358c6d998caaf`](https://github.com/leptos-rs/leptos/commit/d1248d3faf89ccae572827a6b96358c6d998caaf):
```toml
leptos = { git = "https://github.com/leptos-rs/leptos", branch = "main", features = [
    "nightly",
] }
leptos_axum = { git = "https://github.com/leptos-rs/leptos", branch = "main", optional = true }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
leptos_router = { git = "https://github.com/leptos-rs/leptos", branch = "main", features = [
    "nightly",
] }
```

**To Reproduce**

Say you have something like the following (mostly, the example from section 9.5 of the Leptos book), rendered at the route `/search` in an SSR application:
```rust
#[component]
pub fn FormExample() -> impl IntoView {
    let search = move || use_query_map().get("q").cloned().unwrap_or_default();

    view! {
        <A href="/search" >"Search"</A>
        <Form method="GET" action="">
            <input type="search" name="q" value=search/>
            <input type="submit"/>
        </Form>
    }
}
```
Whenever you enter a term `term` in the input field and submit the form, you navigate (client-side) to `/search?q=term`. Clicking on the link rendered by the `<A>` component does clear the `search` signal (so it is correctly emptied in the query map), but the query fragment remains in the URL. Clicking a second time updates the URL to `/search`. The value of the input field remains no matter how many times you click on the link instead of updating it from the URL.

When rendering server-side (i.e., typing `/search?q=term` manually, or refreshing the page when at that URL), the input field behaves correctly: its value is set to `term`.

**Expected behavior**

The first click on the link rendered by the `<A>` should change the URL to `/search` and update the value in the input field of the `<Form>`.

**Screenshots**

None

**Additional context**

None
