### ISSUE TITLE
leptos 0.6 fails to compile due to time dependency

### ISSUE THREAD

**Issue by berkus** [leptos-rs/leptos#2813]
**Describe the bug**
rustc 1.80.0 (051478957 2024-07-21)

Compilation fails with 

```
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/berkus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.31/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

**Leptos Dependencies**

```toml
leptonic = { version = "0.5.0", features = [] }
leptos = { version = "0.6", features = [] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = [] }
leptos_router = { version = "0.6", features = [] }
```
