### ISSUE TITLE
At … you tried to access a reactive value which was defined at …, but it has already been disposed.

### ISSUE THREAD

**Issue by g2p** [leptos-rs/leptos#2842]
**Describe the bug**
I'm using the following (sorry I haven't written a minimal reproducer):
Leptos 0.7-beta (pulled from main branch due to #2723); islands; SsrMode::InOrder; Resource::new_blocking.

With all this I'm rendering a page from a server function called through a Resource and a Transition element, similar to how examples/hackernews_islands_axum loads stories.

Things render fine but I see Tokio threads crashing through the console:

```
Inside ListEvent Transition
thread 'tokio-runtime-worker' panicked at …/src/github.com/leptos-rs/leptos/reactive_graph/src/traits.rs:366:39:
At …/web/src/app.rs:671:22, you tried to access a reactive value which was defined at web/src/app.rs:662:28, but it has already been disposed.
```

Then the server function is called again, so things still render.

Wrapping the Resource in a Memo doesn't help.

If I switch to Resource::new (no explicit blocking), I don't have the crashes.

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0-beta", features = ["experimental-islands"] }
leptos_axum = { version = "0.7.0-beta", optional = true }
leptos_meta = "0.7.0-beta"
leptos_macro = { version = "0.7.0-beta", features = ["experimental-islands"] }
leptos_router = "0.7.0-beta"
```

This might be related to #2789.
