### ISSUE TITLE
(Protected)ParentRoute give 404 errors with Islands

### ISSUE THREAD

**Issue by VincentBerthier** [leptos-rs/leptos#2880]
**Describe the bug**
Flat routes work just fine, but using `<ParentRoute>` or `<ProtectedParentRoute>` always gives 404 errors, which is quite unfortunate.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { git = "https://github.com/leptos-rs/leptos", features = ["experimental-islands"] }
leptos_axum = { git = "https://github.com/leptos-rs/leptos", optional = true }
leptos_meta = { git = "https://github.com/leptos-rs/leptos" }
leptos_router = { git = "https://github.com/leptos-rs/leptos" }
```

**To Reproduce**
Reproduction (on the hackernews axum island example): https://github.com/VincentBerthier/leptos-repro/blob/main/src/lib.rs

**Expected behavior**
To *not* get a 404…

**Additional context**
Nested routes (*à la* 0.6) do not work either since `<Route>` doesn’t take children.
