### ISSUE TITLE
Multi-value query-string parameters discard all but last

### ISSUE THREAD

**Issue by shivjm** [leptos-rs/leptos#2882]
**Describe the bug**
Passing a query string like `?param=a&param=b` redirects the page (or rewrites the location) to `?param=b`. This seems partially intentional since `ParamsMap` maps `String` to `String`, but as you can see in the example, serializing a form can itself produce multiple values.

**Leptos Dependencies**

```toml
leptos = { version = "0.6" }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6" }
leptos_router = { version = "0.6" }
```

**To Reproduce**
1. Clone shivjm/leptos-multi-value-params-mwe.
2. Run <kbd>cargo leptos serve</kbd> (or <kbd>watch</kbd>).
3. Open localhost:3000.
4. Check the boxes.
5. Click on Submit.
6. Note that the URL in the address bar and the query string provided by Leptos are correct but the `ParamsMap` is not.
7. Either refresh the page or navigate to the same URL.
8. Note that the URL in the address bar has dropped one value for the parameter.

**Expected behavior**
Multi-value parameters should be collected into a `Vec` or equivalent structure. I imagine this would have to be a breaking change since `ParamsMap` currently maps `String` to `String`.

**Screenshots**
<img width="306" alt="" src="https://github.com/user-attachments/assets/2791fb5a-9be1-4ec1-924a-3d7446785d6a">
