### ISSUE TITLE
Unable to provide context from ProtectedParentRoute to its children routes

### ISSUE THREAD

**Issue by B83C** [leptos-rs/leptos#2897]
**Describe the bug**
I was trying to provide a User instance from the view prop of a ProtectedParentRoute, hoping that its children routes be able to access it when routing conditions are met. However, it turned out that NOTHING was provided in said routes (children). So, I assume that protectedparentroute and its descendant routes are of the same level in the tree? 

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.7.0-beta2", features = ["nightly"], optional = true }
leptos_axum = { version = "0.7.0-beta2", optional = true }
leptos_meta = { version = "0.7.0-beta2"}
leptos_router = { version = "0.7.0-beta2", features = ["nightly"] }
leptos_router_macro = "0.7.0-beta2"
leptos_macro = { version = "0.6.14", optional = true, features = ["axum", "nightly", "csr", "hydrate"] }
```

**To Reproduce**
```rust                    
                    <ProtectedParentRoute
                        path=path!("")
                        condition=move || user.get().map(|n| n.is_ok_and(|x| x.is_some()))
                        view=move || {
                            provide_context::<User>(user.get().unwrap().unwrap().unwrap());
                            // provide_context::<
                            view! { <Outlet />}
                        }
                        redirect_path=|| "/login"
                    >
                        <Route
                            path=path!("/dashboard")
                            view=move || {
                                // provide_context::<User>(user.get().unwrap().unwrap().unwrap());
                                leptos::logging::log!("{:?}", use_context::<User>());
                                view! { <Dashboard /> }
                            }
                        />
                        <Route
                            path=path!("/logout")
                            view=move || view! { <Logout action=logout /> }
                        />
                        <Route
                            path=path!("/payment")
                            view=PaymentPage
                        />
                    </ProtectedParentRoute>
```

**Expected behavior**
In any of the children routes, the User instance is provided

**Screenshots**

**Additional context**
