### ISSUE TITLE
URL with hash has erroneous space causing 404

### ISSUE THREAD

**Issue by kahnclusions** [leptos-rs/leptos#2908]
**Describe the bug**

@mrvillage the new hash file changes [here](https://github.com/leptos-rs/leptos/pull/2894/files#diff-8b0fbad6e90bad446b9c01f6ac6c6ba1a9970ba237cd3f9968dbbe62b27e773aR57-R62) don't work for me, the hash needs to be trimmed before use, as the generated `hash.txt` can have spaces after the `:` (see [here](https://github.com/leptos-rs/cargo-leptos/blob/5dd5ec23c549dced5deff026cb747d9dbe50db80/src/compile/hash.rs#L35C2-L35C40))

```txt
js: bB2KJyh5l8cGJhaNRusboA
wasm: dITltadhYjmXcisULGztvg
css: v5rStByMZc3_yA7tllspVw
```

so my URL with hash is wrong: `"https://mysite/pkg/myproject. dITltadhYjmXcisULGztvg.wasm"`

**Leptos Dependencies**

```toml
leptos = { git = "https://github.com/leptos-rs/leptos", features = [ "nightly", "tracing"] }
leptos_meta = { git = "https://github.com/leptos-rs/leptos" }
leptos_router = { git = "https://github.com/leptos-rs/leptos", features = [ "nightly"] }
leptos_axum = { git = "https://github.com/leptos-rs/leptos" }
```
