### ISSUE TITLE
beta5 problems

### ISSUE THREAD

**Issue by mahmoud-eltahawy** [leptos-rs/leptos#2962]
**Describe the bug**
running cargo update on my project 
then cargo leptos watch
failed to compile with
error: queries overflow the depth limit!

i increased recursion limit with
#![recursion_limit = "256"]

then it is compiled but at run time when i hit code that uses 
expect_context function it gives me error

thread 'tokio-runtime-worker' panicked at /home/eltahawy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.0-beta5/src/owner/context.rs:261:9:
Location { file: "src/app/review_model.rs", line: 11, col: 19 } expected context of type "nagah::app::BackendContext" to be present

# Note 
the code worked fine at previous version

i provide the context from the axum integration

```rust
    let context = BackendContext {/*code*/};

    let app = Router::new()
        .leptos_routes_with_context(
            &leptos_options,
            routes,
            move || provide_context(context.clone()),
            {
                let leptos_options = leptos_options.clone();
                move || shell(leptos_options.clone())
            },
        )
        .fallback(leptos_axum::file_and_error_handler(shell))
        .with_state(leptos_options);
```

**Leptos Dependencies**

```toml
axum = { version = "0.7", optional = true }
console_error_panic_hook = "0.1"
leptos = { version = "0.7.0-beta" }
leptos_axum = { version = "0.7.0-beta", optional = true }
leptos_meta = { version = "0.7.0-beta" }
leptos_router = { version = "0.7.0-beta" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
wasm-bindgen = "=0.2.93"
thiserror = "1"
tracing = { version = "0.1", optional = true }
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls","postgres","uuid","chrono" ] ,optional = true}
http = "1"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
http-auth-basic = "0.3.5"
```
