### ISSUE TITLE
Issues with runtime crashes when using ProtectedParentRoute

### ISSUE THREAD

**Issue by niklass-l** [leptos-rs/leptos#2990]
Reopened as an issue instead of pull request (#2988).

I've been having issues with the ProtectedParentRoute component, it seems to be crashing whenever the condition evaluates to false, at least when used with ssr enabled (I haven't tested other modes).

The code edit in my fork at https://github.com/niklass-l/leptos/tree/fix-protected-parent-route-ssr-issue seems to fix the immediate issue, but I'm sure the code I'm removing was there for a reason.

I'll include a minimal example here so you can see try it out yourself, and see if you can reproduce it. The code is based off of the axum 0.7 starter template, you can find the full code at https://github.com/niklass-l/start-axum-0.7.

Steps to reproduce:

Cargo.toml:
```toml
[package]
name = "minimal-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
axum = { version = "0.7", optional = true }
console_error_panic_hook = "0.1"

# Crashes when refreshing at /dashboard unauthenticated
leptos = { version = "0.7.0-beta5" }
leptos_axum = { version = "0.7.0-beta5", optional = true }
leptos_meta = { version = "0.7.0-beta5" }
leptos_router = { version = "0.7.0-beta5" }

# Does not crash when refreshing at /dashboard unauthenticated
# leptos = { git = "https://github.com/niklass-l/leptos", branch = "fix-protected-parent-route-ssr-issue" }
# leptos_axum = { git = "https://github.com/niklass-l/leptos", branch = "fix-protected-parent-route-ssr-issue", optional = true }
# leptos_meta = { git = "https://github.com/niklass-l/leptos", branch = "fix-protected-parent-route-ssr-issue" }
# leptos_router = { git = "https://github.com/niklass-l/leptos", branch = "fix-protected-parent-route-ssr-issue" }

... 
```

app.rs:
```rust
use leptos::prelude::*;
use leptos_meta::{provide_meta_context, MetaTags, Stylesheet, Title};
use leptos_router::{
    components::{ProtectedParentRoute, Route, Router, Routes, A},
    StaticSegment,
};

pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <AutoReload options=options.clone() />
                <HydrationScripts options/>
                <MetaTags/>
            </head>
            <body>
                <App/>
            </body>
        </html>
    }
}

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    let authenticated = RwSignal::new(false);

    view! {
        <Stylesheet id="leptos" href="/pkg/minimal-example.css"/>
        <Title text="Protected Route Example"/>
        <Router>
            <nav>
                <A href="/">"Home"</A> " | "
                <A href="/dashboard">"Dashboard"</A> " | "
                <A href="/profile">"Profile"</A> " | "
                <button on:click=move |_| authenticated.update(|auth| *auth = !*auth)>
                    {move || if authenticated.get() { "Logout" } else { "Login" }}
                </button>
            </nav>
            <main>
                <Routes fallback=|| "Page not found.".into_view()>
                    <Route path=StaticSegment("") view=HomePage/>
                    <ProtectedParentRoute
                        path=StaticSegment("")
                        view=|| view! { <div>"Protected Content"</div> }
                        condition=move || Some(authenticated.get())
                        redirect_path=|| "/".to_string()
                    >
                        <Route path=StaticSegment("dashboard") view=DashboardPage/>
                        <Route path=StaticSegment("profile") view=ProfilePage/>
                    </ProtectedParentRoute>
                </Routes>
            </main>
        </Router>
    }
}

#[component]
fn HomePage() -> impl IntoView {
    view! {
        <h1>"Welcome to the Home Page"</h1>
        <p>"This page is accessible to everyone."</p>
    }
}

#[component]
fn DashboardPage() -> impl IntoView {
    view! {
        <h1>"Dashboard"</h1>
        <p>"This is a protected page. You should only see this if you're authenticated."</p>
    }
}

#[component]
fn ProfilePage() -> impl IntoView {
    view! {
        <h1>"Profile"</h1>
        <p>"This is another protected page. You should only see this if you're authenticated."</p>
    }
}
```

With the leptos crates using 0.7.0-beta5, whenever the user is authenticated and I do a hard refresh in the browser for localhost:3000/dashboard, I get this error in the browser logs (truncated for brevity):

```
minimal-example.wasm:0x233cec Uncaught (in promise) RuntimeError: unreachable
    at minimal_example.wasm.std::sys::pal::wasm::common::abort_internal::hba1154986144418e (minimal-example.wasm:0x233cec)
    at minimal_example.wasm.std::sys::sync::rwlock::no_threads::RwLock::write::h71d7d4a3ca559db1 (minimal-example.wasm:0xaa706)
    at minimal_example.wasm.std::sync::rwlock::RwLock<T>::write::h05e0979ff3cae7ef (minimal-example.wasm:0x1f36d9)
    at minimal_example.wasm.<reactive_graph::signal::arc_rw::ArcRwSignal<T> as reactive_graph::traits::Writeable>::try_write::h37a3ba712252afb7 (minimal-example.wasm:0x1d7260)
    at minimal_example.wasm.<T as reactive_graph::traits::Update>::try_maybe_update::h77c16c41e40c6aa1 (minimal-example.wasm:0x96222)
    at minimal_example.wasm.reactive_graph::traits::Update::try_update::h65491631a3980d29 (minimal-example.wasm:0x12ee58)
    at minimal_example.wasm.<T as reactive_graph::traits::Set>::set::h7fc18d2e8d699cac (minimal-example.wasm:0x134362)
    at minimal_example.wasm.leptos_router::components::RouterContext::navigate::hce67dfaf604b821d (minimal-
...
```

If I switch to my forked version then it correctly redirects to localhost:3000
