### ISSUE TITLE
Router hooks not available on the client in islands mode

### ISSUE THREAD

**Issue by bambooyuh** [leptos-rs/leptos#3071]
**Describe the bug**
The browser renders the html and css but throws an error: "Tried to access reactive URL outside a <Router> component." and "Uncaught (in promise) RuntimeError: unreachable"

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.7.0-gamma", features = ["nightly", "experimental-islands"] }
leptos_axum = { version = "0.7.0-gamma", optional = true }
leptos_meta = { version = "0.7.0-gamma" }
leptos_router = { version = "0.7.0-gamma", features = ["nightly"] }
```

**To Reproduce**
1. In the CLI, run: cargo leptos watch
2. Open the browser at localhost:8080 and view the error in the developer console

Implementing use_location() and use_url() results in the same errors.
If you change Header() in pages/team_page.rs from a #[island] to #[component], the errors goes away.
Additionally, the navigating to the dashboard(or homepage) does not produce an error in the browser. My suspicion is that this page component does not contain an Island, like the team_page.

Relevant code files:
src/components/header.rs
src/pages/team_page.rs

**Expected behavior**
For there to be no browser errors, and for all interactivity to work.

**Screenshots**

**Additional context**
code>>>
<img width="666" alt="Screenshot 2024-10-07 at 2 20 24 PM" src="https://github.com/user-attachments/assets/16d2c150-4648-48dd-ae28-10b2f82d1860">
<img width="658" alt="Screenshot 2024-10-07 at 2 20 56 PM" src="https://github.com/user-attachments/assets/a01f1038-ce90-4e3f-adbe-ddfe6fa41f2a">
<img width="600" alt="Screenshot 2024-10-07 at 6 27 11 PM" src="https://github.com/user-attachments/assets/93f561d8-d8f6-4ea1-93a5-67e4040398aa">
 https://github.com/bambooyuh/leptos_islands
