### ISSUE TITLE
"Uncaught RuntimeError: unreachable executed" using reactive-stores with recursive/nested data

### ISSUE THREAD

**Issue by wrl** [leptos-rs/leptos#3086]
testing against leptos 0.7.0-gamma2, reactive-stores 0.1.0-gamma2.

two questions here:
- I have a duplicate `component` for listing `Item`s: one which takes a `KeyedSubfield<Field<Item>, ...>` and one which takes `KeyedSubfield<Store<Item>, ...>`. I could not figure out how to unify these into one component, even though it seems like it should be possible.
- Running this code results in an "Uncaught RuntimeError: unreachable executed". Removing the call to `SubItemListView` in `ItemView` lists the top-level items as expected, but going any deeper than that blows up.

here's the code: [main.rs.txt](https://github.com/user-attachments/files/17319945/main.rs.txt)

relevant deps from cargo.toml:
```toml
[dependencies.leptos]
version = "0.7.0-gamma2"
features = ["csr", "nightly"]

[dependencies.reactive_stores]
version = "0.1.0-gamma2"
features = []

[dependencies.reactive_stores_macro]
version = "0.1.0-gamma2"
features = []

[dependencies.uuid]
version = "1"
features = ["v4", "js", "fast-rng"]
```
