### ISSUE TITLE
[0.7] textarea initialized with space character instead of being empty

### ISSUE THREAD

**Issue by winteler** [leptos-rs/leptos#3120]
Hello,

I think I've found a small bug where a textarea initialized with an empty String will be rendered with a single space character instead. A minimal reproduction is given below.

**Leptos Dependencies**
```toml
leptos = { version = "0.7.0-gamma3", features = ["nightly"] }
leptos_axum = { version = "0.7.0-gamma3", optional = true }
leptos_meta = { version = "0.7.0-gamma3" }
leptos_router = { version = "0.7.0-gamma3", features = ["nightly"] }
```

**To Reproduce**
```
use leptos::prelude::*;
use leptos_meta::{provide_meta_context, MetaTags, Stylesheet, Title};
use leptos_router::{components::{Route, Router, Routes}, StaticSegment};

pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <AutoReload options=options.clone() />
                <HydrationScripts options/>
                <MetaTags/>
            </head>
            <body>
                <App/>
            </body>
        </html>
    }
}

#[component]
pub fn App() -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context();

    view! {
        // injects a stylesheet into the document <head>
        // id=leptos means cargo-leptos will hot-reload this stylesheet
        <Stylesheet id="leptos" href="/pkg/reproduce-leptos-0-7-beta5.css"/>

        // sets the document title
        <Title text="Welcome to Leptos"/>

        // content for this welcome page
        <Router>
            <main>
                <Routes fallback=|| "Page not found.".into_view()>
                    <Route path=StaticSegment("/") view=HomePage/>
                </Routes>
            </main>
        </Router>
    }
}

#[component]
fn HomePage() -> impl IntoView {
    let data = RwSignal::new(String::from(""));
    view! {
        <textarea
            placeholder="Test..."
        >
            {data}
        </textarea>
    }
}
```

Thanks for your help and let me know if I can help :)
