### ISSUE TITLE
Tauri(Transparent) + Leptos: leptos_dom transparency panic after adding Routing via leptos_router

### ISSUE THREAD

**Issue by Salman-Sali** [leptos-rs/leptos#3165]
I am building a Tauri + Leptos windows app. The tauri window is transparent.

```json
 "app": {
    "withGlobalTauri": true,
    "windows": [
      {
        "title": "my_tauri_app",
        "transparent": true,
        "fullscreen": true,
        "alwaysOnTop": true
      }
    ]
```

My leptos component : `<MyComponent\> ` was rendering fine until i added leptos_router and mapped `<MyComponent\>` to `"/"`.
```rust
#[component]
pub fn App() -> impl IntoView { 
    view! {
        <Router>
            <main>
                    <Route path="/" view=MyComponent/>
            </main>
        </Router>
    }
}
```

Once I had added the route, `<App\>`  is not rendering and in the DevTools I can see this exception.

```console
my_tauri_app-ui-ed1e9e6dabb939de.js:445 
 panicked at <my home>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\leptos_dom-0.6.15\src/lib.rs:636:17:
tried to mount a Transparent node.

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de.js:448:17)
    at my_tauri_app_ui-02e4656794cff75e.wasm.console_error_panic_hook::Error::new::h59fa593c6e0cb8fc (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de_bg.wasm:wasm-function[3884]:0x1df74e)
    at my_tauri_app_ui-02e4656794cff75e.wasm.console_error_panic_hook::hook_impl::hd9e89f85a8f12432 (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de_bg.wasm:wasm-function[1023]:0x158077)
    at my_tauri_app_ui-02e4656794cff75e.wasm.console_error_panic_hook::hook::hffd92951bb64016c (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de_bg.wasm:wasm-function[5428]:0x1f9d5c)
    at my_tauri_app_ui-02e4656794cff75e.wasm.core::ops::function::Fn::call::hab09751e57c578fd (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de_bg.wasm:wasm-function[4823]:0x1f0f94)
    at my_tauri_app_ui-02e4656794cff75e.wasm.std::panicking::rust_panic_with_hook::h33fe77d38d305ca3 (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de_bg.wasm:wasm-function[2048]:0x1a05b4)
    at my_tauri_app_ui-02e4656794cff75e.wasm.std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07 (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de_bg.wasm:wasm-function[2754]:0x1bfb87)
    at my_tauri_app_ui-02e4656794cff75e.wasm.std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312 (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de_bg.wasm:wasm-function[6546]:0x2052fa)
    at my_tauri_app_ui-02e4656794cff75e.wasm.rust_begin_unwind (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de_bg.wasm:wasm-function[4229]:0x1e6775)
    at my_tauri_app_ui-02e4656794cff75e.wasm.core::panicking::panic_fmt::hde8b7aa66e2831e1 (http://localhost:1420/my_tauri_app-ui-ed1e9e6dabb939de_bg.wasm:wasm-function[4442]:0x1ea746)

my_tauri_app-ui-ed1e…de_bg.wasm:0x2053c2 
 Uncaught RuntimeError: unreachable
```

In the leptos_dom source, I can see this is whats throwing the exception.
```rust
#[cfg(all(target_arch = "wasm32", feature = "web"))]
impl Mountable for View {
    fn get_mountable_node(&self) -> web_sys::Node {
        match self {
            /*
            */
            Self::Transparent(_) => {
                panic!("tried to mount a Transparent node.") 
            }
        }
    }
````

So I modified it to the following and added the crate to my `cargo.toml` as path

```rust
 Self::Transparent(t) => {
                t.get_mountable_node()
                //panic!("tried to mount a Transparent node.")
            }
```

However, now I am not getting the error, but the `<App>` is still not rendering in dom.

**Orginal Cargo.toml(Without the path import)**
```toml
[package]
name = "my_tauri_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = { version = "0.6", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", femy_tauri_appatures = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1my.7"
leptos-use = "0.13.6"
leptos_router = { version = "0.6.15", features = ["csr"] }

[workspace]
members = ["src-tauri"]
```

Edit: When I access the trunk served localhost:1420 via chrome, I am getting the same issue. So it might not be tauri related.
