### ISSUE TITLE
[0.7] Subfield gets notified by parent change, but Field does not

### ISSUE THREAD

**Issue by caoculus** [leptos-rs/leptos#3169]
**Describe the bug**
After converting a `Subfield` into a `Field`, the `Field` is no longer notified of parent struct updates.

**Leptos Dependencies**
```toml
[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.0-rc0", features = ["csr", "nightly"] }
reactive_stores = "0.1.0-rc0"
```

**To Reproduce**
Click on the "Update" button. Only the value of "a" changes.

**Expected behavior**
The values of both "a" and "b" should change.

**Additional context**
```rust
use leptos::prelude::*;
use reactive_stores::{Field, Store};

#[derive(Store)]
struct State {
    a: i32,
    b: i32,
}

#[component]
fn App() -> impl IntoView {
    let state = Store::new(State { a: 0, b: 0 });
    let update = move || {
        state.update(|state| {
            state.a += 1;
            state.b += 1;
        });
    };

    let a = state.a();
    let b: Field<_> = state.b().into();

    view! {
        <p>Value of a: {move || a.get()}</p>
        <p>Value of b: {move || b.get()}</p>
        <button type="button" on:click=move |_| update()>
            Update
        </button>
    }
}

fn main() {
    console_error_panic_hook::set_once();
    mount_to_body(App);
}
```
