### ISSUE TITLE
[0.7] `#[component]` attribute doesn't work with `clippy::must_use_candidate`

### ISSUE THREAD

**Issue by zroug** [leptos-rs/leptos#3172]
**Describe the bug**

Leptos 0.7.0-rc0 `#[component]` attribute is incompatible with the `clippy::must_use_candidate` lint.

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0-rc0", features = ["nightly", "experimental-islands"] }
leptos_axum = { version = "0.7.0-rc0", optional = true }
leptos_router = { version = "0.7.0-rc0", features = ["nightly"] }
```

**To Reproduce**
1. Enable the `clippy::must_use_candidate` lint.
2. Create a component with the `#[component]` attribute.

**Expected behavior**
There should be no Clippy warning. There are at least three ways to achieve this:

1. Add the `#[must_use]` attribute to the component function. (My preferred option.)
2. Suppress the lint by adding `#[allow(clippy::must_use_candidate)]` to the component function.
3. Do not prevent the warning, but pass the `#[must_use]` attribute to the generated component function if the user adds the attribute manually.
