### ISSUE TITLE
issue with attr("viewBox", ...) and attrs. Attribute name casing not respected.

### ISSUE THREAD

**Issue by anvlkv** [leptos-rs/leptos#3190]
**Describe the bug**
When using `.attr("viewBox", some)` it renders attribute name correctly in ssr. When navigating on client attribute turns into "viewbox" which is not working in chrome. 

When using `view!{<svg viewBox=some></svg>}` it all works correctly but `attrs` passed as props seem ignored. 

**Leptos Dependencies**

```toml
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
leptos-use = { version = "0.13", features = ["use_element_bounding"] }
```

**To Reproduce**

1. have a route that renders `html::svg()` with a `.attr("viewBox", signal)`
2. reload the page on this route - **it works**
3. navigate elsewhere
4. navigate to the route with svg - **attribute name issue**

**Expected behavior**
attribute casing is respected
