### ISSUE TITLE
[hot reload] Hot reload broken for children after components

### ISSUE THREAD

**Issue by omani** [leptos-rs/leptos#3191]
**Describe the bug**
To reproduce clone this repo, which is a fresh starter axum-0.7 template with additionally tailwind included.
https://github.com/omani/lep7

as mentioned in discussion #2919:
hey @gbj. has something changed recently? I again started with the axum-0.7 template and hot-reloading works, but totally wrong children are being replaced in my browser. Im adding a `<p>` for example, and a weird button is added to the DOM. also removing children does not work properly. this is a very weird behavour I hadnt seen 2 months ago (back then when I had set up the axum template with tailwind, etc.).

there is a button below the `<p>`. I remove the `<p>` and the button is removed in the DOM (all of this while using --hot-reload ofc). very strange.

tested with firefox and chromium.

this video shows the weird behavour: https://github.com/user-attachments/assets/cb71fe4c-bba6-478e-816a-9f25cf58d851

https://github.com/user-attachments/assets/cb71fe4c-bba6-478e-816a-9f25cf58d851

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
axum = { version = "0.7", optional = true }
console_error_panic_hook = "0.1"
leptos = { version = "0.7.0-rc0", features = ["nightly"] }
leptos_axum = { version = "0.7.0-rc0", optional = true }
leptos_meta = { version = "0.7.0-rc0" }
leptos_router = { version = "0.7.0-rc0", features = ["nightly"] }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["fs"], optional = true }
wasm-bindgen = "=0.2.93"
thiserror = "1"
tracing = { version = "0.1", optional = true }
http = "1"
```

**To Reproduce**
1. Clone the repo
2. execute `cargo leptos watch --hot-reload`
3. change something in the `App` component's view (add a `<p>' or something else)

**Expected behavior**
I expect it to insert/update the correct child/children when changing something in the HTML view

**Screenshots**
see link to discussion video above

**Additional context**
this wasn't the case 3 months ago. this is new to me.
