### ISSUE TITLE
`A` components aria-current attribute not getting set in nested routes

### ISSUE THREAD

**Issue by TERRORW0LF** [leptos-rs/leptos#3196]
**Describe the bug**
When placing links with the `A` component inside a nested route the aria-current attribute does not get set on client side navigation.

**Leptos Dependencies**
```toml
leptos = { version = "0.7.0-rc1", features = ["nightly"] }
leptos_axum = { version = "0.7.0-rc1", optional = true }
leptos_meta = { version = "0.7.0-rc1" }
leptos_router = { version = "0.7.0-rc1", features = ["nightly"] }
```

**To Reproduce**
1. Set up the router example in an start-axum-0.7 template (remove tracing and futures)
2. Remove routing progress (causes bugs which alter this one)
3. Run `cargo leptos watch`
4. Open the site and navigate to a contact
5. Open the browser's inspector and select the contact's `a` tag
6. The `aria-current="page"` attribute is not there

**Expected behavior**
The `aria-current="page"` attribute gets applied to the `a` tag of the current contact
