### ISSUE TITLE
No navigation to nested route when using RoutingProgress

### ISSUE THREAD

**Issue by TERRORW0LF** [leptos-rs/leptos#3197]
**Describe the bug**
When navigating to a nested route neither the browser's url nor the page get updated when using a RoutingProgress in the app.
Clicking the link to the nested route again displays the correct page.
The same thing happens on the first navigation inside the nested route.

**Leptos Dependencies**
```toml
leptos = { version = "0.7.0-rc1", features = ["nightly"] }
leptos_axum = { version = "0.7.0-rc1", optional = true }
leptos_meta = { version = "0.7.0-rc1" }
leptos_router = { version = "0.7.0-rc1", features = ["nightly"] }
```

**To Reproduce**
1. Set up the router example in an start-axum-0.7 template (remove tracing and futures)
3. Run `cargo leptos watch`
4. Open the site and navigate to the `about` section
5. Navigate to the `contact` section
6. The browser still displays the about section and the RoutingProgress progress bar is stuck at fully completed

**Expected behavior**
The navigation to the nested route completes after the first link click.
