### ISSUE TITLE
No browser navigation to Routes fallback

### ISSUE THREAD

**Issue by TERRORW0LF** [leptos-rs/leptos#3199]
**Describe the bug**
When navigating to a page that doesn't exist (via links in the app) the fallback gets displayed, however the browser's url is still on the old page. Clicking the link again (requires that its displayed in the fallback) sets the url to the correct page.

**Leptos Dependencies**
```toml
leptos = { version = "0.7.0-rc1", features = ["nightly"] }
leptos_axum = { version = "0.7.0-rc1", optional = true }
leptos_meta = { version = "0.7.0-rc1" }
leptos_router = { version = "0.7.0-rc1", features = ["nightly"] }
```

**To Reproduce**
1. Set up the router example in an start-axum-0.7 template (remove tracing and futures)
2. Remove ContactRoutes
3. Run `cargo leptos watch`
4. Open the site and navigate to the `about` section
6. Navigate to the `contact` section
7. The browser displays the fallback however the url is till pointing to the `about` page

**Expected behavior**
The navigation to a non-existent route sets the url in the browser.
