### ISSUE TITLE
[0.7] Incorrect Vec in Suspend or For

### ISSUE THREAD

**Issue by und3fined** [leptos-rs/leptos#3222]
**Describe the bug**

I has `server` fn load data from D1, try run `cargo leptos build`. But leptos always got as non-vec.

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0-rc1", features = ["experimental-islands"] }
leptos_axum = { version = "0.7.0-rc1", default-features = false, features = [
  "wasm",
], optional = true }
leptos_meta = "0.7.0-rc1"
leptos_router = { version = "0.7.0-rc1" }
leptos_dom = "0.7.0-rc1"
leptos_config = "0.7.0-rc1"
```

<img width="952" alt="Screenshot 2024-11-10 at 12 43 51" src="https://github.com/user-attachments/assets/541d0376-bf0d-4657-b431-ddabb4a2b180">
