### ISSUE TITLE
Intermediate memo does not recompute

### ISSUE THREAD

**Issue by stefnotch** [leptos-rs/leptos#3252]
**Describe the bug**
I have set up a reactive graph with "source => memo 1 => memo 2" and "memo1, memo2 => effect". When I change the source, then the first memo gets recomputed, the effect gets updated, *but the second memo stays the same*.

```rust
use any_spawner::Executor;
use reactive_graph::{
    computed::Memo,
    effect::Effect,
    owner::Owner,
    signal::RwSignal,
    traits::{Get, Read, Set},
};

fn main() {
    Executor::init_futures_executor().unwrap();
    let _owner = Owner::new();
    let source = RwSignal::new(0);

    let directly_derived = Memo::new_with_compare(move |_| source.get(), |_, _| true);
    let indirect = Memo::new_with_compare(move |_| directly_derived.get(), |_, _| true);

    Effect::new(move |_| {
        let direct_value = directly_derived.read(); // <!!!=== This seems to break it
        let indirect_value = indirect.get();
        println!(
            "After rerunning the effect effect {:?} ?= {:?} (memo should have been recomputed ^^^)",
            *direct_value, indirect_value
        );
    });

    Executor::poll_local();
    source.set(1);
    Executor::poll_local();
    source.set(2);
    Executor::poll_local();
}
```

**Leptos Dependencies**
```toml
[dependencies]
any_spawner = { version = "0.1.1", features = [
    "wasm-bindgen",
    "futures-executor",
] }
reactive_graph = { version = "0.1.0-rc1", features = ["effects"] }
wasm-bindgen = "0.2.95"
web-sys = { version = "0.3.72", features = ["console"] }

[patch.crates-io]
any_spawner = { git = "https://github.com/leptos-rs/leptos", branch = "main" }

```

**To Reproduce**
1. Run the script above
2. It prints
```
After rerunning the effect effect 0 ?= 0 (memo should have been recomputed ^^^)
After rerunning the effect effect 1 ?= 0 (memo should have been recomputed ^^^)
After rerunning the effect effect 2 ?= 0 (memo should have been recomputed ^^^)
```

**Expected behavior**
It should have printed
```

After rerunning the effect effect 0 ?= 0 (memo should have been recomputed ^^^)
After rerunning the effect effect 1 ?= 1 (memo should have been recomputed ^^^)
After rerunning the effect effect 2 ?= 2 (memo should have been recomputed ^^^)
```

**Additional context**

I also have a demo project that can run in a browser environment 
[leptos-testos.zip](https://github.com/user-attachments/files/17791721/leptos-testos.zip)

The demo project can also be run in a browser environment by doing
```
npm install
npm run build
```
and then serving `index.html` with a HTTP server and opening it in a browser.
I originally thought that it was a wasm-bindgen-futures specific bug, but it turned out that I just didn't manage to properly reproduce it on desktop.
