### ISSUE TITLE
`prevent_default()` doesn't stop `<a>` tags from navigating

### ISSUE THREAD

**Issue by BrandonDyer64** [leptos-rs/leptos#3256]
**Describe the bug**

When using `prevent_default()` on a click event on an `<a>` tag, the browser still navigates. Doing the same in JavaScript does not navigate. Perhaps I'm missing something, but isn't this wrong?

Minimum reproducible example:

```rust
view! {
    // calling ev.prevent_default() should stop the browser from navigating, but it doesn't.
    <a href="/something" on:click=|ev| ev.prevent_default()>
        "Doesn't work"
    </a>
    
    // Doing the same thing, but calling `preventDefault()` from JavaScript successfully stops browser from navigating.
    <a href="/something" id="special-link">
        "Does work"
    </a>
    <script>
        r#"
        document.getElementById("special-link").addEventListener('click', function (event) {
            event.preventDefault();
        })
        "#
    </script>
}
```

If this is expected behavior, how does one stop an `<a>` tag from navigating while preserving the `href` value for graceful degradation?

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = "0.6.14"
leptos_axum = { version = "0.6", default-features = false, features = [
  "wasm",
], optional = true }
leptos_meta = "0.6.14"
leptos_router = "0.6.14"
leptos_dom = "0.6.14"
```

**Additional context**
I want to make an API call when a button is pressed, but I want to handle JavaScript being disabled. My thought was to use an `<a>` tag with an `on:click` to handle the call and have `href` as a backup.
