### ISSUE TITLE
[0.7] Order of class dynamic attribute

### ISSUE THREAD

**Issue by arnaudpoullet-dkt** [leptos-rs/leptos#3296]
**Describe the bug**
Similar to my previous [issue](https://github.com/leptos-rs/leptos/issues/2982), the order of classes here seem to be important while it should not

**Leptos Dependencies**
```toml
leptos = { version = "=0.7.0-rc2", features = ["csr"] }
leptos_meta = { version = "=0.7.0-rc2" }
leptos_router = { version = "=0.7.0-rc2" }
reactive_graph = "=0.1.0-rc2"
leptos_config = "=0.7.0-rc2"
tachys = "=0.1.0-rc2"
server_fn = "=0.7.0-rc2"
leptos_server = "=0.7.0-rc2"
leptos_dom = "=0.7.0-rc2"
leptos_hot_reload = "=0.7.0-rc2"
leptos_macro = "=0.7.0-rc2"
leptos_router_macro = "=0.7.0-rc2"
server_fn_macro = "=0.7.0-rc2"
```

**To Reproduce**
```
use leptos::prelude::*;
use leptos::IntoView;
use leptos_macro::component;
use reactive_graph::signal::RwSignal;

#[component]
pub fn Section() -> impl IntoView {
    let hide_section = RwSignal::new(true);

    view! {
        <div class={move || if hide_section.get() {"pt-2 border-t-2 border-gray-900/10"} else { "p-4 bg-white rounded-md" }}>
            <div on:click=move |_| hide_section.update(|b| *b = !*b) class=("bg-red-600",move || hide_section.get()) class="flex items-start justify-between text-left text-gray-900 hover:cursor-pointer">
                <h3 class="text-lg font-semibold leading-5 py-2">"Section "</h3>
                <span class="ml-6 flex h-7 items-center">
                    <svg class="h-6 w-6" class:hidden=move || !hide_section.get() fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v12m6-6H6" />
                    </svg>
                </span>
            </div>
            <div class="my-2" class:hidden=move || hide_section.get()>
                <p><span class="font-medium">HIDDEN</span></p>
            </div>
        </div>
    }
}
```
**Expected behavior**
The initial state of the div should have a class `bg-red-600` i.e. the same behaviour as:
`<div on:click=move |_| hide_section.update(|b| *b = !*b) class="flex items-start justify-between text-left text-gray-900 hover:cursor-pointer" class=("bg-red-600",move || hide_section.get())>`
which works.

**Screenshots**
![image](https://github.com/user-attachments/assets/2304f990-911f-4fed-98ad-098f58b3a068)

**Additional context**
It does have the nice side-effect of showing which sections you have already expanded, but that result can be obtained by other means as well
