### ISSUE TITLE
+62 838-9911-7560

### ISSUE THREAD

**Issue by Bahri12344** [leptos-rs/leptos#3316]
**Describe the bug**

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.3", features = ["serde"] }
leptos_axum = { version = "0.3", optional = true }
leptos_meta = { version = "0.3"}
leptos_router = { version = "0.3"}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
