### ISSUE TITLE
Cannot add `id` attribute to an ActionForm

### ISSUE THREAD

**Issue by mpalmer** [leptos-rs/leptos#3367]
**Describe the bug**

In Leptos 0.6, I was able to add an `id` attribute to an `ActionForm` like this:

```rust
<ActionForm action=submit_password  attributes=vec![("id", "password-form".into_attribute())]>
```

Now, I'm upgrading to Leptos 0.7, and while I've mostly been able to make the conversion with the help of the release notes (they're really great, thankyou), compiler hints, and the occasional docs search, I cannot for the life of me find a way to add back my `id`.  It seems that the `GlobalAttributes` doesn't apply to components (which makes sense in general), so that's not working.  The `attributes` prop got removed in [this giant cleanup commit](https://github.com/leptos-rs/leptos/commit/9666c9c0c53e55bc4a76806e5972f3c441e3ac51#diff-6edbb281543fc38e436f246c07e6d225c8fddfc49b6cf2e05dfbac26f9e5b5dd), which unfortunately doesn't give me a hint as to what the new approach might be.  I feel like it might have _something_ to do with `node_ref`, but I'm unfamiliar with that concept, and I'm not able to figure it out from the docs.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.7" }
leptos_actix = { version = "0.7" }
leptos_meta = { version = "0.7" }
leptos_router = { version = "0.7" }
```
