### ISSUE TITLE
Wasm-bindgen version conflict (Leptos 0.7.3)

### ISSUE THREAD

**Issue by czyrok** [leptos-rs/leptos#3479]
**Describe the bug**
I started a project based on the `static_routing` example, but since Leptos 0.7.x, it doesn't compile anymore. It's the same as the example itself `static_routing`. There is an error at compile time of the front WASM. It seems like there is a conflict with the version of `wasm-bindgen` used to compile.

**Leptos Dependencies**
```toml
[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0"
leptos = { version = "0.7.3", features = [
  "hydration",
] } #"nightly", "hydration"] }
leptos_meta = { version = "0.7.3" }
leptos_axum = { version = "0.7.3", optional = true }
leptos_router = { version = "0.7.3" }
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
axum = { version = "0.7.5", optional = true }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.5.2", features = ["fs"], optional = true }
tokio = { version = "1.39", features = [
  "fs",
  "rt-multi-thread",
  "macros",
], optional = true }
tokio-stream = { version = "0.1", features = ["fs"], optional = true }
futures = "0.3"
notify = { version = "6", optional = true }
http = { version = "1", optional = true }
wasm-bindgen = "0.2.93"

[features]
hydrate = ["leptos/hydrate"]
ssr = [
  "dep:axum",
  "dep:tower",
  "dep:tower-http",
  "dep:tokio",
  "dep:tokio-stream",
  "leptos/ssr",
  "leptos_meta/ssr",
  "dep:leptos_axum",
  "leptos_router/ssr",
  "dep:notify",
  "dep:http",
]
```

**To Reproduce**
1. Download [Leptos 0.7.3 tag](https://github.com/leptos-rs/leptos/releases/tag/v0.7.3)
2. Go to the `static_routing` folder
3. Do `cargo make start`
4. See the error (refer you to the `screenshots` section)

**Expected behavior**
It should start the web server and exposing the front and the server API used by hydration.

**Screenshots**
![image](https://github.com/user-attachments/assets/ecb95887-f883-46a5-9b2b-9b3e9f0b4a3c)

**Additional context**
