### ISSUE TITLE
Islands wreak havoc on Flexbox Layouts

### ISSUE THREAD

**Issue by cowboyai** [leptos-rs/leptos#3514]
**Describe the bug**
I have a Flexbox layout in CSS with 5 containers. It works great with 100% #[components]. If I make any of the containers an #[island], the added ```<leptos-island>``` and ```<leptos-children>``` completely break the Flexbox.

I have tried several ways to ignore those elements, but I have no clean solution, at least for complex Flexbox layouts with things like sizable containers and growing elements.

**To Reproduce**
1. change any CSS display:flex; with a flex:1 child  enabled #[component] to #[island]

**Expected behavior**
The same Flexbox behavior...

**Additional context**

I'm sort of writing this off to a design issue (on my part) and if I assemble Islands and CSS correctly it won't do this... but I don't see anything mentioning this yet.

Consider the Holy Grail Layout:
[             1               ]
[  2  ][     3       ][  4  ]
[             5               ]

This is somewhat finicky about setting up right in css.

is that 5 islands since they can all change independently?
Mostly 3 change based on interaction in the other areas.

This is a confusing layout to achieve with Islands, but seems the appropriate way.

1 header_w_login
2 nav
3 main_page
4 context_links
5 footer

I currently have them as 5 components and want to understand the proper architecture to achieve this... Do I make a shell aka Home Page that has the 5 containers... then inside the containers, put an Island?

Content is getting fed from SSR which attaches to server side stuff.

I preferably just do this:
```rust
    view! {
          <Header/>
          <div id="main">
            <Article/>
            <Nav/>
            <Aside/>
          </div>
          <Footer/>
    }
```
as they all have defaults.
header and footer are fine as components, they only change on initial page load...
Article, Nav, Aside all are interactive, so maybe just 3 islands.

Where do I put the CSS, attach it to the Island so it overrides the base page?
I'm ok with that as long as it's just sass files and not turn my css into code.

Did I miss something in the Docs?

**Comment by cowboyai** [comment]
```css/* Flexbox */
header {
	display: flex;
	flex-direction: row;
	margin-bottom: .25rem;
	height: 6vh;
}
#main {
	display: flex;
	gap: .25rem;
	min-height: calc(100vh - 11vh);
}
#main > article {
	flex: 1;
}
#main > nav, 
#main > aside {
	flex: 0 0 20vw;
}
#main > nav {
	order: -1;
}
footer {
	margin-top: .375rem;
	height: 3vh;
}
```

**Comment by gbj** [comment]
```css
leptos-islands, leptos-children {
    display: contents;
}
```

I'll take a second to try to reproduce.
