### ISSUE TITLE
Component definition silently dropped

### ISSUE THREAD

**Issue by iradicek** [leptos-rs/leptos#3535]
**Describe the bug**

Define the following component (notice the missing `impl`):

```rust
#[component]
pub fn MyComponent(callback: Fn()) -> impl IntoView {

}
```

**Leptos Dependencies**

```toml
leptos = { version = "0.7.5" }
leptos_meta = { version = "0.7.5" }
leptos_router = { version = "0.7.5" }
leptos_axum = { version = "0.7.5" }
```

**To Reproduce**

Try to use the component and it's actually not defined. Also in VS Code if you try to expand macro it shows nothing. It seems like macro silently drops everything and produces no code.

**Expected behavior**

Report the error - missing `impl`.
