### ISSUE TITLE
Isomorphic Effects don't run on the server

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#3560]
**Describe the bug**
`Effect:new_isomorphic()` used to run the effect both on the server and on the client. It also used to run the effect immediately. Currently, it seems to be just the same as `Effect:new()`.

**Leptos Dependencies**

git rev = c6de7c714ea8f4022798afa2a56df336a844cc93

```toml
[patch.crates-io]
leptos = { git = "https://github.com/leptos-rs/leptos.git" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git" }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git" }
leptos_actix = { git = "https://github.com/leptos-rs/leptos.git" }
reactive_graph = { git = "https://github.com/leptos-rs/leptos.git" }
```

**To Reproduce**

```rs
#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    let title = RwSignal::new("Initial title".to_string());

    provide_context(TitleContext { title });

    view! {
        // injects a stylesheet into the document <head>
        // id=leptos means cargo-leptos will hot-reload this stylesheet
        <Stylesheet id="leptos" href="/pkg/leptos-test.css"/>

        // sets the document title
        <Title text=title/>

        // content for this welcome page
        <Router>
            <main>
                <Routes fallback=move || "Not found.">
                    <Route path=StaticSegment("") view=HomePage />
                    <Route path=WildcardSegment("any") view=NotFound/>
                </Routes>
            </main>
        </Router>
    }
}

#[component]
fn HomePage() -> impl IntoView {
    let title = expect_context::<TitleContext>().title;
    let head = use_head();

    title.set("Home page".to_string());

    let contents = RwSignal::new("Home page contents".to_string());

    Effect::new_isomorphic(move || {
        logging::log!("Server effect"); // This log message is not printed on the server
        title.set("Home page".to_string());
        contents.set("New contents".to_string());
    });

    view! {
        <div>{contents}</div>
    }
}
```

**Expected behavior**
Expected isomorphic effects to also run on server side code.
