### ISSUE TITLE
Hydration error when rendering `Vec<AnyView>` between Text Nodes.

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#3583]
**Describe the bug**
When rendering a `Vec<AnyView>` that returns a text node or that is an empty vec in between 2 other text nodes, there will be a hydration panic.

```
A hydration error occurred while trying to hydrate an element defined at src\app.rs:80:10.

The framework expected a text node, but found this instead:  
<!--  -->
```
 
This does not happen if it's only surrounded by one text node (and possibly an HTML element on the other side), or when the view inside the vec returns other HTML elements.

**Leptos Dependencies**
```toml
[patch.crates-io]
leptos = { git = "https://github.com/leptos-rs/leptos.git", rev = "b17a4c92c745271dba947412bf14b6e0ece1270f" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git", rev = "b17a4c92c745271dba947412bf14b6e0ece1270f" }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", rev = "b17a4c92c745271dba947412bf14b6e0ece1270f" }
leptos_actix = { git = "https://github.com/leptos-rs/leptos.git", rev = "b17a4c92c745271dba947412bf14b6e0ece1270f" }
reactive_graph = { git = "https://github.com/leptos-rs/leptos.git", rev = "b17a4c92c745271dba947412bf14b6e0ece1270f" }
```

**To Reproduce**
```rs
#[component]
fn HomePage() -> impl IntoView {
    // let elements: Vec<AnyView> = vec![]; // <- Empty vec will also reproduce the issue.
    let elements: Vec<AnyView> = vec![view! {
        "hello"
    }
    .into_any()];

    view! {
        <span class="italic">
            "Any text" {elements} "other text"
        </span>
    }
}
```

**Expected behavior**
Not panic

**Additional context**
I want to render a text node inside parentheses as part of a specific markup parser. Currently working around the issue by creating additional `<span>` tags.

```rs
fn into_render(self) -> Self::Output {
        match self {
            MarkupElement::Text(text) => text.into_any(),
            MarkupElement::Symbol(symbol) => {
                let url = symbol.svg_url();
                view! {
                    <img class="cost-symbol" src=url alt=symbol.to_string() />
                }
                .into_any()
            }
            MarkupElement::Italic(elements) => {
                let elements = elements
                    .into_iter()
                    .map(IntoRender::into_render)
                    .collect_view();

                view! {
                    <span class="italic">
                        "("{elements}")"
                    </span>
                }
                .into_any()
            }
        }
    }
```
