### ISSUE TITLE
Users first navigation on `<a>` tag does not update URL if inside `<ParentRoute>` without `<Outlet />`

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#3605]
**Describe the bug**
Using the example code below, the first navigation of the user is ignored. All subsequent navigations work fine however. Also, the `navigate` function appears to be working fine too. It works if I declare an `<Outlet />` component, however, see "Additional Context" for why this is not always desirable.

**Leptos Dependencies**
```toml
[patch.crates-io]
leptos = { git = "https://github.com/leptos-rs/leptos.git", rev = "590728e47e99c0f932cb39abf6c30807c30e5126" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git", rev = "590728e47e99c0f932cb39abf6c30807c30e5126" }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", rev = "590728e47e99c0f932cb39abf6c30807c30e5126" }
leptos_actix = { git = "https://github.com/leptos-rs/leptos.git", rev = "590728e47e99c0f932cb39abf6c30807c30e5126" }
reactive_graph = { git = "https://github.com/leptos-rs/leptos.git", rev = "590728e47e99c0f932cb39abf6c30807c30e5126" }
```

**To Reproduce**
```html
<Router>
    <main>
        <ul>
            <li><a href="/">"Main"</a></li>
            <li><a href="/collection">"Collection"</a></li>
            <li><a href="/other">"Other"</a></li>
        </ul>
        <Routes fallback=move || "Not found.">
            <ParentRoute path=StaticSegment("") view=|| ()>
                <Route path=StaticSegment("") view=|| () />
                <Route path=StaticSegment("collection") view=|| () />
                <Route path=StaticSegment("other") view=|| () />
            </ParentRoute>
            <Route path=WildcardSegment("any") view=NotFound/>
        </Routes>
    </main>
</Router>
```

**Expected behavior**
When the user clicks on the link, they should navigate to the page.

**Additional context**
My Application is largely ignoring leptos-router: I only use the router for the actual routing behavior, but I render all of the components manually based on a `use_location` trigger. I do this because some bits of my application are using a routing scheme that does not fit well into the traditional routing behavior (or nested routing behavior) of a web page. As it is more an App than a pure web page, it has some application states mapped to specific routes. For example, my home route ("/") and my "/search" route are the same page; their only difference is that the user has entered something in the search box presented on the front page, and accordingly, search results are being displayed.
Because `use_location` didn't work outside of a route in 0.6 (probably still doesn't in 0.7 although I haven't tested yet), I have my entire application inside the `view` on a `<ParentRoute>`. The route elements inside of that ParentRoute are all `view=|| ()` as all the actual displaying of the content is done by manually parsing the URL in a Memo via `use_location()` and then using that information in various components to alter their content.
