### ISSUE TITLE
Router fails when a query parameter contains an encoded percent character

### ISSUE THREAD

**Issue by NikosChondros** [leptos-rs/leptos#3606]
When inputting a percent character at a <Form>, the router throws a panic.
Looks like an issue processing the encoded percent character at the query parameters of the URL.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.7.7", features = ["csr"] }
leptos_router = { version = "0.7.7" }
console_error_panic_hook = "0.1.7"
either_of = "0.1.5"
```

**To Reproduce**
1. Go to 'https://codesandbox.io/p/devbox/20-form-0-7-m73jsz'
2. Input a percent character in the first textbox of the preview window
3. Hit submit
4. See error in console and a blank page

**Expected behavior**
Should successfully load the next page.

**Screenshots**

<img width="1249" alt="Image" src="https://github.com/user-attachments/assets/2fffc503-c988-4134-8c55-2bd786b5a006" />

**Additional context**
