### ISSUE TITLE
Path pattern match panic

### ISSUE THREAD

**Issue by ThatBigDerp** [leptos-rs/leptos#3608]
**Describe the bug**
When I try matching path to route (using wildcard) it panics while parsing regex
**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos_actix = { version = "0.7.7", optional = true }

leptos = { version = "0.7.7", features = ["nightly", "islands"] } + ssr + hydrate
leptos_meta = "0.7.7" + ssr
leptos_router = { version = "0.7.7", features = ["nightly"] } +ssr
```

**To Reproduce**
Create Router with path being WIldcardSegment.

**Expected behavior**
It doesn't panic

**Additional context**
Here is part of the code in particular:
```rust
#[cfg(feature = "ssr")]
pub fn shell(options: LeptosOptions) -> impl IntoView {
    let formatter = |text| format!("Formatted title: {text}");
    provide_meta_context();
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <MetaTags/>
                <AutoReload options=options.clone() />
                <HydrationScripts options islands=true/>
                <Title formatter/>
                <Stylesheet id="leptos" href="/pkg//style.css"/>

            </head>
            <body>
                <App/>
            </body>
        </html>
    }
}



#[component]
pub fn App() -> impl IntoView {
    view! {
        <Title text="Test" />
        <Router>
        <main>
            <Routes fallback=|| "Page not found.".into_view()>
                <Route path=path!("") view=HomePage/>
                <Route path=path!("/*any") view=NotFound/>
            </Routes>
        </main>
        </Router>
   }
}


```
