### ISSUE TITLE
Tailwind starter has some issues updating vs. CSS

### ISSUE THREAD

**Issue by jordaniza** [leptos-rs/leptos#361]
Hi all.

Enjoyed using Leptos over the weekend. This is a great utility and I've committed to building a simple app with a friend of mine using the framework to really test drive it. 

I wanted to share a bit of feedback regarding the tailwind starter provided in the examples, wondering if anyone has similar experiences and can share any suggestions.

## Environment

OS: Linux Pop!_OS (Ubuntu 22.04 LTS)
rustup 1.25.1 (bb60b1e89 2022-07-12)
cargo 1.68.0-nightly (985d561f0 2023-01-20)
cargo-leptos 0.1.3
leptos = { version = "0.1.1", default-features = false, features = [
  "serde",
] }
Browser: Brave

## Problem

In general, I'm finding the starter works as expected. However, I'm finding after a while, the generated HTML does not reflect the changes I have made in my view macros. 

For example, I might set:

```jsx
 view! { cx,
        <div class="w-full px-5">
            <h1
                class="
                text-xl
                text-center 
            "
            >"Hi! My name is Chad"</h1>
        </div>
}
```

Then try and add `italic` to the `h1` element.

*Mostly* this works but *sometimes* it doesn't. If it doesn't, then when I check the markup on the browser I can see the `italic` class doesn't get added to the h1 element. 

What is weird is that, if I make the change instead to my `input.css` file with `font-style: italic`, the view will update every time. Browser cache is disabled, so I know it's not that.

This leads me to suspect there is something off with my tailwind setup. 

I see no errors in the console for `npx tailwindcss ...` , but in the `cargo leptos watch` terminal I do often see `Error could not send product changes due to channel closed`, which may or may not be related.

### Setup

My setup is largely copied from the tailwind starter, with the following changes:

1. Changed `Cargo.toml` to fetch crates instead of using path imports:
```toml
leptos = { version = " 0.1.1", default-features = false, features = [
  "serde",
] }
leptos_actix = {  version = " 0.1.1", optional = true }
leptos_meta =   { version = " 0.1.1", default-features = false }
leptos_router = { version = " 0.1.1", default-features = false }
```

2. Added recommended VS Code settings:
```json
{
    "emmet.includeLanguages": {
        "rust": "html",
        "*.rs": "html"
      },
      "tailwindCSS.includeLanguages": {
          "rust": "html",
          "*.rs": "html"
      },
      "files.associations": {
          "*.rs": "rust"
      },
      "editor.quickSuggestions": {
        "other": "on",
        "comments": "on",
        "strings": true
      },
      "css.validate": false
}
```

**Comment by jordaniza** [comment]
@martinfrances107 thanks for replying. Is that what's happening here though? I used the h1 as an example but the same problems are apparent when trying to adjust styles for other elements like divs. I think it's an issue with the tailwind classes not consistently updating, rather than the tailwind presets

**Comment by martinfrances107** [comment]
>Is that what's happening here though? 

Yes, here is my arguments in detail so you can pick holes in it.

When look at the output.css files generated by following the leptos/example/tailwind application

```css
/*
Remove the default font size and weight for headings.
*/

h1,
h2,
h3,
h4,
h5,
h6 {
  font-size: inherit;
  font-weight: inherit;
}
```

This has really high "CSS" specificity in your example this code block is overriding the applied class specification of "text-xl"

This is a patterns that I put at the end of my input.css files, which allow me to set the height of the <H1> elements
on a application wide basis.. ( h1 sizing on a component basis is banned in tailwind )

```
@layer base {
  h1 {
    @apply text-4xl;
  }

  h2 {
    @apply text-xl;
  }

}
```

I hope this helps
