### ISSUE TITLE
Numerous mio errors using Leptos example 'todo_app_sqlite_axum'

### ISSUE THREAD

**Issue by MatthewRalston** [leptos-rs/leptos#3625]
**Describe the bug**
I have downloaded Leptos 0.7.4 and have copied the example 'todo_app_sqlite_axum'. I am trying to follow along with the axum by slowly adding new features like oauth2. 

Rustup 1.27.1
rustc 1.84.1

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

Cargo.toml
```toml
[package]
name = "leptos_template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
# Web framework
axum = { version = "0.7.5", optional = true }
http = "1.1"

# Async utilities
futures = "0.3.30"
tokio = { version = "1.39", features = ["full"], optional = true }

# Leptos for SSR
leptos = { version = "0.7", features = ["ssr", "tracing"] }
leptos_axum = { version = "0.7", optional=true }

# Logging and tracing
log = "0.4"
tracing = { version = "0.1", optional = true }

# OAuth2 authentication
oauth2 = { version = "5" }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }

# Tower middleware
tower = { version = "0.4", optional = true }
tower-http = { version = "0.5", features = ["full"], optional = true }

# Database support (SQLx)
sqlx = { version = "0.8.3", features = ["sqlite", "postgres", "runtime-tokio-rustls"], optional = true } # "tls-native-tls"

# Error handling
thiserror = "1.0"
leptos_router = "0.7.7"
leptos_meta = "0.7.7"

[dev-dependencies]
# Enables dotenv for environment variable management in development
dotenvy = "0.15"

[features]
hydrate = ["leptos/hydrate"]
ssr = [
  "dep:axum",
  "dep:leptos_axum",
  "dep:tokio",
  "dep:tower",
  "dep:tower-http",
  "dep:sqlx",
  "leptos/ssr",
  "dep:leptos_axum",
  "dep:tracing",
]


[profile.release]
opt-level = 3

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = "leptos_template"
# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/site"
# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg
site-pkg-dir = "pkg"
# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into CSS. The CSS is optimized by Lightning CSS before being written to <site-root>/<site-pkg>/app.css
style-file = "./style.css"
# [Optional] Files in the asset-dir will be copied to the site-root directory
assets-dir = "public"
# The IP and port (ex: 127.0.0.1:3000) where the server serves the content. Use it in your server setup.
site-addr = "127.0.0.1:3000"
# The port to use for automatic reload monitoring
reload-port = 3001
# [Optional] Command to use when running end2end tests. It will run in the end2end dir.
end2end-cmd = "cargo make test-ui"
end2end-dir = "e2e"
#  The browserlist query used for optimizing the CSS.
browserquery = "defaults"
# Set by cargo-leptos watch when building with that tool. Controls whether autoreload JS will be included in the head
watch = false
# The environment Leptos will run in, usually either "DEV" or "PROD"
env = "DEV"
# The features to use when compiling the bin target
#
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]

# If the --no-default-features flag should be used when compiling the bin target
#
# Optional. Defaults to false.
bin-default-features = false

# The features to use when compiling the lib target
#
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
#
# Optional. Defaults to false.
lib-default-features = false


```

**To Reproduce**
```bash
cargo leptos watch
```

**Expected behavior**
I would like to run the leptos example without encountering a zillion `mio` crate errors.

**Screenshots**

```bash
[matt@Dend3] git:main*+ <~/repos/leptos_template>>cargo leptos serve --features ssr
  Downloaded leptos_axum v0.7.7
  Downloaded async-compression v0.4.18
  Downloaded leptos_integration_utils v0.7.7
  Downloaded iri-string v0.7.7
  Downloaded 4 crates (300.0 KB) in 0.46s
   Compiling shlex v1.3.0
   Compiling futures-io v0.3.31
   Compiling mio v1.0.3
   Compiling serde_json v1.0.138
   Compiling allocator-api2 v0.2.21
   Compiling foldhash v0.1.4
   Compiling pkg-config v0.3.31
   Compiling stable_deref_trait v1.2.0
   Compiling serde v1.0.217
   Compiling num-traits v0.2.19
   Compiling typenum v1.17.0
   Compiling writeable v0.5.5
   Compiling litemap v0.7.4
   Compiling rustls v0.23.23
   Compiling tower-layer v0.3.3
   Compiling mime v0.3.17
error[E0432]: unresolved import `crate::sys::IoSourceState`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:14:5
   |
14 | use crate::sys::IoSourceState;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`

error[E0432]: unresolved import `crate::sys::tcp`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:19:17
   |
19 | use crate::sys::tcp::{bind, listen, new_for_addr};
   |                 ^^^ could not find `tcp` in `sys`

error[E0432]: unresolved import `crate::sys::tcp`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/stream.rs:17:17
   |
17 | use crate::sys::tcp::{connect, new_for_addr};
   |                 ^^^ could not find `tcp` in `sys`

error[E0433]: failed to resolve: could not find `Selector` in `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/poll.rs:322:18
    |
322 |             sys::Selector::new().map(|selector| Poll {
    |                  ^^^^^^^^ could not find `Selector` in `sys`

error[E0433]: failed to resolve: could not find `event` in `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:24:14
   |
24 |         sys::event::token(&self.inner)
   |              ^^^^^ could not find `event` in `sys`

error[E0433]: failed to resolve: could not find `event` in `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:38:14
   |
38 |         sys::event::is_readable(&self.inner)
   |              ^^^^^ could not find `event` in `sys`

error[E0433]: failed to resolve: could not find `event` in `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:43:14
   |
43 |         sys::event::is_writable(&self.inner)
   |              ^^^^^ could not find `event` in `sys`

error[E0433]: failed to resolve: could not find `event` in `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:68:14
   |
68 |         sys::event::is_error(&self.inner)
   |              ^^^^^ could not find `event` in `sys`

error[E0433]: failed to resolve: could not find `event` in `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:99:14
   |
99 |         sys::event::is_read_closed(&self.inner)
   |              ^^^^^ could not find `event` in `sys`

   Compiling http-body v1.0.1
   Compiling generic-array v0.14.7
   Compiling httparse v1.10.0
   Compiling icu_locid_transform_data v1.5.0
   Compiling byteorder v1.5.0
   Compiling futures-core v0.3.31
   Compiling subtle v2.6.1
   Compiling httpdate v1.0.3
error[E0433]: failed to resolve: could not find `event` in `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:129:14
    |
129 |         sys::event::is_write_closed(&self.inner)
    |              ^^^^^ could not find `event` in `sys`

error[E0433]: failed to resolve: could not find `event` in `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:151:14
    |
151 |         sys::event::is_priority(&self.inner)
    |              ^^^^^ could not find `event` in `sys`

error[E0433]: failed to resolve: could not find `event` in `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:173:14
    |
173 |         sys::event::is_aio(&self.inner)
    |              ^^^^^ could not find `event` in `sys`

error[E0433]: failed to resolve: could not find `event` in `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:183:14
    |
183 |         sys::event::is_lio(&self.inner)
    |              ^^^^^ could not find `event` in `sys`

error[E0433]: failed to resolve: could not find `event` in `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:221:26
    |
221 |                     sys::event::debug_details(f, self.0)
    |                          ^^^^^ could not find `event` in `sys`

error[E0433]: failed to resolve: could not find `tcp` in `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:107:18
    |
107 |             sys::tcp::accept(inner).map(|(stream, addr)| (TcpStream::from_std(stream), addr))
    |                  ^^^ could not find `tcp` in `sys`

error[E0433]: failed to resolve: could not find `udp` in `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/udp.rs:126:14
    |
126 |         sys::udp::bind(addr).map(UdpSocket::from_std)
    |              ^^^ could not find `udp` in `sys`

error[E0433]: failed to resolve: could not find `udp` in `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/udp.rs:548:14
    |
548 |         sys::udp::only_v6(&self.inner)
    |              ^^^ could not find `udp` in `sys`

error[E0412]: cannot find type `Selector` in module `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/poll.rs:273:20
    |
273 |     selector: sys::Selector,
    |                    ^^^^^^^^ not found in `sys`

error[E0412]: cannot find type `Selector` in module `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/poll.rs:730:44
    |
730 |     pub(crate) fn selector(&self) -> &sys::Selector {
    |                                            ^^^^^^^^ not found in `sys`

error[E0412]: cannot find type `Waker` in module `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/waker.rs:79:17
   |
79 |     inner: sys::Waker,
   |                 ^^^^^ not found in `sys`
   |
help: consider importing one of these structs
   |
1  + use crate::Waker;
   |
1  + use std::task::Waker;
   |
help: if you import `Waker`, refer to it directly
   |
79 -     inner: sys::Waker,
79 +     inner: Waker,
   |

error[E0433]: failed to resolve: could not find `Waker` in `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/waker.rs:87:14
   |
87 |         sys::Waker::new(registry.selector(), token).map(|inner| Waker { inner })
   |              ^^^^^ could not find `Waker` in `sys`
   |
help: consider importing one of these structs
   |
1  + use crate::Waker;
   |
1  + use std::task::Waker;
   |
help: if you import `Waker`, refer to it directly
   |
87 -         sys::Waker::new(registry.selector(), token).map(|inner| Waker { inner })
87 +         Waker::new(registry.selector(), token).map(|inner| Waker { inner })
   |

error[E0412]: cannot find type `Event` in module `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:18:17
   |
18 |     inner: sys::Event,
   |                 ^^^^^ not found in `sys`
   |
help: consider importing this struct through its public re-export
   |
1  + use crate::event::Event;
   |
help: if you import `Event`, refer to it directly
   |
18 -     inner: sys::Event,
18 +     inner: Event,
   |

error[E0412]: cannot find type `Event` in module `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:187:55
    |
187 |     pub(crate) fn from_sys_event_ref(sys_event: &sys::Event) -> &Event {
    |                                                       ^^^^^ not found in `sys`
    |
help: consider importing this struct through its public re-export
    |
1   + use crate::event::Event;
    |
help: if you import `Event`, refer to it directly
    |
187 -     pub(crate) fn from_sys_event_ref(sys_event: &sys::Event) -> &Event {
187 +     pub(crate) fn from_sys_event_ref(sys_event: &Event) -> &Event {
    |

error[E0412]: cannot find type `Event` in module `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:191:41
    |
191 |             &*(sys_event as *const sys::Event as *const Event)
    |                                         ^^^^^ not found in `sys`
    |
help: consider importing this struct through its public re-export
    |
1   + use crate::event::Event;
    |
help: if you import `Event`, refer to it directly
    |
191 -             &*(sys_event as *const sys::Event as *const Event)
191 +             &*(sys_event as *const Event as *const Event)
    |

error[E0412]: cannot find type `Event` in module `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/event.rs:217:46
    |
217 |             struct EventDetails<'a>(&'a sys::Event);
    |                                              ^^^^^ not found in `sys`
    |
help: consider importing this struct through its public re-export
    |
1   + use crate::event::Event;
    |
help: if you import `Event`, refer to it directly
    |
217 -             struct EventDetails<'a>(&'a sys::Event);
217 +             struct EventDetails<'a>(&'a Event);
    |

error[E0412]: cannot find type `Events` in module `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/events.rs:43:17
   |
43 |     inner: sys::Events,
   |                 ^^^^^^ not found in `sys`
   |
help: consider importing this struct through its public re-export
   |
1  + use crate::Events;
   |
help: if you import `Events`, refer to it directly
   |
43 -     inner: sys::Events,
43 +     inner: Events,
   |

error[E0433]: failed to resolve: could not find `Events` in `sys`
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/events.rs:94:25
   |
94 |             inner: sys::Events::with_capacity(capacity),
   |                         ^^^^^^ could not find `Events` in `sys`
   |
help: consider importing this struct through its public re-export
   |
1  + use crate::Events;
   |
help: if you import `Events`, refer to it directly
   |
94 -             inner: sys::Events::with_capacity(capacity),
94 +             inner: Events::with_capacity(capacity),
   |

error[E0412]: cannot find type `Events` in module `sys`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/events.rs:189:47
    |
189 |     pub(crate) fn sys(&mut self) -> &mut sys::Events {
    |                                               ^^^^^^ not found in `sys`
    |
help: consider importing this struct through its public re-export
    |
1   + use crate::Events;
    |
help: if you import `Events`, refer to it directly
    |
189 -     pub(crate) fn sys(&mut self) -> &mut sys::Events {
189 +     pub(crate) fn sys(&mut self) -> &mut Events {
    |

error[E0425]: cannot find value `listener` in this scope
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:78:24
   |
78 |         set_reuseaddr(&listener.inner, true)?;
   |                        ^^^^^^^^ not found in this scope

error[E0425]: cannot find value `listener` in this scope
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:80:15
   |
80 |         bind(&listener.inner, addr)?;
   |               ^^^^^^^^ not found in this scope

error[E0425]: cannot find value `listener` in this scope
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:81:17
   |
81 |         listen(&listener.inner, 1024)?;
   |                 ^^^^^^^^ not found in this scope

error[E0425]: cannot find value `listener` in this scope
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:82:12
   |
82 |         Ok(listener)
   |            ^^^^^^^^ not found in this scope

error[E0425]: cannot find value `stream` in this scope
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/stream.rs:97:18
   |
97 |         connect(&stream.inner, addr)?;
   |                  ^^^^^^ not found in this scope

error[E0425]: cannot find value `stream` in this scope
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/stream.rs:98:12
   |
98 |         Ok(stream)
   |            ^^^^^^ not found in this scope

error[E0425]: cannot find function `set_reuseaddr` in this scope
  --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:78:9
   |
78 |         set_reuseaddr(&listener.inner, true)?;
   |         ^^^^^^^^^^^^^ not found in this scope

   Compiling jobserver v0.1.32
   Compiling getrandom v0.2.15
   Compiling crossbeam-utils v0.8.21
   Compiling icu_properties_data v1.5.0
   Compiling multer v3.1.0
   Compiling vcpkg v0.2.15
   Compiling futures-sink v0.3.31
error[E0599]: no method named `register` found for struct `IoSource<std::net::TcpListener>` in the current scope
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:150:20
    |
150 |         self.inner.register(registry, token, interests)
    |                    ^^^^^^^^ method not found in `IoSource<TcpListener>`
    |
   ::: /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:37:1
    |
37  | pub struct IoSource<T> {
    | ---------------------- method `register` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Source` defines an item `register`, perhaps you need to implement it
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/source.rs:75:1
    |
75  | pub trait Source {
    | ^^^^^^^^^^^^^^^^

error[E0599]: no method named `reregister` found for struct `IoSource<std::net::TcpListener>` in the current scope
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:159:20
    |
159 |         self.inner.reregister(registry, token, interests)
    |                    ^^^^^^^^^^ method not found in `IoSource<TcpListener>`
    |
   ::: /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:37:1
    |
37  | pub struct IoSource<T> {
    | ---------------------- method `reregister` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Source` defines an item `reregister`, perhaps you need to implement it
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/source.rs:75:1
    |
75  | pub trait Source {
    | ^^^^^^^^^^^^^^^^

error[E0599]: no method named `deregister` found for struct `IoSource<std::net::TcpListener>` in the current scope
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:163:20
    |
163 |         self.inner.deregister(registry)
    |                    ^^^^^^^^^^ method not found in `IoSource<TcpListener>`
    |
   ::: /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:37:1
    |
37  | pub struct IoSource<T> {
    | ---------------------- method `deregister` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Source` defines an item `deregister`, perhaps you need to implement it
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/source.rs:75:1
    |
75  | pub trait Source {
    | ^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:286:9
    |
286 | /         unsafe {
287 | |             #[cfg(any(unix, target_os = "hermit", target_os = "wasi"))]
288 | |             {
289 | |                 net::TcpListener::from_raw_fd(listener.into_raw_fd())
...   |
294 | |             }
295 | |         }
    | |_________^ expected `TcpListener`, found `()`

error[E0599]: no method named `register` found for struct `IoSource<std::net::TcpStream>` in the current scope
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/stream.rs:332:20
    |
332 |         self.inner.register(registry, token, interests)
    |                    ^^^^^^^^ method not found in `IoSource<TcpStream>`
    |
   ::: /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:37:1
    |
37  | pub struct IoSource<T> {
    | ---------------------- method `register` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Source` defines an item `register`, perhaps you need to implement it
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/source.rs:75:1
    |
75  | pub trait Source {
    | ^^^^^^^^^^^^^^^^

error[E0599]: no method named `reregister` found for struct `IoSource<std::net::TcpStream>` in the current scope
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/stream.rs:341:20
    |
341 |         self.inner.reregister(registry, token, interests)
    |                    ^^^^^^^^^^ method not found in `IoSource<TcpStream>`
    |
   ::: /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:37:1
    |
37  | pub struct IoSource<T> {
    | ---------------------- method `reregister` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Source` defines an item `reregister`, perhaps you need to implement it
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/source.rs:75:1
    |
75  | pub trait Source {
    | ^^^^^^^^^^^^^^^^

error[E0599]: no method named `deregister` found for struct `IoSource<std::net::TcpStream>` in the current scope
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/stream.rs:345:20
    |
345 |         self.inner.deregister(registry)
    |                    ^^^^^^^^^^ method not found in `IoSource<TcpStream>`
    |
   ::: /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:37:1
    |
37  | pub struct IoSource<T> {
    | ---------------------- method `deregister` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Source` defines an item `deregister`, perhaps you need to implement it
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/source.rs:75:1
    |
75  | pub trait Source {
    | ^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/stream.rs:468:9
    |
468 | /         unsafe {
469 | |             #[cfg(any(unix, target_os = "hermit", target_os = "wasi"))]
470 | |             {
471 | |                 net::TcpStream::from_raw_fd(stream.into_raw_fd())
...   |
476 | |             }
477 | |         }
    | |_________^ expected `TcpStream`, found `()`

error[E0599]: no method named `register` found for struct `IoSource<std::net::UdpSocket>` in the current scope
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/udp.rs:626:20
    |
626 |         self.inner.register(registry, token, interests)
    |                    ^^^^^^^^ method not found in `IoSource<UdpSocket>`
    |
   ::: /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:37:1
    |
37  | pub struct IoSource<T> {
    | ---------------------- method `register` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Source` defines an item `register`, perhaps you need to implement it
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/source.rs:75:1
    |
75  | pub trait Source {
    | ^^^^^^^^^^^^^^^^

error[E0599]: no method named `reregister` found for struct `IoSource<std::net::UdpSocket>` in the current scope
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/udp.rs:635:20
    |
635 |         self.inner.reregister(registry, token, interests)
    |                    ^^^^^^^^^^ method not found in `IoSource<UdpSocket>`
    |
   ::: /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:37:1
    |
37  | pub struct IoSource<T> {
    | ---------------------- method `reregister` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Source` defines an item `reregister`, perhaps you need to implement it
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/source.rs:75:1
    |
75  | pub trait Source {
    | ^^^^^^^^^^^^^^^^

error[E0599]: no method named `deregister` found for struct `IoSource<std::net::UdpSocket>` in the current scope
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/udp.rs:639:20
    |
639 |         self.inner.deregister(registry)
    |                    ^^^^^^^^^^ method not found in `IoSource<UdpSocket>`
    |
   ::: /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:37:1
    |
37  | pub struct IoSource<T> {
    | ---------------------- method `deregister` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Source` defines an item `deregister`, perhaps you need to implement it
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/event/source.rs:75:1
    |
75  | pub trait Source {
    | ^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/udp.rs:762:9
    |
762 | /         unsafe {
763 | |             #[cfg(any(unix, target_os = "hermit", target_os = "wasi"))]
764 | |             {
765 | |                 net::UdpSocket::from_raw_fd(socket.into_raw_fd())
...   |
770 | |             }
771 | |         }
    | |_________^ expected `UdpSocket`, found `()`

   Compiling tokio-macros v2.5.0
   Compiling event-listener v5.4.0
   Compiling spin v0.9.8
Some errors have detailed explanations: E0308, E0412, E0425, E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `mio` (lib) due to 47 previous errors

```

**Additional context**
