### ISSUE TITLE
Panic when loading a blocking resource

### ISSUE THREAD

**Issue by njust** [leptos-rs/leptos#3627]
Hi,
I sometimes get an error when loading a blocking resource:
```
thread 'tokio-runtime-worker' panicked at /Users/nico/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reactive_graph-0.1.7/src/traits.rs:200:40:
At /Users/nico/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.7.7/src/suspense_component.rs:306:26, you tried to access a reactive value which was defined at /Users/nico/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-0.7.7/src/suspense_component.rs:114:21, but it has already been disposed.
```
This is related to #2995, but I was not able to repdroduce it with timers (I tried std::thread::sleep and tokio::time::sleep).

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0" }
leptos_router = { version = "0.7.0" }
axum = { version = "0.7", optional = true }
console_error_panic_hook = { version = "0.1", optional = true}
leptos_axum = { version = "0.7.0", optional = true }
leptos_meta = { version = "0.7.0" }
tokio = { version = "1", features = ["rt-multi-thread", "fs"], optional = true }
wasm-bindgen = { version = "=0.2.100", optional = true }
pulldown-cmark = "0.13.0"
```

**To Reproduce**
```rust
use std::path::Path;

use leptos::prelude::*;
use leptos_meta::{provide_meta_context, MetaTags, Stylesheet, Title};
use leptos_router::{
    components::{Route, Router, Routes},
    hooks::use_params_map,
    path, StaticSegment,
};

pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <AutoReload options=options.clone() />
                <HydrationScripts options/>
                <MetaTags/>
            </head>
            <body>
                <App/>
            </body>
        </html>
    }
}

#[component]
pub fn App() -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context();

    view! {
        // injects a stylesheet into the document <head>
        // id=leptos means cargo-leptos will hot-reload this stylesheet
        <Stylesheet id="leptos" href="/pkg/test-web.css"/>

        // sets the document title
        <Title text="Welcome to Leptos"/>

        // content for this welcome page
        <nav>
        <a href="/">Home</a>
        <a href="/page/test">Test</a>
        <a href="/page/gerda">Gerda</a>
        </nav>
        <Router>
            <main>
                <Routes fallback=|| "Page not found.".into_view()>
                    <Route path=StaticSegment("") view=HomePage/>
                    <Route path=path!("/page/:id") view=Page ssr=leptos_router::SsrMode::Async/>
                </Routes>
            </main>
        </Router>
    }
}

#[server]
async fn load_page(id: String) -> Result<String, ServerFnError> {
    let id = id.replace("..", "");
    let path = Path::new("markdown").join(format!("{}.md", id));
    let res = tokio::fs::read_to_string(path).await?;
    let parser = pulldown_cmark::Parser::new(&res);

    let mut html_output = String::new();
    pulldown_cmark::html::push_html(&mut html_output, parser);
    Ok(html_output)
}

#[component]
fn Page() -> impl IntoView {
    let params = use_params_map();
    let id = move || params.read().get("id").unwrap_or_default();
    let res = Resource::new_blocking(id, |id| load_page(id));
    view! {
        <Suspense fallback= move || view! {
            <p>Loading</p>
        }>
        {move || res.get().map(|r| {
            match r {
                Ok(res) => view! {
                    <div inner_html=res></div>
                }.into_any(),
                Err(e) => view! {
                    <div>Failed: {e.to_string()}</div>
                }.into_any()
            }
        })}
        </Suspense>
    }
}

/// Renders the home page of your application.
#[component]
fn HomePage() -> impl IntoView {
    // Creates a reactive value to update the button
    let count = RwSignal::new(0);
    let on_click = move |_| *count.write() += 1;

    view! {
        <h1>"Welcome to Leptos!"</h1>
        <button on:click=on_click>"Click Me: " {count}</button>
    }
}

```
