### ISSUE TITLE
Weird router behaviour

### ISSUE THREAD

**Issue by mscofield0** [leptos-rs/leptos#3665]
**Describe the bug**
When switching over to a different route under the same parent, the first time around the route from which you traversed from doesn't get cleaned up. Only during the second time does it properly clean up the route. If I then move over to a different route, one that's not under the same `ParentRoute`, and go back to try the same procedure, it occurs again.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
[dependencies]
leptos = "0.7"
leptos_router = "0.7"
log = "0.4"
console_error_panic_hook = "0.1"
console_log = "1.0"

[features]
default = ["csr"]
csr = [
    "leptos/csr",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
```

**To Reproduce**
1. Run the following example
2. Open the console and watch for logs
3. Go to route-b via link
4. Go back to route-a via link
5. Go to route-b via link
6. You can also try route-a to route-c or route-d, those examples _seem_ to work
7. Go back to route-a and go to step 3

```rust
pub use leptos::{either::*, ev, html, prelude::*, task, text_prop::TextProp};
pub use leptos_router::{components::*, hooks::*, *};

pub fn main() {
	#[cfg(debug_assertions)]
	let level = log::Level::Trace;
	#[cfg(not(debug_assertions))]
	let level = log::Level::Info;
	_ = console_log::init_with_level(level);
	console_error_panic_hook::set_once();

	leptos::mount::mount_to_body(App);
}

#[component]
fn App() -> impl IntoView {
	view! {
		<Router>
			<Routes fallback=move || view! { "megacringe" }>
				<ParentRoute path=path!("/") view=Outlet>
					<Route path=path!("") view=RouteA />
					<Route path=path!("/route-b") view=RouteB />
				</ParentRoute>
				<Route path=path!("/route-c") view=RouteC />
				<Route path=path!("/route-d") view=RouteD />
			</Routes>
		</Router>
	}
}

#[component]
fn RouteA() -> impl IntoView {
	log::info!("RouteA mount");
	on_cleanup(move || log::info!("RouteA owner cleanup"));

	view! {
		<A href="/route-b">
			"go to route b"
		</A>
		<A href="/route-c">
			"go to route c"
		</A>
		<A href="/route-d">
			"go to route d"
		</A>
	}
}

#[component]
fn RouteB() -> impl IntoView {
	log::info!("RouteB mount");
	on_cleanup(move || log::info!("RouteB owner cleanup"));

	view! {
		<A href="/">
			"go to route a"
		</A>
		<A href="/route-c">
			"go to route c"
		</A>
		<A href="/route-d">
			"go to route d"
		</A>
	}
}

#[component]
fn RouteC() -> impl IntoView {
	log::info!("RouteC mount");
	on_cleanup(move || log::info!("RouteC owner cleanup"));

	view! {
		<A href="/">
			"go to route a"
		</A>
		<A href="/route-b">
			"go to route b"
		</A>
		<A href="/route-d">
			"go to route d"
		</A>
	}
}

#[component]
fn RouteD() -> impl IntoView {
	log::info!("RouteD mount");
	on_cleanup(move || log::info!("RouteD owner cleanup"));

	view! {
		<A href="/">
			"go to route a"
		</A>
		<A href="/route-b">
			"go to route b"
		</A>
		<A href="/route-c">
			"go to route c"
		</A>
	}
}
```

**Expected behavior**
I expect the component (owner) of route-a to be cleaned up _before_ route-b all the time.

**Screenshots**
![Image](https://github.com/user-attachments/assets/1a207a49-cf7c-4830-8877-e020f67b1933)
