### ISSUE TITLE
providing leptos context from axum doesn't work

### ISSUE THREAD

**Issue by djkato** [leptos-rs/leptos#3675]
**Describe the bug**
Trying to provide context from axum to leptos doesn't work. trying to use_context::<T>() always returns None.
```rs
let mut app = Router::new()
    .leptos_routes_with_context(
        &leptos_options,
        routes,
        move || provide_context(config.clone()),
        move || {
            let leptos_options = leptos_options2.clone();
            shell(leptos_options)
        },
    )
    .fallback(leptos_axum::file_and_error_handler(shell))
    .with_state(leptos_options);
```

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.7.7", features = ["nightly", "islands"] }
leptos_axum = { version = "0.7.7", optional = true }
leptos_meta = { version = "0.7.7", features = ["ssr"] }
leptos_router = { version = "0.7.7", features = ["nightly"] }
axum = { version = "0.7", optional = true, features = ["macros"] }
```

**To Reproduce**
https://github.com/djkato/leptos-axum-provide_content-bug

**Expected behavior**
use_context() to return env variable
