### ISSUE TITLE
Reactive Store panic when set during NodeRef::on_load

### ISSUE THREAD

**Issue by seanaye** [leptos-rs/leptos#3684]
**Describe the bug**
If you try to set the value of a reactive store during a NodeRef::on_load callback, there is a panic 

```
tachys-0.1.7/src/reactive_graph/node_ref.rs:49:26:
called `Option::unwrap()` on a `None` value
```

**Leptos Dependencies**

For example:
```toml
leptos = { version = "0.7.7", features = ["nightly", "islands"] }
leptos_router = { version = "0.7.7", features = ["nightly"] }
axum = { version = "0.7", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
leptos_axum = { version = "0.7.7", optional = true }
leptos_meta = { version = "0.7.7" }
reactive_stores = { version = "0.1.7" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
wasm-bindgen = { version = "=0.2.100", optional = true }

```

**To Reproduce**
1. Checkout [this repo](https://github.com/seanaye/leptos-repro)
2. `cargo leptos watch`
3. open browser console

**Expected behavior**
No panic should occur, the value in the store should be set

**Screenshots**

<img width="1479" alt="Image" src="https://github.com/user-attachments/assets/e4c4d44e-a62f-4d73-a6c6-4edf3d8db35f" />
