### ISSUE TITLE
update style/tailwind.css example to work in tailwind v4

### ISSUE THREAD

**Issue by bimoadityar** [leptos-rs/leptos#3688]
**Describe the bug**

As the current default version of tailwind used by cargo-leptos seems to be v4.0.6, the `style/tailwind.css` in the example `tailwind_axum` and `tailwind_actix` does not work anymore.

 It should be changed into:

```
@import "tailwindcss";
```

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0" }
leptos_meta = { version = "0.7.0" }
leptos_router = { version = "0.7.0" }
leptos_axum = { version = "0.7.0", optional = true }
```

**To Reproduce**

Use the exemplified `style/tailwind.css` with the following content:

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Expected behavior**

The generated css contains the tailwind styles for the used classes.
