### ISSUE TITLE
TextProp is not reactive when passed as attribute parameter

### ISSUE THREAD

**Issue by MikeOnTea** [leptos-rs/leptos#3689]
Passing a reactive TextProp as an attribute parameter like this loses reactivity:
`<input id=id.clone() type="text" name=id.clone() value=textprop />`

This is probably caused by the IntoAttributeValue implementation, which just returns a non reactive Oco<'static, str>: https://docs.rs/leptos/latest/src/leptos/text_prop.rs.html#78-84

**Leptos Dependencies**
```toml
leptos = { version = "0.7", features = ["nightly", "islands"] }
leptos_axum = { version = "0.7", optional = true, features = [] }
leptos_meta = { version = "0.7" }
leptos_router = { version = "0.7", features = ["nightly"] }
```

**Expected behavior**
TextProps passed as attribute parameters should support reactive changes.
