### ISSUE TITLE
Option store bug

### ISSUE THREAD

**Issue by mscofield0** [leptos-rs/leptos#3704]
**Describe the bug**
When switching from a `Some` to a `None` for an `Option` in a store, if the `unwrap()`'s returned subfield is used, then a panic occurs in the subfield's unwrapping closures. A minimal reproducible example is given below. The reason for the `print_on_enter_exit` function is there is because in my actual code the equivalent of the `RouteAImpl` component gets created, cleaned up and created, instead of the expected behaviour of just being created. I left it in just in case you modify the example and somehow trigger the behaviour I was experiencing.

```rust
pub use leptos::{either::*, ev, html, prelude::*, reactive::*, task, text_prop::TextProp};
pub use leptos_router::{components::*, hooks::*, *};
use reactive_stores::*;

/// Prints a message on the initial effect run and the cleanup.
///
/// Useful for debugging.
#[track_caller]
pub fn print_on_enter_exit(msg: impl ToString) {
	print_on_enter_exit_impl(msg.to_string());
}

#[track_caller]
fn print_on_enter_exit_impl(msg: String) {
	let location = std::panic::Location::caller();
	Effect::new({
		let msg = msg.clone();
		move || log::info!("{location} | on first effect: {msg}")
	});
	on_cleanup(move || log::info!("{location} | on cleanup: {msg}"));
}

pub fn main() {
	#[cfg(debug_assertions)]
	let level = log::Level::Trace;
	#[cfg(not(debug_assertions))]
	let level = log::Level::Info;
	_ = console_log::init_with_level(level);
	console_error_panic_hook::set_once();

	leptos::mount::mount_to_body(App);
}

#[derive(Store, Default, Debug, Clone, Copy)]
struct Inner {
	num: i64,
}

#[derive(Store, Default)]
struct Data {
	inner: Option<Inner>,
}

#[component]
fn App() -> impl IntoView {
	let data: Store<Data> = Store::default();
	provide_context(data);

	leptos_use::use_interval_fn(
		move || {
			if data.inner().read_untracked().is_some() {
				log::info!("before write");
				*data.inner().unwrap().num().write() += 5;
				log::info!("after write");
			}
		},
		2000,
	);

	view! {
		<Router>
			<Routes fallback=move || view! { "megacringe" }>
				<Route path=path!("/") view=RouteA />
			</Routes>
		</Router>
	}
}

#[component]
fn RouteA() -> impl IntoView {
	Effect::new(move || {
		log::info!("RouteA mount inside effect");
	});
	on_cleanup(move || log::info!("RouteA owner cleanup"));
	let data = expect_context::<Store<Data>>();

	view! {
		<div>
			<Show when=move || {
				log::info!("before is_some read");
				let truth = data.inner().read().is_some();
				log::info!("after is_some read");
				truth
			}>
				<RouteAImpl data=data.inner().unwrap() />
			</Show>
		</div>

		<div>
			<button on:click=move |_| data.inner().set(Some(Default::default()))>
				"make Some"
			</button>

			<button on:click=move |_| data.inner().set(None)>
				"make None"
			</button>
		</div>
	}
}

#[component]
fn RouteAImpl(#[prop(into)] data: Field<Inner>) -> impl IntoView {
	let inner_data_memo = Memo::new(move |_| {
		log::info!("before num get");
		let num = data.num().get();
		log::info!("after num get");
		num
	});

	print_on_enter_exit("routeaimpl");

	view! {
		<span>"inner data: " {inner_data_memo}</span>
	}
}
```

**Leptos Dependencies**
This is on leptos main.
```toml
[dependencies]
leptos = "0.7"
leptos_router = "0.7"
reactive_stores = "0.1"
leptos-use = "0.15"
log = "0.4"
console_error_panic_hook = "0.1"
console_log = "1.0"

[features]
default = ["csr"]
csr = [
    "leptos/csr",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[patch.crates-io]
leptos = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
leptos_router = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
leptos_server = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
tachys = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
either_of = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
reactive_graph = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
reactive_stores = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
reactive_stores_macro = { git = "https://github.com/leptos-rs/leptos", branch = "main" }
```

**To Reproduce**
1. Start the app
2. Click on 'make Some'
3. Wait 2-5 seconds
4. Click on 'make None'
5. Check console, the panic should have occurred

**Expected behavior**
Unwrapping an option like that should not cause a panic since the `RouteAImpl` component is behind a `Show` conditional which ought to display it only when the inner value is really `Some`.
