### ISSUE TITLE
Hydration error when using nested `ParentRoute`s that suspend + a leaf `Route` using `Suspend`

### ISSUE THREAD

**Issue by ilyvion** [leptos-rs/leptos#3726]
**Describe the bug**
In the `App`, have a `Router` with nested `ParentRoute`s where each one's `view` does `<Suspense><Outlet /></Suspense>` and then have a `Route` with a view that does
```rust
<Suspense>
    {move || Suspend::new(async move {
        let _ = some_resource.await.ok();
        view! { <h1>"Doesn't even need to use the result"</h1> }
    })}
</Suspense>
```

**Leptos Dependencies**

```toml
leptos = { version = "0.8.0-alpha", features = ["nightly"] }
leptos_router = { version = "0.8.0-alpha", features = ["nightly"] }
leptos_axum = { version = "0.8.0-alpha", optional = true }
leptos_meta = { version = "0.8.0-alpha" }
```

**To Reproduce**
1. Grab a copy of https://github.com/ilyvion-contrib/hydration_error_mre
2. Run project with `cargo leptos serve`
4. See hydration error in JS console

**Expected behavior**
Any number of nested `<Suspense>`s and `Suspend`s should be fine in theory. Right?

**Additional context**
This is obviously an MRE case; in the real project there's more going on, which each `ParentRoute` "level" doing different work that needs suspending, and not all views are within all `ParentRoute`s, so I can't easily "un-nest" them either.

Removing either of the `ParentRoute`s or either of their `Suspense`s results in the problem going away. Likewise, commenting out the `let _ = test_resource.await.ok();` line results in the problem going away. It's not actually using the value that matters, just the fact that there's an `.await`.

Unfortunately I'm using this `Suspend::new` with `resource.await` pattern in basically all of my views, so I'd like it if I didn't have to rewrite them to do something else.

This issue felt *similar* to #3707 but also different enough that I thought I'd make a separate one. At least in my case it does not seem to be the exact case of
1. A text node
2. Suspense
3. Something else

This bug also happens on 0.7.7, but I am reporting it on 0.8 as I wanted to make sure it was still a problem there and also I assume 0.7 won't be receiving any fixes going forward.
