### ISSUE TITLE
Axum routes don't quite match up with Leptos routes

### ISSUE THREAD

**Issue by ilyvion** [leptos-rs/leptos#3730]
**Describe the bug**
I have these routes that take an optional "root" param, like this:
```rs
<Route path=path!("/categories/:root_category?") view=Categories />
<Route path=path!("/locations/:root_location?") view=Locations />
```
If you try to go to `/categories/` or `/locations/`, Axum returns 404. This goes away if I add extra `Route`s without the params, like this:
```rs
<Route path=path!("/categories/:root_category?") view=Categories />
<Route path=path!("/categories/") view=|| () />
<Route path=path!("/locations/:root_location?") view=Locations />
<Route path=path!("/locations/") view=|| () />
```
Note the empty views -- these are actually never hit by the Leptos router, but they seem to be required by Axum's. The `?` seemingly makes no difference, the behavior is the same whether or not it's there. It just feels *correct* to have it there though, since they're optional params.

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0", features = ["nightly"] }
leptos_axum = "0.7.0"
leptos_meta = "0.7.0"
leptos_router = { version = "0.7.0", features = ["nightly"] }
```

**To Reproduce**
1. Add a route ending with an optional parameter
2. Attempt to visit the route without the parameter
3. Get 404, unless an explicit route without the parameter is also added.

**Expected behavior**
The routing should behave identically between Leptos and Axum.

**Additional context**
Originally brought up on Discord @ https://discord.com/channels/1031524867910148188/1351779128008769637
