### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by johan-smits** [leptos-rs/leptos#3790]
**Describe the bug**
I have a `Store` struct that has a `Vec` of items in a sub struct. Now when the parent gets replaced with 0 items in the vec it panics.

**Leptos Dependencies**

```toml
leptos = { version = "0.8.0-beta", features = ["csr"] }
leptos_router = "0.8.0-beta"
reactive_stores = "0.2.0-beta"
```

**To Reproduce**
I'm able to reproduce the error exactly but it might be related:
1. Clone https://github.com/johansmitsnl/leptos-test/ and use the branch `disposed-signal`
2. Change input value to something else
3. Hit the clear button

**Expected behavior**
Don't panic :)

**Additional context**

The console error:
```
index.crates.io-1949cf8c6b5b557f/reactive_stores-0.2.0-beta/src/keyed.rs:462:24:
index out of bounds: the len is 0 but the index is 0
```
