### ISSUE TITLE
Generated wasm file is loaded twice

### ISSUE THREAD

**Issue by prsutherland** [leptos-rs/leptos#3814]
**Describe the bug**
The wasm file is loaded twice and there is a console warning stating:

```
[Warning] The resource http://localhost:3000/pkg/example.wasm was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
```

This appears to be caused by a [CORS mismatch](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload#cors-enabled_fetches) between the preload link and the fetch of the wasm file.

**Leptos Dependencies**

For example:
```toml
[dependencies]
leptos = { version = "0.7.0" }
leptos_router = { version = "0.7.0" }
axum = { version = "0.7", optional = true }
console_error_panic_hook = { version = "0.1", optional = true}
leptos_axum = { version = "0.7.0", optional = true }
leptos_meta = { version = "0.7.0" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
wasm-bindgen = { version = "=0.2.100", optional = true }
```

**To Reproduce**
1. Create a blank leptos project. I used https://github.com/leptos-rs/start-axum
2. Run the app
3. Open a new browser window with dev tools opened to the Network tab (I am using safari)
4. Visit localhost:3000
5. Note the duplicate wasm file requests and the warning on the dev tools Console tab.

```bash
% cargo leptos new --git https://github.com/leptos-rs/start-axum                

🤷   Project Name: example
✔ 🤷   Use nightly features? · No
% cd example 
% cargo leptos watch                                            

   Compiling proc-macro2 v1.0.94

   ( Omitting for brevity )

   Compiling leptos_server v0.7.8
   Compiling leptos_dom v0.7.8
   Compiling leptos v0.7.8
   Compiling leptos_meta v0.7.8
   Compiling leptos_router v0.7.8
   Compiling example v0.1.0 (/Users/paul/Desktop/example)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 31.33s
       Cargo finished cargo build --package=example --lib --target-dir=/Users/paul/Desktop/example/target/front --target=wasm32-unknown-unknown --no-default-features --features=hydrate
       Front generating JS/WASM with wasm-bindgen
    Finished generating JS/WASM for front in 188.114375ms
   Compiling unicode-ident v1.0.18

   ( Omitting for brevity )

   Compiling leptos_dom v0.7.8
   Compiling leptos_server v0.7.8
   Compiling leptos v0.7.8
   Compiling leptos_router v0.7.8
   Compiling leptos_meta v0.7.8
   Compiling leptos_integration_utils v0.7.8
   Compiling leptos_axum v0.7.8
   Compiling example v0.1.0 (/Users/paul/Desktop/example)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 26.02s
       Cargo finished cargo build --package=example --bin=example --no-default-features --features=ssr
     Serving at http://127.0.0.1:3000
    Creating ignore list from '.gitignore' file
listening on http://127.0.0.1:3000
```
**Expected behavior**
The wasm file should only be loaded once.

**Screenshots**

![Image](https://github.com/user-attachments/assets/67b96def-0aed-4239-8fd6-3916208622b9)

![Image](https://github.com/user-attachments/assets/cd80277e-677c-4dba-b439-5f42fb128873)

**Additional context**
The preload link looks like this:

```html
<link rel="preload" href="/pkg/psbot.wasm" as="fetch" type="application/wasm" crossorigin="3wWvZEHBTLHCxexEm0dK0g">
```

That is not a valid value for [`crossorigin`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin). I believe that attribute should be `nonce`.
