### ISSUE TITLE
Route matches incorrectly

### ISSUE THREAD

**Issue by MikeOnTea** [leptos-rs/leptos#3817]
Given this route:
```
<Route path=path!("/tests/abc") view=|| view! { "Tests" } />
```
a url of `/test/ab/` actually matches this route, even though it is both missing an s and a c in the end of the segments.

**Leptos Dependencies**
```toml
leptos = { version = "0.7", features = ["nightly", "islands"] }
leptos_axum = { version = "0.7", features = [] }
leptos_meta = { version = "0.7" }
leptos_router = { version = "0.7", features = ["nightly"] }
```
