### ISSUE TITLE
Reactive store doesn't update with UUID in some cases

### ISSUE THREAD

**Issue by mahdi739** [leptos-rs/leptos#3828]
**Describe the bug**
I have nested keyed subfields, and one of them uses UUID (v4) to generate the keys. Strangely, some of them don’t get updated in `For`. I’m not sure if the problem comes from the reactive stores, the `For`, or somewhere else. I tried to reproduce something similar to my real app:
https://github.com/mahdi739/leptos_store_uuid_rep/blob/main/src/app.rs

**Leptos Dependencies**

```toml
leptos = { git = "https://github.com/leptos-rs/leptos", features = ["csr"] }
reactive_stores = { git = "https://github.com/leptos-rs/leptos", package = "reactive_stores" }
reactive_stores_macro = { git = "https://github.com/leptos-rs/leptos", package = "reactive_stores_macro" }
uuid = { version = "1.13.1", features = ["js", "serde", "v4"] }
console_log = "1"
log = "0.4.22"
console_error_panic_hook = "0.1.7"
```

**To Reproduce**
Add the `uuid` crate with `js` and `v4` features.
The main code:
```rs
#[component]
pub fn App() -> impl IntoView {
  let state = Store::new(State {
    selected_session: None,
    sessions: vec![
      Session { id: 0, messages: vec![Message { id: Uuid::new_v4(), parts: vec![] }] },
      Session { id: 1, messages: vec![Message { id: Uuid::new_v4(), parts: vec![] }] },
      Session { id: 2, messages: vec![Message { id: Uuid::new_v4(), parts: vec![] }] },
      Session { id: 3, messages: vec![Message { id: Uuid::new_v4(), parts: vec![] }] },
      Session { id: 4, messages: vec![Message { id: Uuid::new_v4(), parts: vec![] }] },
    ],
  });

  view! {
    <button on:click=move |_| {
      let length = state.sessions().get().len();
      state
        .sessions()
        .update(|f| {
          f.push(Session {
            id: length + 1,
            messages: vec![
              Message {
                id: Uuid::new_v4(),
                parts: vec![],
              },
            ],
          })
        });
    }>"ADD SESSION"</button>
    {move || {
      state
        .selected_session()
        .get()
        .map(|selected_sessioon| {
          view! {
            <button on:click=move |_| {
              let length = selected_sessioon.get().messages.last().unwrap().parts.len() + 1;
              let message = selected_sessioon.messages().iter_unkeyed().last().unwrap();
              message.parts().update(|m| m.push(format!("{length}")));
            }>"Count"</button>
          }
        })
    }}
    <For each=move || state.sessions() key=|session| session.id().get() let:session>
      <div>
        <label>
          <input
            type="radio"
            checked=state
              .selected_session()
              .try_get()
              .flatten()
              .map(|s| s.id().get() == session.id().get())
            name="session"
            on:click=move |_| {
              state.selected_session().set(Some(session.into()));
            }
          />
          <b>"Session " {move || session.id().get().to_string()} ": "</b>
        </label>
        <For each=move || session.messages() key=|message| message.id().get() let:message>
          <For each=move || message.parts() key=|part| part.get() let:part>
            {move || part.get()}
          </For>
        </For>
      </div>
    </For>
  }
}
```
**Steps to reproduce the behavior:**
Run `trunk serve --open` in the project's directory.
Click on `ADD SESSION` and select the newly added sessions. Then click the `Count` button.

**Expected Behavior**  
The session items should display numbers in front of themselves, like the default added sessions.

**Additional Context**  
Interestingly, if you continue to add more sessions, after 5-6 more sessions, the new ones start working again.  
If you change the number of default sessions, the number of broken sessions varies.  
If you replace the UUID key with a `usize`, it works correctly.
