### ISSUE TITLE
[0.8] Stack overflow in 'tokio-runtime-worker'

### ISSUE THREAD

**Issue by adrianncovaci** [leptos-rs/leptos#3833]
**Describe the bug**
Stack overflow error occurs when refreshing a page on a specific route, but not when navigating to the route via client-side navigation.
When navigating to a route using in-app navigation, everything works fine. However, when I refresh the browser while on that route (causing a full server-side render), I get a fatal stack overflow error.

```
thread 'tokio-runtime-worker' has overflowed its stack
fatal runtime error: stack overflow
```

**Leptos Dependencies**
```toml
[workspace.dependencies]
leptos = { version = "0.8.0-beta", features = ["nightly"] }
leptos_meta = { version = "0.8.0-beta"}
leptos_router = { version = "0.8.0-beta", features = ["nightly"] }
leptos_axum = { version = "0.8.0-beta" }

axum = "0.8"
cfg-if = "1"
console_error_panic_hook = "0.1.7"
console_log = "1"
getrandom = { version = "0.3", features = ["wasm_js"] }
http = "1"
log = "0.4.20"
serde = { version = "1", features = ["derive"] }
simple_logger = "5.0.0"
strum = "0.27"
strum_macros = "0.27"
thiserror = "2.0.11"
time = { version = "0.3", features = ["serde", "wasm-bindgen"] }
tokio = { version = "1.33.0", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["full"] }
uuid = { version = "1", features = ["serde", "v4", "js"] }
wasm-bindgen = "=0.2.100"
```

**To Reproduce**
https://github.com/adrianncovaci/overflow-leptos-reproduce
