### ISSUE TITLE
[leptos_0.7][nightly] leptos_macro doesn't compile

### ISSUE THREAD

**Issue by dev-inigmas** [leptos-rs/leptos#3862]
**Describe the bug**

leptos_0.7 branch on nightly does not compile.

**Leptos Dependencies**

```toml
leptos          = { version="0.7.8", features=["nightly"] }
leptos_axum     = { version="0.7.8" }
leptos_meta     = { version="0.7.8" }
leptos_router   = { version="0.7.8", features=["nightly"] }
reactive_stores = { version="0.1.8" }
```

or

```toml
leptos          = { git="https://github.com/leptos-rs/leptos.git", branch="leptos_0.7", features=["nightly"] }
leptos_axum     = { git="https://github.com/leptos-rs/leptos.git", branch="leptos_0.7" }
leptos_meta     = { git="https://github.com/leptos-rs/leptos.git", branch="leptos_0.7" }
leptos_router   = { git="https://github.com/leptos-rs/leptos.git", branch="leptos_0.7", features=["nightly"] }
reactive_stores = { git="https://github.com/leptos-rs/leptos.git", branch="leptos_0.7" }
```

**To Reproduce**

1. Make sure on latest `nightly`.
2. Attempt to build.

**Screenshots**

From the leptos 0.7.8 release:

![Image](https://github.com/user-attachments/assets/79a4d80f-7f3b-4b93-8fec-eaf2ba9399bc)

From the current `leptos_0.7` branch:

![Image](https://github.com/user-attachments/assets/6008bda3-25d8-44ab-8e15-339e7e3eacd4)

**Next Steps**
[X] I made a PR
[ ] I would like to make a PR, but need help getting started
[ ] I want someone else to take the time to fix this
[ ] This is a low priority for me and is just shared for your information
