### ISSUE TITLE
Proc Macro Mismatch issue in leptos_macro 0.7.9

### ISSUE THREAD

**Issue by jacobrmoss** [leptos-rs/leptos#3867]
Unable to compile with "cargo leptos", because of the following error:

Leptos/Axum versions in cargo.toml
```toml
leptos = { version = "0.7.8", features = ["nightly"] }
leptos_router = { version = "0.7.8", features = ["nightly"] }
leptos_axum = { version = "0.7.8", optional = true }
leptos_meta = { version = "0.7.8" }

axum = { version = "0.7", features = ["macros"], optional = true }
```
leptos_macro-0.7.9/src/lib.rs:360:22
error[E0599]: no method named `file` found for struct `memo::proc_macro::Span` in the current scope

To reproduce just delete your cargo.lock with Leptos 0.7.8 with the Leptos Axum SSR template.

Possibly related to: https://github.com/dtolnay/proc-macro2/issues/499
