### ISSUE TITLE
Incorrect child rendering order in SSR

### ISSUE THREAD

**Issue by mahdi739** [leptos-rs/leptos#3906]
**Describe the bug**
In an SSR setup with the client side compiled to WASM (similar to the [todo_app_sqlite_csr](https://github.com/leptos-rs/leptos/tree/main/examples/todo_app_sqlite_csr) example), deleting a list item causes the delete button to render before the title, resulting in an incorrect order. This issue does not occur in a pure CSR app.
A minimal reproduction:
[leptos_render_bug](https://github.com/mahdi739/leptos_render_bug/blob/main/src/app.rs)

**Leptos Dependencies**
```toml
leptos = { git = "https://github.com/leptos-rs/leptos", features = ["csr"] }
reactive_stores = { git = "https://github.com/leptos-rs/leptos" }
reactive_stores_macro = { git = "https://github.com/leptos-rs/leptos" }
chrono = { version = "0.4.39", features = ["serde"] }
wasm-bindgen = "0.2.100"
console_log = "1"
log = "0.4.22"
console_error_panic_hook = "0.1.7"
actix-web = { version = "4.10.2", optional = true }
actix-files = { version = "0.6.6", optional = true }
leptos_integration_utils = { git = "https://github.com/leptos-rs/leptos", optional = true }
leptos_actix = { git = "https://github.com/leptos-rs/leptos", optional = true }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", optional = true }
```

**To Reproduce**
1. Run the app
2. Click on delete button

**Next Steps**
[ ] I will make a PR
[ ] I would like to make a PR, but need help getting started
[x] I want someone else to take the time to fix this
[ ] This is a low priority for me and is just shared for your information

**Additional context**
This is the main component:
```rust
 view! {
    <aside>
      <ul>
        <ForEnumerate
          each=move || state.sessions()
          key=|item| item.date_created().get()
          let(index,
          session)
        >
          <li>
            {move || match session.edit_mode().get() {
              EditMode::Done => {
                Some(
                  view! {
                    {move || {
                      format!(
                        "{}\n{}",
                        session.title().get(),
                        session.date_created().get().format("%d/%m/%Y %H:%M"),
                      )
                    }}
                    <button>"Edit"</button>
                  },
                )
              }
              EditMode::Editing => None,
            }}
            <button on:click=move |_| {
              state.sessions().write().remove(index.get());
            }>"Delete"</button>
          </li>
        </ForEnumerate>
      </ul>
    </aside>
  }
```
