### ISSUE TITLE
provide/use context does not work in 0.8 anymore with donut islands

### ISSUE THREAD

**Issue by MikeOnTea** [leptos-rs/leptos#3928]
Given these components:
```rust
#[island]
pub fn LodgersProvider(mut lodgers: Vec<LodgerDto>, children: Children) -> impl IntoView {
	let lodgers = StoredValue::new(lodgers);
	provide_context(lodgers);
	children()
}

#[island]
pub fn TestComponent() -> impl IntoView {
	let lodgers = use_context::<StoredValue<Vec<LodgerDto>>>().unwrap();
	view! {}
}

#[component]
pub fn Flat() -> impl IntoView {
	let lodgers = vec![];
	Ok::<_, AppError>(view! {
		<LodgersProvider lodgers=lodgers.clone()>
			<h1>test</h1>
			<TestComponent />
		</LodgersProvider>
	})
}
```
Here, the unwrap() in TestComponent will fail. However, if i remove the h1 tag right before it, it will work. This also worked fine in Leptos 0.7.

**Leptos Dependencies**
```toml
leptos = { version = "0.8", features = ["nightly", "islands"] }
leptos_axum = { version = "0.8", features = [] }
leptos_meta = { version = "0.8" }
leptos_router = { version = "0.8", features = ["nightly"] }
```

**Next Steps**
[ ] I will make a PR
[ ] I would like to make a PR, but need help getting started
[ x] I want someone else to take the time to fix this
[ ] This is a low priority for me and is just shared for your information
