### ISSUE TITLE
Hydration error when use `Stylesheet` or `Style` Component

### ISSUE THREAD

**Issue by visig9** [leptos-rs/leptos#3945]
**Describe the bug**
When I add `<Stylesheet>` or `<Style>` into a `ssr` project, the console in web browser report the following text:

```
A hydration error occurred while trying to hydrate an element defined at /Users/xxx/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos_meta-0.8.1/src/stylesheet.rs:38:14.

The framework expected an HTML <link> element, but found this instead: <!-- -->
```

This problem only happen in leptos >= 0.8. I found it in other project but can use `start-axum` template to reproduce this behavior. 

**Leptos Dependencies**

```toml
leptos = { version = "0.8.0" }
leptos_router = { version = "0.8.0" }
axum = { version = "0.8", optional = true }
console_error_panic_hook = { version = "0.1", optional = true}
leptos_axum = { version = "0.8.0", optional = true }
leptos_meta = { version = "0.8.0" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
wasm-bindgen = { version = "=0.2.100", optional = true }
```

**To Reproduce**

1. `cargo leptos new --git https://github.com/leptos-rs/start-axum -n leptos-hydration-error`
2. Select `No` for `Use nightly features`.  
3. `cargo leptos watch` and check <http://localhost:3000> to make sure no error in browser console (currently it use leptos 0.7 version)
4. Open `Cargo.toml` and modify  dependencies version into following:

```toml
[dependencies]
leptos = { version = "0.8.0" }                          # change from v0.7.0
leptos_router = { version = "0.8.0" }                   # change from v0.7.0
axum = { version = "0.8", optional = true }             # change from v0.7
console_error_panic_hook = { version = "0.1", optional = true}
leptos_axum = { version = "0.8.0", optional = true }    # change from v0.7.0
leptos_meta = { version = "0.8.0" }                     # change from v0.7.0
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
wasm-bindgen = { version = "=0.2.100", optional = true }
```

5. `cargo leptos watch` again and check <http://localhost:3000> to see the error message in console.

<img width="1447" alt="Image" src="https://github.com/user-attachments/assets/db5f7138-9082-42c7-8317-d1f341950a4c" />

**Next Steps**
[ ] I will make a PR
[ ] I would like to make a PR, but need help getting started
[x] I want someone else to take the time to fix this
[ ] This is a low priority for me and is just shared for your information

**Additional context**
v0.7 HTML sample:

<img width="1441" alt="Image" src="https://github.com/user-attachments/assets/f3f0933e-76ef-4aa8-a22d-096712749853" />

v0.8 HTML sample:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/c7bb0443-cc26-42bf-8f36-b84402faec42" />

The `<!><!>` part before `<link ...>` may relevant.
