### ISSUE TITLE
Hydration error on any project using leptos_meta::Stylesheet and erase_components in 0.8.1

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#3946]
The 0.8.1 update breaks the use of `rustflags = ["--cfg=erase_components"]` and `leptos_meta::Stylesheet` with hydration with the following error:

```
A hydration error occurred while trying to hydrate an element defined at C:\Users\Luxalpa\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\leptos_meta-0.8.1\src\stylesheet.rs:38:14.

The framework expected an HTML <link> element, but found this instead:  
<!--  -->
 
The hydration mismatch may have occurred slightly earlier, but this is the first time the framework found a node of an unexpected type.
```

The error does not seem to appear when not using erase_components.

**Leptos Dependencies**
```toml
leptos = { version = "0.8.1", features = ["nightly"] }
leptos_meta = { version = "0.8.1" }
leptos_actix = { version = "0.8.1", optional = true }
leptos_router = { version = "0.8.1", features = ["nightly"] }
```

**To Reproduce**
```rs
#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {
        <Stylesheet id="leptos" href="/pkg/leptos-test.css"/>
        <div>"Hello World!"</div>
    }
}
```

Relevant part of the SSR-rendered HTML:

```html
... </script><!><!--hot-reload|C:-Users-Luxalpa-.cargo-registry-src-index.crates.io-1949cf8c6b5b557f-leptos-0.8.1-src-hydration-mod.rs-110|close--><!--HEAD--><!><!><link id="leptos" rel="stylesheet" href="[/pkg/leptos-test.css](view-source:http://127.0.0.1:3000/pkg/leptos-test.css)">...
```
It seems that it stumbles over one or both of the `<!>` after the closing `<!--HEAD-->`.

**Comment by gbj** [comment]
For the moment, disabling erasing components in `Cargo.toml` will fix it:
```toml
[package.metadata.leptos]
# ... 
disable-erase-components = true
```

I'll work on a fix as soon as I can.
