### ISSUE TITLE
Redirect + Transition can lead to "could not find parent" unreachable

### ISSUE THREAD

**Issue by Bytekeeper** [leptos-rs/leptos#3962]
**Describe the bug**
Using Transition with a redirect can lead to "could not find parent element" errors.

**Leptos Dependencies**
I used `cargo leptos new --git https://github.com/leptos-rs/start-axum`:

```toml
leptos = { version = "0.7.0" }
leptos_router = { version = "0.7.0" }
axum = { version = "0.7", optional = true }
console_error_panic_hook = { version = "0.1", optional = true}
leptos_axum = { version = "0.7.0", optional = true }
leptos_meta = { version = "0.7.0" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
wasm-bindgen = { version = "=0.2.100", optional = true }
```

**To Reproduce**
1. Generate new project with cargo leptos as seen above.
2. Replace the bottom part of app.rs with:
```rust
#[component]
pub fn App() -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context();

    view! {
        // injects a stylesheet into the document <head>
        // id=leptos means cargo-leptos will hot-reload this stylesheet
        <Stylesheet id="leptos" href="/pkg/bug.css"/>

        // sets the document title
        <Title text="Welcome to Leptos"/>

        // content for this welcome page
        <Router>
            <main>
                <Routes fallback=|| "Page not found.".into_view()>
                    <Route path=StaticSegment("") view=Redirect/>
                    <Route path=StaticSegment("/hp") view=HomePage/>
                </Routes>
            </main>
        </Router>
    }
}

#[server]
async fn redirect() -> Result<(), ServerFnError> {
    leptos_axum::redirect("/hp");
    Ok(())
}

#[server]
async fn data() -> Result<Vec<String>, ServerFnError> {
    Ok(vec!["Test".to_string()])
}

#[component]
fn Redirect() -> impl IntoView {
    let _ = LocalResource::new(move || redirect());
    view! {}
}
/// Renders the home page of your application.
#[component]
fn HomePage() -> impl IntoView {
    let resource = Resource::new(|| true, |_| data());
    view! {
        <Transition>
        { move || resource.get().into_iter().flatten().map(|_| view! { }).collect_view() }
        </Transition>
    }
    //view! {
    //    <Transition>
    //        <p>
    //   { move || resource.get().into_iter().flatten().map(|_| view! { }).collect_view() }
    //        </p>
    //    </Transition>
    //}
}
```
3. Run and visit '/' - which should redirect to '/hp'
4. The screen will be empty and a console error will appear showing 'could not find parent element'
5. Now hit refresh, the console error will be gone and you'll see "It worked" on the screen

**Additional context**
Not using the `fn data` function or not using a Vec seems not to trigger the error. 

*ALSO* - if you use an element in the Transition (see the commented code) - there also won't be an error.
