### ISSUE TITLE
JS Infinite loop with islands-router

### ISSUE THREAD

**Issue by FranzStrudel** [leptos-rs/leptos#3970]
**Describe the bug**
When navigating in the app through links, the replaceBranch method is stuck in a infinite loop.

Initial load is ok. 

**Leptos Dependencies**

```toml
leptos = { version = "0.8.0", features = ["nightly", "islands", "islands-router"] }
leptos_router = { version = "0.8.0", features = ["nightly"] }
axum = { version = "0.8", optional = true, features = ["macros"] }
console_error_panic_hook = { version = "0.1", optional = true}
leptos_axum = { version = "0.8.0", optional = true, features = ["islands-router"] }
leptos_meta = { version = "0.8.0" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
wasm-bindgen = { version = "=0.2.100", optional = true }
```

**To Reproduce**
1. Go to 'http://localhost:3000/1'
2. Click on any link (it might be necessary to click the link several times)
3. Url is updated, but page is frozen and unresponsive

**Screenshots**

<img width="311" alt="Image" src="https://github.com/user-attachments/assets/be8b64d0-d5d2-4816-bd28-03af4a63b1f1" />

Notice the url is /1, but we are frozen on "2"

**Next Steps**
[ ] I will make a PR
[ ] I would like to make a PR, but need help getting started
[X] I want someone else to take the time to fix this
[X] This is a low priority for me and is just shared for your information

**Additional context**
The data is warp in a Arc<RwLock> because I want the data to be in memory server-side, while being updated through another process (I listen an SurrealDB Live Query and updated the data accordingly)

[lib.rs.txt](https://github.com/user-attachments/files/20162112/lib.rs.txt)
[main.rs.txt](https://github.com/user-attachments/files/20162113/main.rs.txt)
