### ISSUE TITLE
Returning floating point NAN from a server function causes hydration error in SSR mode

### ISSUE THREAD

**Issue by dbdr** [leptos-rs/leptos#3997]
When a server function returns data that contains NAN, it causes a hydration error. I managed to narrow it down to this simple reproduction, based on https://github.com/leptos-rs/start-axum:

```rust
#[component]
fn HomePage() -> impl IntoView {
	view! {
		<Await
			future=get_data()
			let(data)
		>{
			match data {
				Ok(data) => view! { {data.to_string()} }.into_any(),
				Err(e)   => view! {
					<div> "Error fetching data:" {e.to_string()} </div>
				}.into_any()
			}
		}</Await>
	}
}

#[server]
async fn get_data() -> Result<f64, ServerFnError> {
	Ok(f64::NAN)
}
```

**Leptos Dependencies**

```toml
[dependencies]
leptos = { version = "0.8.0" }
leptos_router = { version = "0.8.0" }
axum = { version = "0.8.0", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
leptos_axum = { version = "0.8.0", optional = true }
leptos_meta = { version = "0.8.0" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
wasm-bindgen = { version = "=0.2.100", optional = true }

[features]
hydrate = [
    "leptos/hydrate",
    "dep:console_error_panic_hook",
    "dep:wasm-bindgen",
]
ssr = [
    "dep:axum",
    "dep:tokio",
    "dep:leptos_axum",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
]
```

**To Reproduce**
1. `cargo leptos new --git https://github.com/leptos-rs/start-axum`
2. Modify app.rs with the code above.
3. Open the page in browser
4. The page shows NaN as expected, but the browser console has:

```
A hydration error occurred while trying to hydrate an element defined at src/app.rs:43:14.

The framework expected a marker node, but found this instead:  
#text "NaN"
 

The hydration mismatch may have occurred slightly earlier, but this is the first time the framework found a node of an unexpected type. [hydration-error.js:532:9](http://127.0.0.1:4000/pkg/hydration-error.js)
panicked at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tachys-0.2.2/src/hydration.rs:186:9:
Unrecoverable hydration error. Please read the error message directly above this for more details.

Stack:

__wbg_get_imports/imports.wbg.__wbg_new_8a6f238a6ece86ea@http://127.0.0.1:4000/pkg/hydration-error.js:766:13
hydration_error.wasm.__wbg_new_8a6f238a6ece86ea externref shim@http://127.0.0.1:4000/pkg/hydration-error.wasm:wasm-function[10886]:0x23543e
hydration_error.wasm.console_error_panic_hook::Error::new::h5abd51a18b5b3124@http://127.0.0.1:4000/pkg/hydration-error.wasm:wasm-function[6475]:0x1f76ad
hydration_error.wasm.console_error_panic_hook::hook_impl::h681d50068ded7f79@http://127.0.0.1:4000/pkg/hydration-error.wasm:wasm-function[1479]:0x11c610
hydration_error.wasm.console_error_panic_hook::hook::h2759bb4e0edb9451@http://127.0.0.1:4000/pkg/hydration-error.wasm:wasm-function[9154]:0x22331f
hydration_error.wasm.core::ops::function::Fn::call::h9818fa3bdaf3f258@http://12…
[hydration-error.js:543:9](http://127.0.0.1:4000/pkg/hydration-error.js)
Uncaught (in promise) RuntimeError: unreachable executed
```

In an actual app, reactivity is lost after that.

At the very least, this should be mentioned in the Hydration Bugs section of the book. However, it would be *really* nice if this could be better supported, either by actually allowing NAN in server function results, or at least by giving a more explicit error message. NAN is often a sign of another bug (in the server function), but getting an hydration bug for it is very non-obvious, and can lead to a lot of searching (it's more obvious in this minimal example where NAN is directly shown as the top-level element, but in a real situation it would be buried deeper, or even not visible at all).
