### ISSUE TITLE
Effect's previous value is always None

### ISSUE THREAD

**Issue by mahdi739** [leptos-rs/leptos#4039]
**Describe the bug**
I have an effect that depends on a reactive store field. When the field changes, the effect is triggered, but it doesn't detect its previous value.

**Leptos Dependencies**
```toml
leptos = { git = "https://github.com/leptos-rs/leptos", features = ["csr"] }
reactive_stores = { git = "https://github.com/leptos-rs/leptos", package = "reactive_stores" }
reactive_stores_macro = { git = "https://github.com/leptos-rs/leptos", package = "reactive_stores_macro" }
console_log = "1"
log = "0.4.22"
console_error_panic_hook = "0.1.7"
```

**To Reproduce**
1. Run the app using Trunk.
2. Open the dev tools and go to the console tab.
3. Click on any item in the list.
4. In the console, you should see the previous value logged and it's always `None`

**Next Steps**
[ ] I will make a PR
[ ] I would like to make a PR, but need help getting started
[x] I want someone else to take the time to fix this
[ ] This is a low priority for me and is just shared for your information

**Additional context**
This is the main code:
```rust
#[derive(Default, Store, Debug, Clone)]
pub struct State {
  #[store(key: usize = |session| session.id)]
  pub sessions: Vec<Session>,
  pub selected_session: Option<Field<Session>>,
}
#[derive(Default, Store, Debug, Clone)]
pub struct Session {
  pub id: usize,
  pub title: String,
}

#[component]
pub fn App() -> impl IntoView {
  let state = Store::new(State {
    sessions: vec![
      Session { id: 0, title: "Title".to_string() },
      Session { id: 1, title: "Title".to_string() },
      Session { id: 2, title: "Title".to_string() },
    ],
    selected_session: None,
  });

  view! {
    <ul>
      <For each=move || state.sessions() key=|item| item.id().get() let(session)>
        <li on:click=move |_| {
          state.selected_session().set(Some(session.into()));
        }>{move || session.get().title}</li>
      </For>
    </ul>
    {move || {
      state
        .selected_session()
        .get()
        .map(|selected_session| {
          Effect::new(move |prev| {
            console_log(&format!("Previous value: {prev:#?}"));
            selected_session.title().get()
          });
          view! { "Hey" }
        })
    }}
  }
}
```

The repo:
https://github.com/mahdi739/leptos_rerender_issue
