### ISSUE TITLE
Diferent behaviour in SRR and CSR redirect from page without trailing slash to relative page

### ISSUE THREAD

**Issue by TERRORW0LF** [leptos-rs/leptos#4054]
**Describe the bug**
When using the `Redirect` component with a relative link, in SSR, on a page that has no trailing slash (e.g. you call `your.site/redirect` with redirect to `this/subpage`) you get send to `your.site/this/subpage`. In CSR you get send to `your.site/redirect/this/subpage`

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.8.2", features = ["nightly"] }
leptos_axum = { version = "0.8.2", optional = true }
leptos_meta = { version = "0.8.2"}
leptos_router = { version = "0.8.2"}
```

**To Reproduce**
1. Use the start-axum template
2. Create a route with a redirect to a relative subroute (e.g. route `/redirect` to `this/subpage`)
3. Create a link to `/redirect` from the homepage
4. Open the page on `/redirect`
5. Observe the url changing to `/this/subpage`
6. Open the page on `""`
7. Click on a link to `/redirect`
8. Observe the url chaning to `/redirect/this/subpage`

**Next Steps**
- [ ] I will make a PR
- [x] I would like to make a PR, but need help getting started
- [ ] I want someone else to take the time to fix this
- [ ] This is a low priority for me and is just shared for your information

**Additional context**
Looking at the underlying redirect implementation for SSR, it just sets the `Location` header, so I'm not sure how / if to fix it. However the SSR and CSR results still differ, which they definitely shouldn't.
