### ISSUE TITLE
Hydration error when using `use_location().hash`

### ISSUE THREAD

**Issue by TERRORW0LF** [leptos-rs/leptos#4059]
**Describe the bug**
On SSR loaded pages using `use_location().hash` to determine dom structure results in a hydration error. This is due to the hash / fragment always being `""` on the server as it can't be sent in the request while the client has the "correct" value.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.8.2", features = ["nightly"] }
leptos_axum = { version = "0.8.2", optional = true }
leptos_meta = { version = "0.8.2"}
leptos_router = { version = "0.8.2"}
```

**To Reproduce**
1. Create a project from the start-axum template
2. Replace HomePage with this:
```html
#[component]
pub fn HomePage() -> impl IntoView {
    let hash = use_location().hash;
    view! {
        <Show when=move || !hash.get().is_empty()>
            <p> "Hydration error </p>
        </Show>
    }
}
```
3. Navigate to /#test from the browser.
4. Open the console and see a hydration error.

**Next Steps**
- [ ] I will make a PR
- [x] I would like to make a PR, but need help getting started
- [ ] I want someone else to take the time to fix this
- [ ] This is a low priority for me and is just shared for your information

**Additional context**
This is theoretically expected if you know that fragments are not sent in requests but it might still be worth it to prevent the hydration error in the framework.
