### ISSUE TITLE
Leptos does not allow to build documentation site

### ISSUE THREAD

**Issue by mondeja** [leptos-rs/leptos#750]
If I run `cargo doc --no-deps` the next warning is raised and no builds are produced.

```
`mount_to_body` should not be called outside the browser.
```

Tried for a components-only library with a configuration like:

```toml
[package]
name = "components"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = "0.2.4"
```

```rust
// src/lib.rs
use leptos::*;

#[component]
pub fn Hello(cx: Scope) -> impl IntoView {
    view! { cx,
        <p>"Hello"</p>
    }
}
```

Also tried with typical CSR and SSR layouts, as well using `--target wasm32-unknown-unknown`. Is currently any command that could produce a documentation site for components?

Thanks for this framework, is really awesome!
