### ISSUE TITLE
counter_isomorphic compile error: `hydrate` and `ssr` enabled as features

### ISSUE THREAD

**Issue by agilarity** [leptos-rs/leptos#916]
Run `cargo make test -p counter_isomorphic` from `leptos/examples` to reproduce.

**Comment by gbj** [comment]
I'm not sure what you're trying to achieve with this (there are no tests for that example). If you use `cargo make check` or something, it will avoid the mutually exclusive features that are defined in `Cargo.toml`. I'm not sure why `cargo make test` doesn't do that, but it never has if you run it from any of the sub-directories, as far as I know.
```toml
[package.metadata.cargo-all-features]
denylist = ["actix-files", "actix-web", "leptos_actix", "stable"]
skip_feature_sets = [["ssr", "hydrate"]]
``` 

You can run tests for the separate features separately (`cargo test --features=ssr`, `cargo test --features=hydrate`)
