### ISSUE TITLE
View macro should support style: syntax

### ISSUE THREAD

**Issue by engiwengi** [leptos-rs/leptos#942]
Might be missing an actual feature as I've only just picked up leptos but the intuitive approach doesn't work. I didn't see anything in the book, examples or other issues that mention this.

What I thought might work:
```rust
view! { cx, <div style:--columns=5></div> }
```
```css
div { 
  display: grid;
  grid-template-columns: repeat(var(--columns), 120px);
}
```
Above is just an example of using [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) in a way I might expect to be able to in leptos.

A workaround is to assign the whole style like `style="--columns:5"` but it would be nice if the view macro supported this.
